### ISSUE TITLE
Launcher not displaying on multiple monitors

### ISSUE THREAD

**Issue by Semperverus** [linuxdeepin/developer-center#780] opened 2019-01-04 07:10 UTC
When running Deepin with multiple monitors, there is no way to allow multiple docks to show up on each monitor.

Additionally, it seems that you can only right click and show files on the monitor that has the launcher.

**Comment by Semperverus** [comment] 2019-01-04 07:39
![Current desktop](https://user-images.githubusercontent.com/613225/50677795-b06b6600-0fb0-11e9-847d-e134ab6f27eb.png)

![What it would look like with taskbars/launchers across all screens](https://user-images.githubusercontent.com/613225/50677806-bfeaaf00-0fb0-11e9-8ffa-569483f06ddd.png)

**Comment by hualet** [comment] 2019-01-06 09:47
It's by design, Dock/Desktop/Launcher only show in the primary screen, not other ones.
So closing...

**Closed by hualet** 2019-01-06 09:47 UTC

**Comment by ivashin** [comment] 2019-02-06 13:37
That's an unfortunate design decision. Having dock duplicated, and Launcher on active screen, would be very convenient for productivity in a multi-monitor setup.
