### ISSUE TITLE
Update prompt at shutdown

### ISSUE THREAD

**Issue by Octavian-Q** [linuxdeepin/developer-center#3244] opened 2022-06-14 05:40 UTC
### Discussed in https://github.com/linuxdeepin/developer-center/discussions/3239

<div type='discussions-op-text'>

<sup>Originally posted by **Octavian-Q** June 10, 2022</sup>
Hi, I am writing quite often here and sorry if bother a lot :)
Having this screen randomly appears when I want to shutdown the pc. There are no updates waiting, everything installed and up to date but still appears. Maybe is an issue, I am not sure 🤔 
![3AD97B25-8910-42DA-A32B-E531C55E68CE](https://user-images.githubusercontent.com/98664445/173069888-0eb9c276-a683-4261-ba53-5e0a70472d33.jpeg)
</div>

**Comment by BLumia** [comment] 2022-06-14 06:32
I saw the discussion but I never got this situation. The store process is requesting to block the shutdown, the prompt is not caused by `apt`. I'm not sure if it's a bug. cc @babyfengfjx

**Comment by Octavian-Q** [comment] 2022-06-14 10:23
I noticed if I enable Auto Download Updates, this screen starts to appear after short time 
![Screenshot_dde-control-center_20220614132108](https://user-images.githubusercontent.com/98664445/173555418-eca3ea4e-3b23-4ea3-846d-3bea75b3dfa1.png)

**Comment by raspin0** [comment] 2022-06-14 19:13
> I saw the discussion but I never got this situation. The store process is requesting to block the shutdown, the prompt is not caused by `apt`. I'm not sure if it's a bug. cc @babyfengfjx

It's a very frequent bug. I've seen 3+ reports about this issue.

**Comment by BLumia** [comment] 2022-06-15 01:25
> > I saw the discussion but I never got this situation. The store process is requesting to block the shutdown, the prompt is not caused by `apt`. I'm not sure if it's a bug. cc @babyfengfjx
> 
> It's a very frequent bug. I've seen 3+ reports about this issue.

Could you link those reports so we could check them out and look into them? Thanks!

**Comment by babyfengfjx** [comment] 2022-06-15 08:35
Thanks for the feedback, we will continue to pay attention to this issue, if there is a mandatory method, please let us know, we will submit the optimization analysis in a timely manner after the recurrence.

**Comment by raspin0** [comment] 2022-06-15 13:37
> > > I saw the discussion but I never got this situation. The store process is requesting to block the shutdown, the prompt is not caused by `apt`. I'm not sure if it's a bug. cc @babyfengfjx
> > 
> > 
> > It's a very frequent bug. I've seen 3+ reports about this issue.
> 
> Could you link those reports so we could check them out and look into them? Thanks!

In details they don't go beyond what's already in here. On my end it reproduces without any interaction on both computers. Skype also introduces similar problem with "Ensure a clean shutdown".

**Comment by babyfengfjx** [comment] 2023-05-26 09:32
I apologize that the issue has not been reproduced and optimized. Due to the fact that there will be no major updates or maintenance for the V20 version, if there are similar or other new issues in the V23 version, please feel free to submit an issue. We will close this issue and thank you very much for your understanding.

**Closed by babyfengfjx** 2023-05-26 09:32 UTC
