### ISSUE TITLE
Deepin V20.1 (1010) journalctl -p 0 to 5 on 01/05/2021 at 21:28pm

### ISSUE THREAD

**Issue by serial02** [linuxdeepin/developer-center#2014] opened 2021-01-06 00:37 UTC
Hello Deepin V20.1 (1010) Team

Following are reports from Deepin V20.1 (1010) journalctl -p 0 to 5 on 01/02/2021 at 13:34 pm
If possible, emphasize journalctl -p 2 and 5

https://pastebin.com/X86VqDaM
https://pastebin.com/raw/X86VqDaM

```
journalctl -p 2
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
-- Logs begin at Sat 2020-12-26 13:54:43 -03, end at Tue 2021-01-05 20:39:52 -03. --
dez 28 10:11:51 edson-PC6450br deepin-deepinid-daemon[8010]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 28 15:36:23 edson-PC6450br deepin-deepinid-daemon[9404]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 28 18:35:01 edson-PC6450br deepin-deepinid-daemon[7252]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 28 20:38:26 edson-PC6450br deepin-deepinid-daemon[5438]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 28 21:38:00 edson-PC6450br deepin-deepinid-daemon[8009]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 29 09:52:50 edson-PC6450br deepin-deepinid-daemon[6961]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 29 17:00:33 edson-PC6450br deepin-deepinid-daemon[7401]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 29 20:56:40 edson-PC6450br deepin-deepinid-daemon[7352]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 29 22:13:24 edson-PC6450br deepin-deepinid-daemon[7916]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 30 10:03:10 edson-PC6450br deepin-deepinid-daemon[6933]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 31 09:45:11 edson-PC6450br deepin-deepinid-daemon[7506]: [CRI] main.go:34: quit with anothe
-- Reboot --
dez 31 10:05:06 edson-PC6450br deepin-deepinid-daemon[5587]: [CRI] main.go:34: quit with anothe
-- Reboot --
jan 01 09:05:54 edson-PC6450br deepin-deepinid-daemon[8110]: [CRI] main.go:34: quit with anothe
-- Reboot --
jan 02 20:12:24 edson-PC6450br deepin-deepinid-daemon[5774]: [CRI] main.go:34: quit with anothe
-- Reboot --
jan 02 22:36:58 edson-PC6450br deepin-deepinid-daemon[7383]: [CRI] main.go:34: quit with anothe
-- Reboot --
jan 04 21:45:10 edson-PC6450br deepin-deepinid-daemon[8833]: [CRI] main.go:34: quit with anothe
-- Reboot --
jan 05 02:10:59 edson-PC6450br deepin-deepinid-daemon[9182]: [CRI] main.go:34: quit with anothe
-- Reboot --
jan 05 10:15:49 edson-PC6450br deepin-deepinid-daemon[7544]: [CRI] main.go:34: quit with anothe
-- Reboot --
jan 05 20:16:41 edson-PC6450br deepin-deepinid-daemon[8930]: [CRI] main.go:34: quit with anothe
lines 17-38/38 (END)
```

Other journalctl reports for Deepin V20.1 (1010)
https://pastebin.com/u/SerialCom

@felixonmars
@juteman

**Comment by LeiGangZheng** [comment] 2021-01-06 02:03
It means that there is another instance. Please confirm that only one instance can exist, thinks..

**Comment by BLumia** [comment] 2022-03-28 02:52
Sorry for the super late response. It's already answered by @LeiGangZheng, Only one `deepin-deepinid-daemon` process should be running at the same time. 

Since I also couldn't reproduce this issue on deepin v20.4, I'm closing this issue for now. If you still have this issue on the most recent version of deepin, feel free to open another issue with detail information so we could look into it. Thanks!

**Closed by BLumia** 2022-03-28 02:52 UTC
