### ISSUE TITLE
application menu doesn't work

### ISSUE THREAD

**Issue by LinuxUserGD** [linuxdeepin/developer-center#729] opened 2018-12-07 19:54 UTC
## Application menu doesn't work

When I click on the application menu, nothing happens. The applications doesn't show up.

### Distro & Version

Linux Deepin 15.7

latest packages on Arch Linux (Antergos)

**Comment by hualet** [comment] 2018-12-13 01:49
Please file issues with the ISSUE TEMPLATE, at least what's your distribution, what's your package version, etc. so we can save time asking for more information.

Anyway, you can try "dde-launcher" or "deepin-launcher" in your terminal, and see what it complains.

**Comment by hualet** [comment] 2018-12-14 01:10
> I've updated the issue. I can't try the commands "dde-launcher" or "deepin-launcher" for now because I changed to Gentoo.

Will you give it another chance? or I'll close this issue for now since no one can reproduce this issue anymore.

**Comment by hualet** [comment] 2018-12-18 04:45
OK, close then.

**Closed by hualet** 2018-12-18 04:45 UTC
Labels: info needed
