### ISSUE TITLE
Modal findow button label bug

### ISSUE THREAD

**Issue by denisoster** [linuxdeepin/developer-center#539] opened 2018-05-27 13:25 UTC
Russian language.
Please, fix it:
![deepinscreenshot_ - _20180527162400](https://user-images.githubusercontent.com/15886355/40586419-72d49ab2-61ca-11e8-9a85-f1d64909b323.png)

**Comment by BLumia** [comment] 2018-07-04 01:54
Hi and thanks for reporting this issue.

This issue has been fixed in recent development ([dde-file-manager/develop2.0#1c3d329](https://github.com/linuxdeepin/dde-file-manager/commit/1c3d329e4413d779781cd96088dfe5afc9af6cb4) ), and will be delivery in dde-file-manager v1.8 release. Please wait for the update or build a develop package yourself for a sneakpeek :)

btw a preview for ya (the dialog title is not a bug and should works fine on your computer, i'm just testing it on a computer with zh_CN locale):

![dfmrudlg](https://user-images.githubusercontent.com/10095765/42252545-b7766cdc-7f6f-11e8-8804-4d7e7bd7350d.png)

**Closed by BLumia** 2018-07-04 01:54 UTC
