### ISSUE TITLE
Background Blur Uses Default Wallpaper

### ISSUE THREAD

**Issue by stevedude** [linuxdeepin/developer-center#154] opened 2017-02-03 18:49 UTC
I recently upgraded Manjaro Deepin to Manjaro Deepin 15.4rc. I use the 64-bit version. After a recent upgrade to Deepin 15.4rc, whenever you use the Launcher icon or the screen Hot Spot for the Launcher, the background blur does not use your current desktop, but the default wallpaper.

After deleting the contents of  /var/cache/image-blur and logging out then logging in again, the background blur acts normally
![mybackground](https://cloud.githubusercontent.com/assets/8483863/22603985/829503dc-ea17-11e6-80b4-9b451192ce68.png)
![launcherbackground](https://cloud.githubusercontent.com/assets/8483863/22603990/8559154a-ea17-11e6-8251-68e5d00bdd31.png)

.

**Comment by hualet** [comment] 2017-02-04 01:21
Just want to confirm that you do have only one workspace, right ?

**Comment by oberon2007** [comment] 2017-02-04 09:25
I have the same thing and have definitely multiple workspaces. This might however be connected to the manjaro specific wallpaper package which also comes with pre-blurred image files. I haven't looked at this for quite a while... Will check that later... :wink:

**Comment by hualet** [comment] 2017-02-04 12:01
I think I've found the cause of this bug, will fix it later 😄

**Comment by stevedude** [comment] 2017-02-06 18:06
Yes, this is only for a single workspace.  Thank you for looking into this. The work-around solved the issue, but I wanted to bring it to someone's attention.

**Comment by DasJott** [comment] 2017-06-07 12:32
Can not confirm here. Using Arch Anywhere.

**Comment by hualet** [comment] 2017-06-08 01:12
Yeah, close it, thanks for reminding :+1:

**Closed by hualet** 2017-06-08 01:12 UTC

**Comment by SalahAdDin** [comment] 2018-05-14 15:38
Related: https://github.com/linuxdeepin/deepin-wallpapers/issues/2
