### ISSUE TITLE
Bug report: Dual monitor not recognized following upgrade

### ISSUE THREAD

**Issue by emulienfou** [linuxdeepin/developer-center#2211] opened 2022-01-24 14:11 UTC
## Issue: Bug or suggest report 「问题 或 建议 反馈」 

Following some recent package upgrade, it's impossible to extend dual monitor anymore. Here is the list of upgraded packages:
```
022-01-21 16:56:18 install libdeepin-authenticate:amd64 <none> 1:1.3.6-1
2022-01-21 16:56:48 install libnppc9.2:amd64 <none> 9.2.148-7
2022-01-21 16:56:49 install libnppicc9.2:amd64 <none> 9.2.148-7
2022-01-21 16:56:49 install libnppidei9.2:amd64 <none> 9.2.148-7
2022-01-21 16:56:49 install libnppig9.2:amd64 <none> 9.2.148-7
2022-01-21 16:56:50 install libdocparser:amd64 <none> 1.0.1-1
2022-01-21 16:57:02 install dde-crypto:amd64 <none> 1.0.1-1
2022-01-21 16:57:04 install dde-wloutput:amd64 <none> 1.0.1-1
2022-01-21 16:57:04 install dde-wloutput-daemon:amd64 <none> 1.0.1-1
2022-01-21 16:57:04 install dde-wayland-config:amd64 <none> 1.0.3-1
2022-01-21 16:57:05 install dde-wldpms:amd64 <none> 1.0.1-1
2022-01-21 16:57:06 install libdareader1:amd64 <none> 1.0.0-1
2022-01-21 16:57:16 install dde-dconfig-daemon:amd64 <none> 0.0.7-1
2022-01-21 16:57:20 install linux-headers-5.10.83-amd64-desktop:amd64 <none> 5.10.83-amd64-desktop-20.00.50.06-release
2022-01-21 16:57:24 install linux-image-5.10.83-amd64-desktop:amd64 <none> 5.10.83-amd64-desktop-20.00.50.06-release
2022-01-21 16:57:30 install dcc-dock-plugin:amd64 <none> 5.5.9-1
2022-01-21 16:57:30 install dcc-network-plugin:amd64 <none> 1.0.2-1
2022-01-21 16:57:30 install dde-manual-content:all <none> 1.0.3-1
2022-01-21 16:57:34 install dde-network-dialog:amd64 <none> 1.0.2-1
2022-01-21 16:57:34 install libqt5waylandclient5:amd64 <none> 5.15.1.3-1+dde
2022-01-21 16:57:34 install dde-qt5wayland-plugin:amd64 <none> 5.0.46-1
2022-01-21 16:57:44 install libenchant-2-2:amd64 <none> 2.2.12-1
2022-01-21 16:58:03 install xorg-sgml-doctools:all <none> 1:1.11-1
2022-01-21 16:58:04 install x11proto-dev:all <none> 2018.4-4
2022-01-21 16:58:04 install x11proto-core-dev:all <none> 2018.4-4
2022-01-21 16:58:04 install libxau-dev:amd64 <none> 1:1.0.8.1-1+rebuild
2022-01-21 16:58:04 install libxdmcp-dev:amd64 <none> 1:1.1.2-3
2022-01-21 16:58:04 install xtrans-dev:all <none> 1.3.5-1+apricot
2022-01-21 16:58:04 install libpthread-stubs0-dev:amd64 <none> 0.4-1
2022-01-21 16:58:05 install libxcb1-dev:amd64 <none> 1.13.1-2
2022-01-21 16:58:05 install libx11-dev:amd64 <none> 2:1.6.12-1
2022-01-21 16:58:05 install libglx-dev:amd64 <none> 1.3.2-1
2022-01-21 16:58:05 install libgl-dev:amd64 <none> 1.3.2-1
2022-01-21 16:58:05 install libegl-dev:amd64 <none> 1.3.2-1
2022-01-21 16:58:05 install libgles1:amd64 <none> 1.3.2-1
2022-01-21 16:58:05 install libgles-dev:amd64 <none> 1.3.2-1
2022-01-21 16:58:05 install libopengl0:amd64 <none> 1.3.2-1
2022-01-21 16:58:05 install libopengl-dev:amd64 <none> 1.3.2-1
2022-01-21 16:58:06 install libglvnd-dev:amd64 <none> 1.3.2-1
2022-01-21 16:58:06 install libgl1-mesa-dev:amd64 <none> 20.3.4.2-1
2022-01-21 16:58:06 install libglu1-mesa-dev:amd64 <none> 9.0.0.1-1+rebuild
2022-01-21 16:58:06 install libvulkan-dev:amd64 <none> 1.2.162.0-1
2022-01-21 16:58:06 install x11proto-xext-dev:all <none> 2018.4-4
2022-01-21 16:58:06 install libxext-dev:amd64 <none> 2:1.3.3.1-1+rebuild
2022-01-21 16:58:06 install qt5-qmake-bin:amd64 <none> 5.15.1.9-1+dde
2022-01-21 16:58:06 install qt5-qmake:amd64 <none> 5.15.1.9-1+dde
2022-01-21 16:58:07 install qtbase5-dev-tools:amd64 <none> 5.15.1.9-1+dde
2022-01-21 16:58:07 install qtbase5-dev:amd64 <none> 5.15.1.9-1+dde
2022-01-21 16:58:08 install libkf5wayland-dev:amd64 <none> 4:5.57.0.6-1+eagle
2022-01-21 16:58:09 install dock-network-plugin:amd64 <none> 1.0.2-1
2022-01-21 16:58:09 install dss-network-plugin:amd64 <none> 1.0.2-1
2022-01-21 16:58:10 install enchant-2:amd64 <none> 2.2.12-1
2022-01-21 16:58:15 install libkf5wayland-doc:all <none> 4:5.57.0.6-1+eagle
2022-01-21 16:58:15 install libqt5opengl5-dev:amd64 <none> 5.15.1.9-1+dde
```

Here is the result of the command `xrandr`:
```
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
DP-1 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 521mm x 293mm
   1920x1080     60.00*+  50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1440x576      50.00  
   1024x768      75.03    70.07    60.00  
   1440x480      60.00    59.94  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    66.67    60.00    59.94  
   720x400       70.08  
DP-2 connected (normal left inverted right x axis y axis)
   1920x1080     60.00 +
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    66.67    59.94  
   720x400       70.08  
HDMI-1 disconnected (normal left inverted right x axis y axis)
```

As you can see, DP-2 is available in the list of mode:
<img src="https://i.ibb.co/C5yKk6b/image-2022-01-24-090923.png" alt="image-2022-01-24-090923" border="0"/>

> I can duplicate or switch from DP-1 to DP-2 without issues

**Comment by germsb** [comment] 2022-01-26 22:35
Since 20.4 
Can switch from DVI-I-1 to DP-0 without issues but can't duplicate or extend screens
![Imgur](https://i.imgur.com/qIC6RPBh.jpg)
```bash
~$ xrandr
Screen 0: minimum 8 x 8, current 2560 x 1440, maximum 16384 x 16384
DVI-I-1 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
   2560x1440     59.95*+
   2048x1280     60.00  
   1920x1200     59.88  
   1920x1080     60.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1600x1000     60.00  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     75.02  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   640x480       75.00    59.94  
DP-0 connected (normal left inverted right x axis y axis)
   2560x1440     59.95 +  74.92  
   2048x1280     59.96  
   1920x1080     69.92    60.00    59.94    50.00  
   1680x1050     59.95  
   1600x1200     60.00  
   1600x900      60.00  
   1440x900      59.89  
   1280x1024     60.02  
   1280x720      59.94    50.00  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       59.94  
   640x480       59.94    59.93  
```

After nvidia-settings install, we can see that the second screen is disabled
![Imgur](https://i.imgur.com/84UeAXCl.jpg)

Everything is back to normal after activating the latter (just the time of the session)
![Imgur](https://i.imgur.com/SSUJeril.jpg)
![Imgur](https://i.imgur.com/7vNaDi0h.jpg)

**Comment by emulienfou** [comment] 2022-01-27 00:28
FYI: I needed to reinstall Deepin to fix the my issue!

**Comment by babyfengfjx** [comment] 2022-02-15 05:28
> 

So  the problem is ok ,after  re-installed?At present, it is possible to have a certain relationship with the graphics card driver, may have a certain impact on the driver after the kernel upgrade, thanks for your feedback, this issue we record and pay attention, hoping to recover and submit optimization.

**Comment by babyfengfjx** [comment] 2022-03-11 05:30
Since we have not been in touch for a long time, we will close the issue first. If there is any problem later, you can submit the issue in time. Thank you for your feedback.

**Closed by babyfengfjx** 2022-03-11 05:30 UTC
