### ISSUE TITLE
System freezes when some flatpak apps are opened

### ISSUE THREAD

**Issue by igatjens** [linuxdeepin/developer-center#1955] opened 2020-10-22 22:05 UTC
System freezes when some flatpak apps are opened

When running the Zoom and Gimp flatpak applications, the system freezes, you can only move the pointer or open a terminal with the Ctrl + Alf + F2 keys.

Terminal opened with Ctrl + Alt + F2 works fine.

The Zoom and Gimp versions were downloaded at flathub.org

https://flathub.org/apps/details/org.gimp.GIMP
https://flathub.org/apps/details/us.zoom.Zoom

The version of the applications is as follows.

```
flatpak list | grep -E "zoom|gimp"
Programa de manipulación de imágenes de GNU - Cree imágenes y edite fotografías org.gimp.GIMP   2.10.22 stable  x86_64  flathub system
Manual  org.gimp.GIMP.Manual            2.10    x86_64  flathub system
Zoom - Video Conferencing, Web Conferencing, Webinars, Screen Sharing   us.zoom.Zoom    5.3.472687.1012 stable  x86_64  flathub system
```

The system version is as follows.

```
 cat /etc/os-version 
[Version] 
SystemName=deepin
SystemName[zh_CN]=深度操作系统
ProductType=Desktop
ProductType[zh_CN]=桌面
EditionName=Community
EditionName[zh_CN]=社区版
MajorVersion=20
MinorVersion=1003
OsBuild=11031.105
```

I attach the record created with the command `sudo deepin-feedback-cli`

[deepin-feedback-cli-Deepin-20-all-20201022-151257.tar.gz](https://github.com/linuxdeepin/developer-center/files/5426161/deepin-feedback-cli-Deepin-20-all-20201022-151257.tar.gz)

**Comment by martinlindelof** [comment] 2020-10-23 08:40
I rolled back update. Had same issues with Flatpak Discord. And Steam playing games.
UI frozen, could be graphic drivers glitch. Because could hear Steam game load and play lobby sounds.

**Comment by igatjens** [comment] 2020-10-25 20:33
The system also freezes with with OBS Studio.

```
flatpak list | grep OBS
OBS Studio - Live streaming and video recording software        com.obsproject.Studio   26.0.2  stable  x86_64  flathub system
```

**Comment by lorenzosoannini** [comment] 2020-10-28 17:59
Same issue on Arch Linux but it seems to freeze when the system is doing heavy operations (even if the CPU and RAM usage is not too high) but maybe it's just random.
The graphics freezes but sounds and pointer still work, furthermore if you click on something the system is actually doing the task but with all graphics freezed.

OS: Arch Linux x86_64                                               
Host: XPS 13 9360                                                   
Kernel: 5.9.1-arch1-1                                               
Resolution: 3200x1800                                               
DE: Deepin Beta                                                     
WM: Mutter(DeepinGala)

**Comment by alexk136** [comment] 2020-11-08 15:02
Same! Stem freeze.

OS: deepin 20 5.4.45.

**Comment by Hi-Phile** [comment] 2020-11-20 01:20
I had same problems, I noticed this with Skype and Signal Desktop.  I removed them from the Software store and installed them from the Arch Repository, no more freezing.

**Comment by lfgoulart** [comment] 2020-11-25 15:18
I had a total DDE freeze when I click on the clock icon and open the calendar. It also happens when I use the file manager when to open something with a flat pack application (Image viewer, Gimp and others).

**Comment by alexk136** [comment] 2020-11-25 15:29
I think problem in dde-doc, any action on it have delay after a  while.. open doc, open any app from doc.. everything, even animation. Deskotop or Alt-Tab switch works fine.

**Comment by martinlindelof** [comment] 2020-11-26 09:31
Tried to upgrade to latest version 2020-11-25 and run flatpak again.
Same issue, every app that seems to draw OpenGL Windows in fullscreen causes freeze.
> Installed blender with flatpak = Deepin WM Freeze
> Downloaded blender, and symlinked /usr/bin/blender = No WM Freeze
Same with Steam games running from Steam downloaded with flatpak

**Comment by peeweep** [comment] 2021-12-30 03:45
I tried gimp and it work fine.
Since this problem has not reproduced in the latest version of Deepin, I will close this issue.

**Closed by peeweep** 2021-12-30 03:45 UTC
