### ISSUE TITLE
Deepin bug after Manjaro update

### ISSUE THREAD

**Issue by Carl-Marx** [linuxdeepin/developer-center#355] opened 2017-08-26 02:41 UTC
Hello,

I've noticed a bug after Manjaro's 08/18 update. I think it's caused by dtksettings.
Desktop icons are invisible, the font is bigger, the dock is bugged... please help.

![deepinscreenshot_20170825233821](https://user-images.githubusercontent.com/19856591/29737989-d6cac28a-89ee-11e7-8dbb-7d9794c4f9e7.png)

**Comment by oberon2007** [comment] 2017-08-27 07:11
I cannot confirm this. Here everything looks normal with latest Manjaro packages.
Do you by any chance still have **qt5ct** installed? If so, remove it and verify that the output of
``echo $QT_QPA_PLATFORMTHEME`` returns empty.

**Comment by oberon2007** [comment] 2017-08-27 07:14
![deepin](https://user-images.githubusercontent.com/11800714/29747857-130631ac-8b08-11e7-8f4f-db8c8cc23594.png)

**Comment by ag14774** [comment] 2017-10-28 16:48
After the last update the font is thicker(like it is bold) in text editors. Both in gedit and Atom:
![deepinscreenshot_select-area_20171028184658](https://user-images.githubusercontent.com/10788242/32136576-7336f668-bc10-11e7-8fc9-f6cf3770b34e.png)

The font in terminal is also thicker

**Comment by oberon2007** [comment] 2017-10-28 17:13
I'm sorry, I cannot reproduce. Seems to be your settings. Here everything looks fine:

![deepin-font](https://user-images.githubusercontent.com/11800714/32136763-0a082582-bc14-11e7-9b2a-e3a0f8025e58.png)

**Comment by ag14774** [comment] 2017-10-28 18:54
hmm under "Font" what is Monospaced Font options supposed to do? It's currently set to DejaVu Sans Mono but changing it doesn't seem to change anything? Maybe that's related?

**Comment by ag14774** [comment] 2017-10-28 18:57
ok `echo $QT_QPA_PLATFORMTHEME` returns qt5ct but I don't have it installed. That must be it

**Comment by felixonmars** [comment] 2017-10-28 19:01
That variable should not be set manually. Is that something set by Manjaro or yourself?

**Comment by ag14774** [comment] 2017-10-28 19:13
I haven't done anything to set it so I am guessing it's Manjaro maybe? are there other applications that set that variable?

**Comment by ag14774** [comment] 2017-10-28 19:20
I have this line in ~/.profile:
`[[ "$XDG_CURRENT_DESKTOP" == "KDE" ]] || [[ "$XDG_CURRENT_DESKTOP" == "GNOME" ]] || export QT_QPA_PLATFORMTHEME="qt5ct"`

Is this supposed to be there? I don't know how it got there

**Comment by oberon2007** [comment] 2017-10-28 19:24
Right, I know it shouldn't be set, but I just realize that our build tools configure it in ~/.profile for any environment except KDE 😉 
Please remove the line there! Thanks.

**Comment by ag14774** [comment] 2017-10-28 19:30
Thanks. I removed the line and rebooted. Now the variable returns empty but the font is still thicker. Changing the Monospaced Font option still doesn't do anything.

**Comment by ag14774** [comment] 2017-10-28 19:40
Also is com/deepin/wrap/gnome/desktop/interface/monospace-font-name supposed to do anything? I tried changing that to 'Monospace 15' instead of 'Monospace 11' to see if it makes any difference but it doesn't(after reboot)

**Comment by hualet** [comment] 2017-10-30 01:06
@jouyouyun

**Comment by jouyouyun** [comment] 2017-10-30 01:20
After the monospace font changed, please paste the outputs of command `fc-match mono`.

**Comment by ag14774** [comment] 2017-10-30 02:02
` $fc-match mono
Fontconfig error: "/home/ageorgiou/.config/fontconfig/conf.d/99-deepin.conf", line 1: Unsupported version '2.0'

VeraMono.ttf: "Bitstream Vera Sans Mono" "Roman"
`

**Comment by jouyouyun** [comment] 2017-10-30 02:20
Please update the file `/home/ageorgiou/.config/fontconfig/conf.d/99-deepin.conf`, thanks!

**Comment by jouyouyun** [comment] 2017-10-30 02:57
What's the version of `fontconfig` and `freetype`?

**Comment by jouyouyun** [comment] 2017-10-30 03:34
@ag14774 Try modified `<?xml version="2.0"?>` to `<?xml version="1.0"?>` after font changed by edited the file `/home/ageorgiou/.config/fontconfig/conf.d/99-deepin.conf`.

**Comment by jouyouyun** [comment] 2017-10-30 03:36
There is a same bug, please see: https://bbs.deepin.org/forum.php?mod=viewthread&tid=44705

**Comment by ag14774** [comment] 2017-10-30 09:13
I could find these packages:
`freetype2` : `2.8.1-1`
`fontconfig` : `2.12.6-1`
 Your trick with the xml version change works for all the other fonts. But DejaVuSansMono defaults to the bold one:

`$fc-match mono`
`DejaVuSansMono-Bold.ttf: "DejaVu Sans Mono" "Bold"`

In the control center I have selected DejaVu Sans Mono. How can I remove the "bold" part?

**Comment by ag14774** [comment] 2017-10-30 09:17
@oberon2007 Could you tell me what version of `freetype2` and `fontconfig` should I have?

Also can you tell me what is the output of `fc-match mono`? Is it also `DejaVuSansMono-Bold.ttf`?

**Comment by jouyouyun** [comment] 2017-10-31 01:58
Paste the outputs of ` fc-list |grep 'DejaVu Sans Mono'`

**Comment by jouyouyun** [comment] 2017-10-31 02:50
Fixed the bug of font xml version, see: https://github.com/linuxdeepin/dde-daemon/commit/7ed2035634cf296b6966c6abade65b48795721dd

**Comment by ag14774** [comment] 2017-10-31 10:40
This is the output:
```
$ fc-list |grep 'DejaVu Sans Mono'
/usr/share/fonts/TTF/DejaVuSansMono.ttf: DejaVu Sans Mono:style=Book
/usr/share/fonts/TTF/DejaVuSansMono-Oblique.ttf: DejaVu Sans Mono:style=Oblique
/usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf: DejaVu Sans Mono:style=Bold
/usr/share/fonts/TTF/DejaVuSansMono-BoldOblique.ttf: DejaVu Sans Mono:style=Bold Oblique
```

**Comment by jouyouyun** [comment] 2017-10-31 11:43
@ag14774 Your 'DejaVu Sans Mono' only bold style, so it's DejaVuSansMono-Bold.ttf, no fault.

**Comment by ag14774** [comment] 2017-10-31 14:32
May I ask what is the default monospace font of Deepin? Cause I never changed it and I am sure that the font is thicker now.

**Comment by jouyouyun** [comment] 2017-11-01 01:04
Now the default monospace is 'Noto Mono', the deepin control-center unsupport font style settings.

**Comment by ag14774** [comment] 2017-11-01 02:03
Ok I switched to Noto Mono and changed the xml version to 1.0. The font is better now. Thanks
@Carl-Marx You can close this now if you want :p Sorry I hijacked your issue

**Closed** 2017-11-02 14:55 UTC
