### ISSUE TITLE
Crash On Play The Video

### ISSUE THREAD

**Issue by marcellino03** [linuxdeepin/developer-center#1695] opened 2020-04-21 07:57 UTC
My deepin is crash when am play the video use default mp4 player.

**Comment by xmuli** [comment] 2020-05-06 07:11
Without a detailed description, it can be difficult to reproduce, leading to omissions or delays

**Comment by justforlxz** [comment] 2021-06-10 02:21
Can you add detailed information, such as software, test videos, etc.

**Comment by Zeno-sole** [comment] 2022-02-22 02:18
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue

**Closed by Zeno-sole** 2022-02-22 02:18 UTC
Labels: need | need more information
