### ISSUE TITLE
No way to close notifications

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#1781] opened 2020-06-28 06:25 UTC
There some notifications which need to be closed manually.

But the problem is that there's no close button for the notifications. We can close them in the notification panel but not when they are being shown.

**Comment by SiamSami** [comment] 2020-06-29 09:48
@xmuli Anything?

**Comment by xmuli** [comment] 2020-06-30 03:03
New features for "Notifications" are currently under development and will be available at a later stage (you can find them in the Settings Center).

**Comment by gardotd426** [comment] 2020-07-26 23:38
Duplicate of #1752

**Comment by xmuli** [comment] 2020-07-27 01:36
This feature has been released on uos sp2 (deepin will be delayed)

![image](https://user-images.githubusercontent.com/33887845/88495432-71669080-cfec-11ea-9241-771eb581ecf1.png)

**Comment by gardotd426** [comment] 2020-07-27 02:29
I can't read chinese so I don't know what any of that says, but it looks like everything that's already available.

You can disable notifications and stuff already, but it doesn't work. 

I go in, disable notifications, the system try indicator even SHOWS they're disabled, and yet they still show up

**Comment by gardotd426** [comment] 2020-07-27 03:16
I can't read chinese so I don't know what any of that says, but it looks like everything that's already available.

You can disable notifications and stuff already, but it doesn't work. 

I go in, disable notifications, the system try indicator even SHOWS they're disabled, and yet they still show up

**Comment by tsic404** [comment] 2021-12-29 08:51
![image](https://user-images.githubusercontent.com/48748112/147643979-073f7f2f-bf55-4f3f-a8d2-83fb72f84361.png)
now you can disable notifications in dde-control-center

**Closed by tsic404** 2021-12-29 08:51 UTC
