### ISSUE TITLE
[Bug] cannot unzip large files using deepin archive manager

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#3161] opened 2022-05-15 07:36 UTC
### SUMMARY | 问题概要
It is not possible to unzip large files (around 2 GB) using deepin archive manager

### STEPS TO REPRODUCE | 复现步骤

1. Open an archive file of size around 2 GB
2. Try to extract it
3. Says that the archive file is damaged even if it isn't.

### OBSERVED RESULT | 观察到的结果
![Record_select-area_20220515132622](https://user-images.githubusercontent.com/33563064/168462331-13fd2c23-7de6-4103-8fcc-295aa11fdfd5.gif)
It says that the archive file is damaged even though it isn't.

### EXPECTED RESULT | 期望的结果
It should be able to extract without any issue.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
OS: Deepin 20.5
Deepin Archive Manager version: 5.12.5

### ADDITIONAL INFORMATION | 额外补充
I can extract that archive file using the `unzip` command in the terminal, which means that the archive file isn't damaged in any way. But Deepin Archive Manager says that it is damaged and so it won't extract it.

**Comment by luodeepin** [comment] 2022-05-16 07:03
Excuse me! Your side of the problem, I have not reproduced the current, please ask your package is compressed on deepin or compressed on another system?

**Comment by BLumia** [comment] 2022-05-16 07:07
Hi @SiamSami. Could you provide a file which can be used to reproduce this issue? Or steps to create a file that can be used to reproduce this issue? Thanks!

**Comment by SiamSami** [comment] 2022-05-16 14:14
> Excuse me! Your side of the problem, I have not reproduced the current, please ask your package is compressed on deepin or compressed on another system?

It was actually compressed on another system

**Comment by SiamSami** [comment] 2022-05-16 14:24
> Hi @SiamSami. Could you provide a file which can be used to reproduce this issue? Or steps to create a file that can be used to reproduce this issue? Thanks!

Sure. Will look into that later.

**Comment by Octavian-Q** [comment] 2022-05-17 20:03
I also could not replicate the issue, I used 2 types of archive to test this, one with pictures other with videos. 2.5Gb and 2.4Gb respectively (both compressed outside Deepin) and extracted fine. Then I took pictures and compressed in deepin, then unzip also fine. I can only suspect it is a very specific bug not wide spread or either archive was encoded with some kind of tool (compression level/format) that Deepin doesn't like

**Comment by babyfengfjx** [comment] 2022-05-18 01:03
I wonder if this file will decompress properly on other systems?

**Comment by BLumia** [comment] 2022-08-02 07:01
Since no additional information was provided and not able to reproduce this issue with existing information, I'll close this issue for now.

If you have additional information provided, please feel free to create a new issue to report (and put a link to this issue in the description if needed) so we can start reproducing this issue and look into it. Thanks!

**Closed by BLumia** 2022-08-02 07:01 UTC
Labels: triage | need more information
