### ISSUE TITLE
HDMI not recognized

### ISSUE THREAD

**Issue by WesleySantosMaxtelll** [linuxdeepin/developer-center#1948] opened 2020-10-17 02:27 UTC
I installed the deepin v20 on my laptop and my HDMI does not recognize when I connect it a second monitor.
I have tested hardware stuff and everything is fine, also, my HDMI was working just before I switch from another linux distro to this one. 

I am using a nvidia gtx 1050 ti mobile.

**Comment by xmuli** [comment] 2020-10-21 06:25
A reboot may take effect (happened to me too)

**Comment by peeweep** [comment] 2021-12-31 01:46
Since this problem has not reproduced in the latest version, I will close it first. If you still have problems, you can reopen this issue and provide more details.

**Closed by peeweep** 2021-12-31 01:46 UTC
