### ISSUE TITLE
[Support Reuqest] How to boot/shutdown sound in manjaro deepin? 

### ISSUE THREAD

**Issue by vesterlay** [linuxdeepin/developer-center#1909] opened 2020-09-12 17:05 UTC
After installing dde through manjaro architect and basically copying official deepin plymouth config I managed to get everything working quite well, but shutdown/startup/log out sound still does not work. I didn't manage to find any clues on the internet, so I though you may know if there are any additional steps required to get this working.

**Comment by juteman** [comment] 2020-09-14 01:23
Duplicate of #1862

**Comment by vesterlay** [comment] 2020-12-03 20:03
I moved to deepin 20 and the issue still reproduces. I know exactly why tho. Deepin sounds are working correctly, but they are using wrong device(I'm using external AMP/DAC). Setting up default device doesn't change much, but when you turn off all other sound devices from `pauvcontrol` it's working. Unfortunately it doesn't persist those settings after reboot, so it's not a fix but rather a workaround.

Also when I turn off a device from `pauvcontrol`, options in tray icon are frozen instead of disappearing. 
![Screen-Capture-select-area-20201](https://user-images.githubusercontent.com/39202451/101081871-f1a88e00-35aa-11eb-9309-84608aa33f1e.gif)

**Closed** 2021-03-25 16:48 UTC
Labels: duplicate | repeat or similar
