### ISSUE TITLE
Deepin file manager core dump

### ISSUE THREAD

**Issue by fosshelper** [linuxdeepin/developer-center#622] opened 2018-10-08 13:05 UTC
## Core dump by `dde-file-manager`

It has been the case since the last few months, that the file manager acts very unstably and keeps crashing whenever one tries to switch fast between directories and the like

## To Reproduce

1. Open Deepin file manager
2. Move around a bit in the directory structure, or plug in a usb device and try to mount it by clicking on the relevant sidebar option which appears (if automount is enabled).

## Expected behavior

The file manager shouldn't crash, and should work as expected.

## Journal logs

I am providing `journalctl` logs for the coredump here. These can be obtained by running `sudo journalctl -xe`.

```bash
Oct 08 00:00:00 hostname systemd[1]: Started Process Core Dump (PID 13571/UID 0).
-- Subject: Unit systemd-coredump@5-13571-0.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit systemd-coredump@5-13571-0.service has finished starting up.
--
-- The start-up result is RESULT.
Oct 08 00:00:00 hostname audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-coredump@5-13571-0 comm=">
Oct 08 00:00:00 hostname systemd[1]: dde-filemanager-daemon.service: Main process exited, code=dumped, status=11/SEGV
Oct 08 00:00:00 hostname audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=dde-filemanager-daemon comm="syste>
Oct 08 00:00:00 hostname systemd[1]: dde-filemanager-daemon.service: Failed with result 'core-dump'.
Oct 08 00:00:00 hostname dbus-daemon[654]: [system] Activating via systemd: service name='com.deepin.filemanager.daemon' unit='dde-filemanager-daemon.se>
Oct 08 00:00:00 hostname systemd[1]: dde-filemanager-daemon.service: Start request repeated too quickly.
Oct 08 00:00:00 hostname systemd[1]: dde-filemanager-daemon.service: Failed with result 'core-dump'.
Oct 08 00:00:00 hostname systemd[1]: Failed to start DDE File Manager Daemon.
-- Subject: Unit dde-filemanager-daemon.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit dde-filemanager-daemon.service has failed.
--
-- The result is RESULT.
Oct 08 00:00:00 hostname systemd-coredump[13572]: Process 13564 (dde-file-manage) of user 0 dumped core.

                                                Stack trace of thread 13564:
                                                #0  0x000069bfeff6d05c _ZN7QStringaSERKS_ (libQt5Core.so.5)
                                                #1  0x000069bff0a567bb _ZN13DSqliteHandle19getMountPointOfFileE4DUrlRSt10unique_ptrISt3mapI7QStringSt8>
                                                #2  0x000069bff0a5d0fc _ZN13DSqliteHandle10execSqlstrILNS_7SqlTypeE19E5QListI7QStringEEET0_RK4QMapIS3_>
                                                #3  0x000069bff0a64c5d _ZN13DSqliteHandle10execSqlstrILNS_7SqlTypeE20E5QListI7QStringEEET0_RK4QMapIS3_>
                                                #4  0x000069bff0a6766d _ZN13DSqliteHandle17disposeClientDataERK4QMapI7QString5QListIS1_EERKy (libdde-f>
                                                #5  0x00000b272b021cd3 n/a (dde-file-manager-daemon)
                                                #6  0x00000b272b034417 n/a (dde-file-manager-daemon)
                                                #7  0x000069bff00b77cd _ZNK11QMetaMethod6invokeEP7QObjectN2Qt14ConnectionTypeE22QGenericReturnArgument>
                                                #8  0x000069bff00b9089 _ZN11QMetaObject12invokeMethodEP7QObjectPKcN2Qt14ConnectionTypeE22QGenericRetur>
                                                #9  0x00000b272b02719d n/a (dde-file-manager-daemon)
                                                #10 0x00000b272b034baa n/a (dde-file-manager-daemon)
                                                #11 0x00000b272b034e43 n/a (dde-file-manager-daemon)
                                                #12 0x000069bff03599ef n/a (libQt5DBus.so.5)
                                                #13 0x000069bff035e16c n/a (libQt5DBus.so.5)
                                                #14 0x000069bff035e9e1 n/a (libQt5DBus.so.5)
                                                #15 0x000069bff036114e n/a (libQt5DBus.so.5)
                                                #16 0x000069bff00d3352 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
                                                #17 0x000069bff00a8c17 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                #18 0x000069bff00abccc _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5>
                                                #19 0x000069bff00fc9d4 n/a (libQt5Core.so.5)
                                                #20 0x000069bfeef1b3cf g_main_context_dispatch (libglib-2.0.so.0)
                                                #21 0x000069bfeef1cf89 n/a (libglib-2.0.so.0)
                                                #22 0x000069bfeef1cfce g_main_context_iteration (libglib-2.0.so.0)
                                                #23 0x000069bff00fbfc9 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFl>
                                                #24 0x000069bff00a78cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                #25 0x000069bff00afbc6 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                                #26 0x00000b272b003a9d main (dde-file-manager-daemon)
                                                #27 0x000069bfefaec223 __libc_start_main (libc.so.6)
                                                #28 0x00000b272b0040ee n/a (dde-file-manager-daemon)

                                                Stack trace of thread 13567:
                                                #0  0x000069bfefbb8bb1 __poll (libc.so.6)
                                                #1  0x000069bfeef1cee0 n/a (libglib-2.0.so.0)
                                                #2  0x000069bfeef1cfce g_main_context_iteration (libglib-2.0.so.0)
                                                #3  0x000069bfeef1d022 n/a (libglib-2.0.so.0)
                                                #4  0x000069bfeeee63eb n/a (libglib-2.0.so.0)
                                                #5  0x000069bfeddd6a9d start_thread (libpthread.so.0)
                                                #6  0x000069bfefbc3a43 __clone (libc.so.6)

                                                Stack trace of thread 13566:
                                                #0  0x000069bfefbb8bb1 __poll (libc.so.6)
                                                #1  0x000069bfeef1cee0 n/a (libglib-2.0.so.0)
                                                #2  0x000069bfeef1cfce g_main_context_iteration (libglib-2.0.so.0)
                                                #3  0x000069bff00fbfc9 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFl>
                                                #4  0x000069bff00a78cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                #5  0x000069bfefef0eb9 _ZN7QThread4execEv (libQt5Core.so.5)
                                                #6  0x000069bff034dba6 n/a (libQt5DBus.so.5)
                                                #7  0x000069bfefefaf65 n/a (libQt5Core.so.5)
                                                #8  0x000069bfeddd6a9d start_thread (libpthread.so.0)
                                                #9  0x000069bfefbc3a43 __clone (libc.so.6)
-- Subject: Process 13564 (dde-file-manage) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
--
-- Process 13564 (dde-file-manage) crashed and dumped core.
--
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
```

### Distro & Version

Arch Linux with the latest deepin packages

### Related package version

`deepin-file-manager 1:4.6.8.6-1`

Please ask me if I can provide any other logs for help.

**Comment by felixonmars** [comment] 2018-11-04 02:53
Is this crash still present in the latest 4.6.10 release?

**Comment by felixonmars** [comment] 2018-11-04 05:40
I still cannot reproduce it. Maybe the developers would have an idea...

**Comment by HuxyUK** [comment] 2018-11-05 16:55
I've seen the same behaviour with DDE. For me the issue was the underlying file-system I was using. When using BTRFS, the file daemon crashes and seg faults constantly. In addition, the file manager is sluggish and hangs. I was able to replicate it across Manjaro, Arch and Antergos. Reformatting to ext4 solved the problem.

## To Reproduce

1. Use BTRFS as file system
2. Open file manager and attempt to create a new folder. 
3. Don't accept the default name "new folder". Enter a new one. 
4. If it doesn't freeze for a short time, just keep repeating until it does.

This issue has been present ever since I first tried Deepin over the Summer.

**Comment by fosshelper** [comment] 2018-11-06 04:44
I use `ext4` for all my partitions, so I don't think it might be related to that.

**Comment by HuxyUK** [comment] 2018-11-06 10:37
Interesting. I'll have to double check, maybe with some Virtual Machines, but the behavior I experience is similar to yours, even if we're not running the same filesystem. If it helps, I started using Nautilus as it works fine, but the problem is Deepin File Manager is still preferred by the environment.

**Comment by fosshelper** [comment] 2018-11-07 15:19
Same here, Nautilus works fine, but deepin file manager doesn't.

**Comment by BLumia** [comment] 2018-11-07 23:44
Seems related: https://github.com/linuxdeepin/dde-file-manager/issues/43

**Comment by HuxyUK** [comment] 2018-11-08 14:59
I can confirm this problem still occurs irrespective of whether I use Root-Filemanager or Deepin File Manager. I can replicate this error with ease. For completeness sake, I've added a coredump. You can see the stack traces are very similar to fosshelper's. 

As fosshelper mentioned, my initial prognosis of file-system issues seems to be incorrect. It also crashes when accessing my NTFS drive. I have a suspicion that the crashes, don't start immediately, which is why I thought ext4 fixed it. 

I *believe* both fosshelper and I have the same issue.

## Journal Logs

```
Nov 08 14:51:11 charizard systemd-coredump[2274]: Process 2266 (dde-file-manage) of user 0 dumped core.
                                                  
                                                  Stack trace of thread 2266:
                                                  #0  0x00007f21d6e3a05c _ZN7QStringaSERKS_ (libQt5Core.so.5)
                                                  #1  0x00007f21d794415b _ZN13DSqliteHandle19getMountPointOfFileE4DUrlRSt10unique_ptrISt3mapI7QStringSt8multimapIS3_S3_St4lessIS3_ESaISt4pairIKS3_S3_EEES6_SaIS7_IS8_SB_EEESt14default_deleteISE_EE (libdde-file-manager.so.1)
                                                  #2  0x00007f21d794aa9c _ZN13DSqliteHandle10execSqlstrILNS_7SqlTypeE19E5QListI7QStringEEET0_RK4QMapIS3_S4_E (libdde-file-manager.so.1)
                                                  #3  0x00007f21d79525fd _ZN13DSqliteHandle10execSqlstrILNS_7SqlTypeE20E5QListI7QStringEEET0_RK4QMapIS3_S4_E (libdde-file-manager.so.1)
                                                  #4  0x00007f21d795500d _ZN13DSqliteHandle17disposeClientDataERK4QMapI7QString5QListIS1_EERKy (libdde-file-manager.so.1)
                                                  #5  0x0000555fc4f04cd3 n/a (dde-file-manager-daemon)
                                                  #6  0x0000555fc4f17417 n/a (dde-file-manager-daemon)
                                                  #7  0x00007f21d6f847cd _ZNK11QMetaMethod6invokeEP7QObjectN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS5_S5_S5_S5_S5_S5_S5_S5_S5_ (libQt5Core.so.5)
                                                  #8  0x00007f21d6f86089 _ZN11QMetaObject12invokeMethodEP7QObjectPKcN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS7_S7_S7_S7_S7_S7_S7_S7_S7_ (libQt5Core.so.5)
                                                  #9  0x0000555fc4f0a19d n/a (dde-file-manager-daemon)
                                                  #10 0x0000555fc4f17baa n/a (dde-file-manager-daemon)
                                                  #11 0x0000555fc4f17e43 n/a (dde-file-manager-daemon)
                                                  #12 0x00007f21d72269ef n/a (libQt5DBus.so.5)
                                                  #13 0x00007f21d722b16c n/a (libQt5DBus.so.5)
                                                  #14 0x00007f21d722b9e1 n/a (libQt5DBus.so.5)
                                                  #15 0x00007f21d722e14e n/a (libQt5DBus.so.5)
                                                  #16 0x00007f21d6fa0352 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5)
                                                  #17 0x00007f21d6f75c17 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                                                  #18 0x00007f21d6f78ccc _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5)
                                                  #19 0x00007f21d6fc99d4 n/a (libQt5Core.so.5)
                                                  #20 0x00007f21d5de83cf g_main_context_dispatch (libglib-2.0.so.0)
                                                  #21 0x00007f21d5de9f89 n/a (libglib-2.0.so.0)
                                                  #22 0x00007f21d5de9fce g_main_context_iteration (libglib-2.0.so.0)
                                                  #23 0x00007f21d6fc8fc9 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #24 0x00007f21d6f748cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #25 0x00007f21d6f7cbc6 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                                                  #26 0x0000555fc4ee6a9d main (dde-file-manager-daemon)
                                                  #27 0x00007f21d69b9223 __libc_start_main (libc.so.6)
                                                  #28 0x0000555fc4ee70ee n/a (dde-file-manager-daemon)
                                                  
                                                  Stack trace of thread 2272:
                                                  #0  0x00007f21d6a85c21 __poll (libc.so.6)
                                                  #1  0x00007f21d5de9ee0 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f21d5de9fce g_main_context_iteration (libglib-2.0.so.0)
                                                  #3  0x00007f21d5dea022 n/a (libglib-2.0.so.0)
                                                  #4  0x00007f21d5db33eb n/a (libglib-2.0.so.0)
                                                  #5  0x00007f21d4ca3a9d start_thread (libpthread.so.0)
                                                  #6  0x00007f21d6a90b23 __clone (libc.so.6)
                                                  
                                                  Stack trace of thread 2267:
                                                  #0  0x00007f21d6a85c21 __poll (libc.so.6)
                                                  #1  0x00007f21d5de9ee0 n/a (libglib-2.0.so.0)
                                                  #2  0x00007f21d5de9fce g_main_context_iteration (libglib-2.0.so.0)
                                                  #3  0x00007f21d6fc8fc9 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #4  0x00007f21d6f748cc _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                                                  #5  0x00007f21d6dbdeb9 _ZN7QThread4execEv (libQt5Core.so.5)
                                                  #6  0x00007f21d721aba6 n/a (libQt5DBus.so.5)
                                                  #7  0x00007f21d6dc7f65 n/a (libQt5Core.so.5)
                                                  #8  0x00007f21d4ca3a9d start_thread (libpthread.so.0)
                                                  #9  0x00007f21d6a90b23 __clone (libc.so.6)
-- Subject: Process 2266 (dde-file-manage) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 2266 (dde-file-manage) crashed and dumped core.
-- 
```

**Comment by hualet** [comment] 2018-11-13 11:16
@felixonmars maybe a package with debug information can help?

**Comment by fosshelper** [comment] 2018-11-14 07:37
@BLumia I don't think a VM is going to help, as many people here aren't able to reproduce the crash. It would also take a lot of effort to produce a VM image similar to my working installation. It's a bit strange since I encounter the crashes routinely. Just today, after I had the file manager opened, I launched another file manager window (using [albert](https://github.com/albertlauncher/albert) fwiw), and then it just got stuck. The new window opened after 5 - 10 sec, and only then the previous window responded.

@hualet If there is a special debug package, I'm happy to try it on, if its available on the official repos or on AUR. If there are special flags required during launching file manager, let me know.

**Comment by BLumia** [comment] 2018-11-14 08:13
> as many people here aren't able to reproduce the crash.

So do I, and that's why I'm asking for a VM or something similar. Use [Mozilla/rr](https://github.com/mozilla/rr) to record the state is also okay if possible.

**Comment by fosshelper** [comment] 2018-11-16 18:16
> Use Mozilla/rr...

That is really nifty, I'll submit logs as soon as I encounter bugs again.

**Comment by fosshelper** [comment] 2018-11-23 13:50
On using `rr record`, I got the attached logs. I hope they don't contain any personal info, but if you find any, let me know. The file manager stuck multiple times, when I was trying to get a right click.
[logs.txt](https://github.com/linuxdeepin/developer-center/files/2610905/logs.txt)

**Comment by wangzk** [comment] 2018-11-29 10:10
This bug is pretty strange. I install Manjaro Deepin on both my desktop and laptop. Only the desktop meets the bug while the laptop works fine.

**Comment by taolin96** [comment] 2018-12-07 08:15
> This bug is pretty strange. I install Manjaro Deepin on both my desktop and laptop. Only the desktop meets the bug while the laptop works fine.

yes same for me, I have Arch Linux on my laptop and desktop PC, only see coredump on my PC,

**Comment by BLumia** [comment] 2018-12-24 03:12
@wangzk Is this issue the same as https://github.com/linuxdeepin/dde-file-manager/issues/43 ?

**Comment by wangzk** [comment] 2018-12-24 03:17
> @wangzk Is this issue the same as [linuxdeepin/dde-file-manager#43](https://github.com/linuxdeepin/dde-file-manager/issues/43) ?

From the journal logs, I think they are the same issue. The crashes in this issue also happens in `DSqliteHandle::getMountPointOfFile`.

**Comment by BLumia** [comment] 2019-01-09 07:05
Closing since it's already fixed in https://github.com/linuxdeepin/dde-file-manager/commit/58e4c2da555887b0dd284431cc3e7397e46fede0 ;)

**Closed by BLumia** 2019-01-09 07:05 UTC

**Comment by fosshelper** [comment] 2019-01-12 01:46
Works beautifully now, thanks.
