### ISSUE TITLE
Bug : File Manager automount inconsistency !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#792] opened 2019-01-08 16:54 UTC
Hi,

off late since last week i am seeing an inconsistency in the automount feature of the file manager ... turns out after i have booted into the OS the partitions are not mounted they suddenly start mounting when i open the file manager ... as a result of this inconsistency in mounting my flatpak apps on a separate partition do not launch.

please let me know if you want to view any logs from my affected system.

thanks.

**Comment by BLumia** [comment] 2019-01-09 01:12
> after i have booted into the OS the partitions are not mounted

Did you got the `dde-disk-mount-plugin` installed?

**Comment by aiamuzz** [comment] 2019-01-09 04:36
> > after i have booted into the OS the partitions are not mounted
> 
> Did you got the `dde-disk-mount-plugin` installed?

`dde-disk-mount-plugin is already the newest version (4.7.1.10-1).` its already present ...

**Comment by BLumia** [comment] 2019-01-09 05:08
If you are sure the automount (after you first-time login) is enabled from the file manager and it's not working, could you provide more info about your partitions (e.g. `gio mount -li`, `udisksctl dump`, etc.) and other details may related with this issue like the `dde-dock` log?

**Comment by BLumia** [comment] 2019-01-09 06:03
It seems all partitions are mounted according to `can_unmount=1` from your `gio_mount.log`.

FYI `dde-dock` log located at `/home/wzc/.cache/deepin/dde-dock/`, you can also find log of other program at `/home/wzc/.cache/deepin/`.

Please try reboot and enter these command like `gio mount -li` **before** you launch the `dde-file-manager` so we can see the state of your partitions.

**Comment by BLumia** [comment] 2019-01-09 06:31
Manually unmount all disks via right click the dde-disk-mount-plugin and choose "Unmount all", and then do a `killall dde-dock` is also okay. 

The daemon will restart the dde-dock process. Once the `dde-disk-mount-plugin` got loaded, if you enabled the auto-mount feature, the mount plugin will try to mount all partitions (expect the partitions which should be ignored with the "HintIgnore" property) at that time.

**Comment by aiamuzz** [comment] 2019-01-09 06:40
> Manually unmount all disks via right click the dde-disk-mount-plugin and choose "Unmount all", and then do a `killall dde-dock` is also okay.

hahaha ... dde-disk-mount-plugin is missing from the dock ... hence this issue reported to seek clarification ... https://github.com/linuxdeepin/developer-center/issues/793 ... hey wait ... could that be the problem ... the missing disks plugin in the dock is what is causing the auto mount to fail after boot ?

**Comment by aiamuzz** [comment] 2019-01-09 06:42
sometime back i faced this issue ... https://github.com/linuxdeepin/developer-center/issues/766 ... and @listenerri 's help restored it ... using https://github.com/linuxdeepin/developer-center/issues/766#issuecomment-450809570

will removing the dock config file help in restoring the disks plugin too

**Comment by BLumia** [comment] 2019-01-09 06:54
> the missing disks plugin in the dock is what is causing the auto mount to fail after boot ?

Yep, if the mount plugin failed to load, then there is nobody going to mount your partitions.

So it seems duplicated with #793, closing. Feel free to reopen it if it's not related to that issue ;)

**Closed by BLumia** 2019-01-09 06:54 UTC

**Comment by aiamuzz** [comment] 2019-01-09 08:12
> > the missing disks plugin in the dock is what is causing the auto mount to fail after boot ?
> 
> Yep, if the mount plugin failed to load (or just not loaded), then there is nobody going to mount your partitions.
> 
> So it seems duplicated with #793, closing. Feel free to reopen it if it's not related to that issue ;)

oh ... @BLumia ... you closed both the issues without providing the solution / fix ... 

:fearful: :sweat: :cry: :weary: :confounded:

**Comment by aiamuzz** [comment] 2019-01-09 08:16
If this was supposed to be the solution ... `rm -rf ~/.config/deepin/dde-dock.conf` ... i tried that command and restarted the dock ... but the disk plugin is not back !

**Comment by BLumia** [comment] 2019-01-09 09:17
> you closed both the issues without providing the solution / fix ...

Shouldn't the solution posted to #793 ?

> i tried that command and restarted the dock ... but the disk plugin is not back !

You should post these info to #793 instead of this one, since it's more about a dde-dock issue, and this issue title lead to the file manager which may confuse people.

**Comment by aiamuzz** [comment] 2019-01-09 09:51
ok ... posted here ... https://github.com/linuxdeepin/developer-center/issues/766

**Comment by BLumia** [comment] 2019-01-10 10:00
> If this was supposed to be the solution ... `rm -rf ~/.config/deepin/dde-dock.conf` ... i tried that command and restarted the dock ... but the disk plugin is not back !

So #766 is not related with your issue, so that's not the issue which should be reopened. Your issue caused by the mount plugin not loaded, which is exactly #793 , so we should continue our discussion at #793, not #766.
