### ISSUE TITLE
[archlinux] LightDM + Deepin Session.

### ISSUE THREAD

**Issue by demencia89** [linuxdeepin/developer-center#108] opened 2016-07-27 14:48 UTC
Whenever I log on to Deepin Session using LightDM it loads and then after any interaction with the Deepin Dock or Deepin Control the session starts freezing. So Deepin is unusable if I use LightDM, it works perfectly with GDM though. Is there a way to make it work using LightDM?

**Comment by hualet** [comment] 2016-07-28 00:47
DDE should work better with LightDM instead of GDM. I think this issue has something to do with the runtime dependencies, it needs more investigation though :)
Please upload the log files so I can debug more,  ~/.cache/deepin/dde-dock/dde-dock.log ~/.cache/deepin/dde-control-center/dde-control-center.log

**Comment by hualet** [comment] 2016-07-28 01:01
DDE should work better with LightDM instead of GDM. I think this issue has something to do with the runtime dependencies, it needs more investigation though :)
Please upload the log files so I can debug more,  ~/.cache/deepin/dde-dock/dde-dock.log ~/.cache/deepin/dde-control-center/dde-control-center.log

**Comment by fasheng** [comment] 2016-07-28 04:14
@demencia89 I notice you commented in the high CPU topic just now, I guess you could not see the Desktop, Dock and other DDE components is just because the startdde didn't initialize them correctly for some reason. Beside the log files, please upload the process information in another tty(press Ctrl-Alt-F2 to swtich to tty2):
```
ps aux | grep 'dde\|deepin'
```

**Comment by demencia89** [comment] 2016-07-28 15:17
Yeah I commented there too but he says it's after a while that he has those issues. The problem for me is as soon as I log in using LightDM. Is it working for someone on arch and LightDM? I'll upload the info you asked as soon as I get home. Thank you.

**Comment by demencia89** [comment] 2016-07-30 03:44
Allright. So, here's what I see in a tty if I log in with my user, the one logged on deepin via light dm.
![img_20160730_242033243_hdr](https://cloud.githubusercontent.com/assets/20685036/17267929/4fa73884-5618-11e6-9391-d67b6b8aa2fd.jpg)

Then this is the output of ps aux | grep 'dde\|deepin'

![img_20160730_243351530_hdr](https://cloud.githubusercontent.com/assets/20685036/17267937/66b0b10e-5618-11e6-80a4-75b4d90ce044.jpg)

And here are the log files you requested.

[logs.zip](https://github.com/linuxdeepin/developer-center/files/391699/logs.zip)

By the way it's worst now. It wont even load the panel. Hot corners are working tho.. Except for control center.

**Comment by demencia89** [comment] 2016-07-31 16:51
help?

**Comment by fasheng** [comment] 2016-08-01 01:59
I saw lots of xcb warnings in the dock/control-center logs, looks startdde didn't own the right X environment for some case, so dock/control-center/daemon could not initialize correctly.
```
[Warning] [0] QXcbConnection: XCB error: 8 (BadMatch), sequence: 1896, resource id: 125829145, major code: 130 (Unknown), minor code: 3
```
And the enable module faild errors in first picture should be caused by the previous unfinished dde-session-daemon process. This is not always occurred.

But the problem is it's fine here both through lightdm-gtk-greeter and lightdm-deepin-greeter. I have to try to reproduce it in some way.

**Comment by jouyouyun** [comment] 2016-08-01 02:45
@demencia89  Can you paste the file '~/.xsession-errors'?

**Comment by fasheng** [comment] 2016-08-01 03:43
@demencia89 You could download the official toolkit to collect more information
including all mentioned in this topic after login failed
again. Just run the following commands and upload the generated log
file in current directory:

    wget https://raw.githubusercontent.com/linuxdeepin/deepin-feedback/master/cli/deepin-feedback-cli.sh
    chmod +x deepin-feedback-cli.sh
    sudo -E deepin-feedback-cli.sh

**Comment by demencia89** [comment] 2016-08-01 04:17
@jouyouyun @fasheng 
On the zip you can find both of the files you request.
[logs.zip](https://github.com/linuxdeepin/developer-center/files/392932/logs.zip)

**Comment by fasheng** [comment] 2016-08-01 06:48
Really strange, there is even no startdde or dde-daemon syslogs which shoul be followed after lightdm-deepin-greeter...

**Comment by demencia89** [comment] 2016-08-01 14:44
Do you think there might be a difference between the way GDM and LightDM start the Deepin Session? It's all I can think about since Deepin Session works perfectly if I use GDM to log on.
Is there a way I can check how each DM start the session?

**Comment by fasheng** [comment] 2016-08-02 03:20
I found a warning message in your lightdm.log, looks you open multiple seats at the same time and /dev/tty0 already in use?
```[+29574.66s] WARNING: Error using VT_WAITACTIVE 7 on /dev/tty0: Interrupted system call```

And there is no startdde logs in your syslog, but I'm not sure is it launch failed or just blocked, did it play the login system sound at the time?

Besides, you could create a new temporary user through deepin control center and have a try again. And you could take a difference about the environment variables between lightdm and gdm.

**Comment by demencia89** [comment] 2016-08-02 04:08
@fasheng okay, I'm gonna try with a user created in deein control center now. Where should I look for differnces about the env variables between lightdm and gdm?
and what do you mean when you say this?

> I found a warning message in your lightdm.log, looks you open multiple seats at the same time and /dev/tty0 already in use?

Also, I think it might be important to know that I used AntergOS to install archlinux on this PC.

**Comment by demencia89** [comment] 2016-08-02 04:21
I logged on via gdm, but I can't add user from deepin control panel. Here are the screenshots.

![screenshot from 2016-08-02 01-16-24](https://cloud.githubusercontent.com/assets/20685036/17316993/47c4b3cc-5879-11e6-80fe-31f4d0f60225.png)
![screenshot from 2016-08-02 01-16-48](https://cloud.githubusercontent.com/assets/20685036/17316994/47cb1eec-5879-11e6-9f3c-0ee4dfb6f8f8.png)


Also, about this:

> I found a warning message in your lightdm.log, looks you open multiple seats at the same time and /dev/tty0 already in use?

When I'm using GDM, If I press ctrl+alt+f1 I see GDM screen. If I press ctrl+alt+f7 I see deepin desktop.
This doesn't happen when using LightDM. Everything is on ctrl+alt+f7 when using LightDM.

**Comment by fasheng** [comment] 2016-08-02 04:28
You should append your user to sudo/wheel group or there is no permission to create another user..
For the environment variables, Just run `env` command in the terminal after login DDE through lightdm and gdm like this:
```
env | sort > envs_lightdm
env | sort > envs_gdm
diff envs_lightdm envs_gdm
```
For the seat warning, did you stopped gdm.service before starting lightdm.server? And could you hear the theme sound after login through lightdm just like gdm did?
OK, I will try to reproduce it under AntergOS later.

**Comment by demencia89** [comment] 2016-08-02 04:40
Env:

> diff envs_lightdm envs_gdm
10c10
< DISPLAY=:0
---
> DISPLAY=:1
14a15,16
> GIO_LAUNCHED_DESKTOP_FILE=/etc/xdg/autostart/gnome-settings-daemon.desktop
> GIO_LAUNCHED_DESKTOP_FILE_PID=938
31c33
< SHLVL=5
---
> SHLVL=9
39c41
< XAUTHORITY=/home/demencia/.Xauthority
---
> XAUTHORITY=/run/user/1000/gdm/Xauthority

**Comment by demencia89** [comment] 2016-08-02 04:40
`diff envs_lightdm envs_gdm
10c10
< DISPLAY=:0
---
> DISPLAY=:1
14a15,16
> GIO_LAUNCHED_DESKTOP_FILE=/etc/xdg/autostart/gnome-settings-daemon.desktop
> GIO_LAUNCHED_DESKTOP_FILE_PID=938
31c33
< SHLVL=5
---
> SHLVL=9
39c41
< XAUTHORITY=/home/demencia/.Xauthority
---
> XAUTHORITY=/run/user/1000/gdm/Xauthority
`

**Comment by demencia89** [comment] 2016-08-02 04:41
Envs:

`diff envs_lightdm envs_gdm
10c10
< DISPLAY=:0
---
> DISPLAY=:1
14a15,16
> GIO_LAUNCHED_DESKTOP_FILE=/etc/xdg/autostart/gnome-settings-daemon.desktop
> GIO_LAUNCHED_DESKTOP_FILE_PID=938
31c33
< SHLVL=5
---
> SHLVL=9
39c41
< XAUTHORITY=/home/demencia/.Xauthority
---
> XAUTHORITY=/run/user/1000/gdm/Xauthority
`

**Comment by demencia89** [comment] 2016-08-02 04:43
[envs.zip](https://github.com/linuxdeepin/developer-center/files/395246/envs.zip)

**Comment by fasheng** [comment] 2016-08-02 04:46
Thanks, got it.

**Comment by demencia89** [comment] 2016-08-02 04:51
Also, I believe I'm already in the wheel group.

grep wheel /etc/group
wheel:x:10:root,demencia

**Comment by fasheng** [comment] 2016-08-02 10:20
>And the backlight is kind of like a strobe.

It should be caused by the daemon crash&restart repeatly issue.
https://github.com/linuxdeepin/dde-daemon/issues/26

**Comment by demencia89** [comment] 2016-08-02 15:16
Let me know if you need any other information that I can provide.

**Comment by fasheng** [comment] 2016-08-03 04:53
I installed a fresh AntergOS(Base)+DDE with the following command today:
```sudo pacman -Sy deepin deepin-extra gdm lightdm-gtk-greeter```
But I could not reproduce this issue, too. Everything is just fine for both gdm and lightdm~ So we will continue the debug work until some new clues were found.

For the user creating issue, just uncomment this line in `/etc/sudoer` and there will be a "+" button in the account UI, you could have a try again:
```%wheel ALL=(ALL) ALL```

**Comment by suratovvlad** [comment] 2017-02-02 02:23
I had a similar problem, but I've found a solution: I've deleted light-locker, xscreensaver, cinnamon-screensaver and gnome-screensaver (I'd tested some of them a long time ago).
So, deepin stops freezing and start working fine with lightdm

**Comment by demencia89** [comment] 2017-02-07 21:04
Amazing, thank you so much, this was the only thing that worked.

2017-02-01 23:23 GMT-03:00 suratovvlad <notifications@github.com>:

**Comment by hualet** [comment] 2017-02-08 01:53
@demencia89 Maybe you can tell which screensaver/locker application you deleted specifically, so we can narrow it down?

**Comment by dongfengweixiao** [comment] 2017-02-09 03:19
i have same problem but now it works well(i donot do anything).when this problem occur try switch to a tty by Ctrl + Alt + num and then login,execute "systemctl restart lightdm.service".

**Comment by jouyouyun** [comment] 2017-11-06 07:15
Update system to the last version, test it!

**Comment by Dinolek** [comment] 2019-02-09 11:54
I have similar issue with deepin started by lightdm on arch.
Deepin started by lightdm doesn't open app launcher, power menu or control center, but if I start dde-launcher, dde-control-center or dde-shutdown from terminal buttons start working.
There is no such problem with gdm.
Tried creating new user for new settings, didn't help.
Reinstalling deepin and lightdm didn't help as well.

**Comment by jouyouyun** [comment] 2019-02-13 01:14
@Dinolek Please run the command `sudo journalctrl -b 0 > /tmp/sys.log` after login to deepin, then upload the file `/tmp/sys.log`, thanks!

**Comment by Dinolek** [comment] 2019-02-13 08:53
It just started working now, ehh...
Thanks anyway

**Comment by hualet** [comment] 2019-02-15 10:15
This issue is too old, closing.
Feel free to reopen it or create new issues if anyone gets this issue again.

**Closed by hualet** 2019-02-15 10:15 UTC
