### ISSUE TITLE
Authentication locked if command contains empty line breaks

### ISSUE THREAD

**Issue by Azn9** [linuxdeepin/developer-center#3013] opened 2022-04-04 18:02 UTC
### SUMMARY

Pasting any sudo command (or any ones that require authentification) with empty line breaks at the end will validate the password prompt and lock all authentication.

### STEPS TO REPRODUCE

Paste the following in a console (with the line breaks) :
``` 
sudo whoami




```

### OBSERVED RESULT

The password prompts are "pre-filled" with the line breaks are automatically submitted, locking the auth for some time.

### EXPECTED RESULT

It shouldn't.

### SOFTWARE/OS VERSIONS

Deepin 20.5 default terminal

### ADDITIONAL INFORMATION

I'm currently logged in but I know that if log out in the next 75 (!!) minutes, I won't be able to log back in...

**Comment by SuperEffie** [comment] 2022-04-06 09:03
Could you describe the expected results in more detail? If you have entered the password in the terminal before executing the sudo command , you will not need to enter the password again for a period of time.

**Comment by Azn9** [comment] 2022-04-06 12:10
> Could you describe the expected results in more detail? If you have entered the password in the terminal before executing the sudo command, you will not need to enter the password again for a period of time.

I copy/pasted a command starting with sudo and ending with empty line breaks. Instead of letting me enter my password, the three prompts were completed as if I just pressed enter for each, causing my account to get locked due to the three errors.
What is respected is that a line break doesn't submit the password prompt.

**Comment by SuperEffie** [comment] 2022-04-07 08:16
![截图_deepin-terminal_20220407160133](https://user-images.githubusercontent.com/58986464/162150651-6aed7416-5446-43f2-8462-e7254f9bf446.png)
Just like the above screenshot,I have tried to copy and past the command in the terminal, but I cannot reproduce what you said. 
Don't you think it is reasonable to handle line breaks in the terminal?
If you can reproduce the problem, please give me a screenshot.

**Comment by SuperEffie** [comment] 2022-04-29 03:17
Due to no reply for a long time and lack of necessary information,close this issue at first.If the issue still exists,you can apply to reopen it and please give us more information.You are welcomed to give more feedback.

**Closed by SuperEffie** 2022-04-29 03:17 UTC
Labels: project: deepin-terminal
