### ISSUE TITLE
[Feature request] Events

### ISSUE THREAD

**Issue by Pauligrinder** [linuxdeepin/developer-center#1060] opened 2019-03-13 10:56 UTC
deepin-calendar looks pretty nice, but it's quite useless since it doesn't support events at all. So it would be very nice if such functions could be implemented. 
Also support for cloud calendars (Google etc) would be very nice, but events need to be implemented first so those can use that functionality.

**Comment by BLumia** [comment] 2019-04-10 01:09
Close since duplicate of #1043

**Closed by BLumia** 2019-04-10 01:09 UTC
