### ISSUE TITLE
Slow file manager and menu to reboot or turn off pc.

### ISSUE THREAD

**Issue by AmigaBlitter** [linuxdeepin/developer-center#1992] opened 2020-11-29 19:01 UTC
When i call the file manager and when i call the shutdown or reboot option, it' takes many seconds to both to appear on screen.
Deepin 20 and Ubuntu 20.10

**Comment by babyfengfjx** [comment] 2022-02-15 06:22
Hi, this question still exists in the latest version  Deepin V20.4, I don't know if your problem has been solved?

**Comment by BLumia** [comment] 2022-07-12 02:13
I cannot reproduce this on the most recent version of deepin (currently `deepin v20.6`). Since there is no further response, I'll close this issue for now. If you still have this issue on the most recent release you can get, please feel free to create a new issue and we will look into it. Thanks!

**Closed by BLumia** 2022-07-12 02:13 UTC
Labels: bug | functional behavior
