### ISSUE TITLE
Wallpapers and slow applications

### ISSUE THREAD

**Issue by Xeers** [linuxdeepin/developer-center#497] opened 2018-03-25 00:09 UTC
[Arch Linux] After the last updates it is impossible to put a wallpaper and the applications take a long time to be minimized or closed.
Applications only take up half of the screen and are not maximized. The minimize, zoom in and out buttons have disappeared in many applications.
Show desktop does not work, Firefox does not open menus,...

Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"

deepin-system-m[12723]: segfault at 55bb1782a340 ip 000055bb1782a340 sp 00007ffed7ec77a8 error 15
deepin-menu[12016]: segfault at 38 ip 00007fdfc4c18581 sp 00007ffc57178230 error 4 in libQt5Core.so.5.10.1[7fdfc4978000+4f7000]
deepin-system-m[13712]: segfault at 558d85107e80 ip 0000558d85107e80 sp 00007ffdb172e848 error 15

https://i.imgur.com/EiJmS4y.png

**Comment by Xeers** [comment] 2018-03-25 12:51
The problem of the windows is solved if in Control Center> Customization> we deactivate Effects of activated windows.

**Comment by konig1** [comment] 2018-03-25 13:40
This is probably caused by the switch to the latests gnome shell. Opera's control buttons are gone, something that is only attributable to gnome DE.

**Comment by dogukanoksuz** [comment] 2018-03-25 18:12
[deepin.txt](https://github.com/linuxdeepin/developer-center/files/1845618/deepin.txt)
There is a bug after new archlinux update. I solved it by closing window effects but they're all gone and system looks just weird :(

**Comment by konig1** [comment] 2018-03-26 15:01
looks like no one gives a rats ass about this issue - a broken DE is a feature now.

**Comment by felixonmars** [comment] 2018-03-26 16:50
I still could not reproduce any of these. @hualet thoughts?

**Comment by Xeers** [comment] 2018-03-26 19:58
Dock Launcher does not work if Effects of activated windows is enabled

**Comment by hualet** [comment] 2018-03-27 01:05
@sbwtw

**Comment by dogukanoksuz** [comment] 2018-03-27 09:25
it fixed by running pacman -Syyu but don't know what fixed it exactly. maybe, i installed gnome-desktop package and this installed the lib that can't be reached by deepin-wm and metacity. strange issue don't understand why is that happened.

**Comment by konig1** [comment] 2018-03-27 11:39
Here's a walk around which fixes the issue -
First downgrade deepin-vm to version "deepin-wm-1.9.23-1-x86_64.pkg.tar.xz"
next downgrade deepin-mutter to deepin-mutter-3.20.28-2-x86_64.pkg.tar.xz
reboot
Once rebooted do a full system upgrade et voila.

**Closed** 2018-07-21 09:55 UTC
