### ISSUE TITLE
Cannot switch layout by clicking layout icon using mouse button

### ISSUE THREAD

**Issue by tribunal2000** [linuxdeepin/developer-center#671] opened 2018-11-17 09:02 UTC
## Describe the bug

Cannot switch layout by clicking layout icon using mouse button

## To Reproduce

1. Start session
2. Use shortcut to see layout switching icon
3. Click it by mouse buttons
4. No reaction

## Expected behavior

Layouts must be switched by mouse button as it is done by using shortcut

deepin 15.8

**Comment by listenerri** [comment] 2018-11-20 01:38
That is not a bug.
The keyboard layout indicator does not support mouse events, do we need support it? @hualet

**Comment by hualet** [comment] 2018-11-20 05:51
> That is not a bug.
> The keyboard layout indicator does not support mouse events, do we need support it? @hualet

It did support that long time ago until @justforlxz rewrote it.

**Comment by tribunal2000** [comment] 2018-11-20 07:00
I think, it should support mouse events, as it supports it in Plasma/Win7/Cinnamon etc, with 
LMB: simple switching 
RMB: small context menu with list of layouts and "settings" option.

**Comment by listenerri** [comment] 2018-11-20 07:07
@tribunal2000 
Ok, it will be fixed later

**Comment by listenerri** [comment] 2019-03-06 09:19
https://cr.deepin.io/c/dde/dde-dock/+/41872

**Comment by liuwen123** [comment] 2019-03-07 02:10
+1

**Comment by tribunal2000** [comment] 2019-03-08 08:10
May be you should use button value like this?

(code, using my style (it looks lix mix of google and Qt style))

void DBusAdaptors::onClicked(int button, int x, int y) {

  int oldtLayout = m_currentLayout;
  if (m_userLayoutList.size() < 2) 
      return;
   switch (button)
   {
     case LEFT_BUTTON:
     case SCROLL_DOWN:
          m_currentLayout++;
       if (m_currentLayout == m_userLayoutList.size())
          m_currentLayout = 0;
       layoutChanged = true;
       break;
     case SCROLL_UP:
       m_currentLayout--;
       if (m_currentLayout < 0)
       m_currentLayout = m_userLayout.size() - 1;
       break;
      case RIGHT_BUTTON:
      case MIDDLE_BUTTON:
       QTimer::singleShot(1000, this, &DBusAdaptors::onLayoutChanged);
       if (m_menu) {
          m_menu->exec(QPoint(x, y));
          return;
       }
       break;
    default:
       
   }
   
   if (oldLayout != m_currentLayout)
       emit LayoutChanged (m_currentLayout);
}

**Comment by hualet** [comment] 2019-03-13 06:18
@tribunal2000 you can use ` ``` `  to quote your code.

**Comment by tribunal2000** [comment] 2019-03-13 13:40
Thank you :+1: Now looks much better

**Comment by liuwen123** [comment] 2019-03-29 07:00
已修复

**Closed** 2019-03-29 07:17 UTC
