### ISSUE TITLE
'busy' cursor

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxdeepin/developer-center#250] opened 2017-04-09 19:01 UTC
I cannot reproduce this issue myself but on Manjaro several users are reporting that they get a 'busy' mousecursor immediately after login. It stops when they delete something and empty the trash. Otherwise it will just continue to show busy.
Anyone have an idea how to troubleshoot this?

**Comment by joksik** [comment] 2017-04-09 19:08
I'm one of the users who experience this error and I recorded a video showing that the bug affects only the desktop area in all the other windows the cursor behaves normally

https://uploadfiles.io/8e1231

**Comment by JulianLai** [comment] 2017-04-10 03:00
Same here
https://youtu.be/K7PQqPkLJm0

**Comment by hualet** [comment] 2017-04-10 04:43
Affected users must have autostart applications, right ? @JulianLai

**Comment by JulianLai** [comment] 2017-04-10 04:45
@hualet No, ~/.config/autostart is empty.

**Comment by hualet** [comment] 2017-04-10 05:29
@JulianLai Then please attach the log file of dde-desktop of dde-dock which are located at ~/.cache/deepin/dde-desktop/

**Comment by joksik** [comment] 2017-04-10 06:00
**hualtet** autostart entries clean and clean manjaro deepin installation. The problem occurs immediately after the first time you start your computer. No updates or other programs were installed. I just changed the language in the settings.

edit; 
Okay, when I'm in the house I will join the logs

**Comment by JulianLai** [comment] 2017-04-10 06:56
[dde-desktop.log.zip](https://github.com/linuxdeepin/developer-center/files/909221/dde-desktop.log.zip)

**Comment by hualet** [comment] 2017-04-10 07:53
`
startup notification initiated:  startdde-408-Julian-PC-pamac-tray-0_TIME0
`
I've noticed this line at the end of the log file, pamac-tray is shipped with DDE on Manjaro?

**Comment by joksik** [comment] 2017-04-10 08:04
yes pamac-tray is default installing in Manjaro

**Comment by oberon2007** [comment] 2017-04-10 09:10
I don't have the issue although of course I am using pamac aswell. Also not in vbox with a fresh ISO, which also has pamac of course. But you can try to narraw down the problem by closing pamac. Just click on the systray, then right click on pamac and 'Quit'. After that check if the busy cursor comes back.

**Comment by oberon2007** [comment] 2017-04-10 09:12
Even better, try removing pamac temporarily to see if that's causing it. It uses a dbus service...

**Comment by joksik** [comment] 2017-04-10 14:18
my logs:
[deepin.zip](https://github.com/linuxdeepin/developer-center/files/910325/deepin.zip)

I turned off pamac-tray form autostart by delete pamac-tray.desktop from /etc/xdg/autostart and nothing changed. cursor still busy so it`s no pamac-tray issue

**Comment by joksik** [comment] 2017-04-13 09:05
How is the investigation going? Have you managed to determine something? or maybe we must add some additional logs?

**Comment by hualet** [comment] 2017-04-13 13:36
Sorry, got no time this day to deal with problem. Just downloaded the logs, I still see pamac starting int the log file, why ?

**Comment by oberon2007** [comment] 2017-04-13 14:15
That's why I meant it would be good to remove pamac altogether, not just pamac-tray auto-start to check if this is causing the busy cursor. In any case out would be strange, since I don't see the issue and my pamac plus pamac-tray are running also... 😉

**Comment by joksik** [comment] 2017-04-14 06:29
hmm very very strange

1) i run livecd for fresh install and works good
2) after install at login screen where i must enter my password works good
3) first deskopt run and i have busy cursor
4) i try pacman -Rcs pamac and reboot
5) and woorks good xD :))))
6) so if pamac dont work i try switch to octopi
7) after i install octopi i have busy cursor :////
8) so i can`t have pamac and octopi? and software to check system updates it causes this bug

btw after fresh install i see new bug. when i want connect to my wifi it`s does not ask for password and i must manully enter my password in deepin control center

**Comment by oberon2007** [comment] 2017-04-14 07:23
It's weird. I am running pamac without the cursor problem.
The wifi issue, yes, it's not new: https://github.com/linuxdeepin/developer-center/issues/246

**Comment by joksik** [comment] 2017-04-14 07:25
I am sending new logs if they can help

https://ufile.io/8fdd1

**Comment by oberon2007** [comment] 2017-04-14 07:25
@hualet I don't know about **octopi**, but **pamac** uses a daemon and a dbus service - maybe that's the problem?
If you'd like to check pamac sources, they are [here](https://github.com/manjaro/pamac)

**Comment by joksik** [comment] 2017-04-14 07:30
We will wait what the deepin programmers will say. I think that since two different programs cause the same error, unfortunately they are guilty of deepin. I do not know just why the problem does not occur at everyone. Could it be a hardware configuration? i use laptop lenovo i3 6th generation,intel 520HD graphics card and ssd disc with 4 gb ram

> 20170414.10:24:25.005[Debug][monitor_event_func                  34   0x9b19e0 ] startup notification initiated:  startdde-694-laptop-octopi-notifier-0_TIME0
> 
> 20170414.10:02:56.336[Debug][monitor_event_func                  34   0x23ad9e0 ] startup notification initiated:  startdde-625-laptop-pamac-tray-0_TIME0

**Comment by hualet** [comment] 2017-04-14 07:31
That's because the desktop file (in /etc/xdg/autostart/ directory) claims that it needs Startup Notification, but  it actually won't open a new window on startup completed which is needed to stop the busy cursor. So you can simple remove the StartupNotify line in the desktop file to work around this problem.

**Comment by hualet** [comment] 2017-04-14 08:03
@joksik Do other DEs share the same problem?

**Comment by joksik** [comment] 2017-04-14 08:03
ok i do what you write and edit /etc/xdg/autostart/octopi-notifier.deskopt and delete this line:
> 
StartupNotify=true

and i test this solution with pamac.deskopt and it works in 100%. thanks for help now i can again use deepin ;) but i don`t know who was guilty? manjaro team added this useless line?if it will not be fixed after every pure install i and other people that have this bug must manually edit this file

**Comment by hualet** [comment] 2017-04-14 08:18
I see this line in the source code, so it's not Manjaro's fault.
@oberon2007 Your machine works well, right ? can you upload the log file ?

**Comment by oberon2007** [comment] 2017-04-14 11:11
Thanks @hualet ! 
Here you are.
[dde-desktop_log.txt](https://github.com/linuxdeepin/developer-center/files/921955/dde-desktop_log.txt)
[dde-dock_log.txt](https://github.com/linuxdeepin/developer-center/files/921956/dde-dock_log.txt)
As I said I don't get the busy cursor, however I have suddenly a new problem that seems to have surfaced with latest package upgrades. That's that most of the time the tray doesn't show up at all as long as pamac-tray is the only tray app running. I used to have this same issue a while ago but it had disappeared, now it seems to be back 🙄 When I launch skype for example the tray appears, but without pamac-tray icon. At the same time pidof ``pamac-tray`` shows that it is in fact running, just invisible 😉 Some rare times the systray with pamac-tray does show up normally after login.
I'll catch logs for on occasion where the tray icon goes missing, but maybe I should open a separate issue for that?

**Comment by oberon2007** [comment] 2017-04-14 11:15
As you see I do get 
```
20170414.12:41:23.227[Debug][monitor_event_func                  42   0x1898ba0 ] startup notification completed:  startdde-607-manjaro-deepin-pamac-tray-0_TIME0
```
!

**Comment by ag14774** [comment] 2017-04-15 10:59
I had the same problem. I commented out StartupNotify=true in pamac-tray.desktop and it works now! Great!

**Comment by oberon2007** [comment] 2017-04-16 08:57
@hualet I don't really understand what is going on here? How is it possible that this is only a problem for some people and also not in the live session, where pamac-tray is equally launched.
Also in the logs I see both ``startup notification initiated`` and ``startup notification completed``! Should n't that normally stop the spinning cursor?

**Comment by cyc0ol** [comment] 2017-04-18 01:40
I ran into this issue after updating manjaro deepin, i tried to disable window effects and somehow the problem went away as well as problem on changing resolution on my second monitor that turns off after changing resolution.  Is it also problem on window effects as well? I don't have this issue before updating..thanks.

**Comment by joksik** [comment] 2017-04-18 16:36
Let's hope that they are working on the fix because on manjaro board, more and more people are complaining about this bug

**Comment by hualet** [comment] 2017-04-19 04:59
Sorry, just have been very busy with our 15.4 final release for a few days.
Thanks all for the information, but I'm still not aware of the root cause of this issue.

**Comment by hualet** [comment] 2017-04-19 05:00
@oberon2007 Where can I get a latest ISO of your distro? I need to test it myself.

**Comment by joksik** [comment] 2017-04-19 05:04
https://sourceforge.net/projects/manjarotest-community/files/deepin/17.0.1-rc3-testing/

**Comment by cyc0ol** [comment] 2017-04-19 05:31
@hualet i tried the solution above and it works perfectly then i changed my video card to proprietary driver and it works well. I can now enable windows effect without any problem. Thanks.

**Comment by hualet** [comment] 2017-04-19 05:34
@cyc0ol Great, but it's just a work-around, not a solution. 😅 

@joksik Thanks for the download link, downloading.

**Comment by cyc0ol** [comment] 2017-04-19 05:57
@hualet i forgot to mention that i have tried to install deepin with antergos and i also had the same problem mentioned above.

**Comment by oberon2007** [comment] 2017-04-19 08:57
@hualet latest builds are [here](https://sourceforge.net/projects/manjarotest-community/files/deepin/17.0.1-rc3-testing/) Problem is that the live environment is not showing the issue, Ali in the install as you know not for everyone... Thank you very much anyway and good luck! 😉

**Comment by hualet** [comment] 2017-04-20 06:23
I failed to install Manjaro on my test PC :sob: So I have to install it in my virtualbox. And I didn't reproduce the problem, so...

**Comment by oberon2007** [comment] 2017-04-20 06:34
What is your problem installing, how did it fail?

**Comment by oberon2007** [comment] 2017-04-20 09:14
In any case the issue seems to be somehow related to how Deepin (not) handles pamac and octopi's ``startup notification completed``, which seems in fact to happen. apparently Deepin is unable to deal with such a notification when no window is opened by the application, correct?

**Comment by oberon2007** [comment] 2017-04-20 09:17
@hualet can you not maybe just build/install pamac on another system? Or you'd probably just need to find or reconfigure any other tray application that doesn't open a window at startup?

**Comment by hualet** [comment] 2017-04-20 09:36
After the install process finished, I reboot my computer, and it didn't show up in the grub list. @oberon2007 
App launcher send the startup message, and it's the job of the launchee to send the launch finished signal, basically Qt and GtK will do the job when the window pop up. On manjaro-deepin I see the completed message every time and no busy cursor. So  I'll keep digging to see what's the root cause of this issue anyway.

**Comment by oberon2007** [comment] 2017-04-20 09:45
@hualet but I can see that @joksik 's log also contains the "completed" message!

**Comment by joksik** [comment] 2017-04-20 09:45
In my free time for testing I installed antergos base without any DE. i manually install all package
`pacman -S xorg xorg-server && pacman -S deepin && pacman -S deepin-extra `
so i have the latest fresh package from Arch not manjaro and after and run systemctl start lightdm.service and login into deskopt i have busy cursor;))) but this bug its only on my laptop i do the same steps on deskopt computer and it works good.

**Comment by hualet** [comment] 2017-04-20 11:30
@oberon2007 that means @joksik may not having busy cursor every time?

**Comment by oberon2007** [comment] 2017-04-20 13:27
I just looked at the log he posted earlier in this tread! I think he has the issue every time, right @joksik

**Comment by JulianLai** [comment] 2017-04-20 16:06
I have the issue everytime with antergos

**Comment by joksik** [comment] 2017-04-20 16:28
**oberon2007** right. i have in home 2 computers laptop ideapad 310-15isk and deskopt computer. on my laptop i have this issue every time on manjaro or on antergos and for me help only logout like **JulianLai** write or empty trash. strage is that on my second computer it`s works fine so its really strange. maybe hardware issue?**JulianLai** maybe you have intel skylake like me in laptop?

**Comment by ag14774** [comment] 2017-04-20 23:47
Just wanted to add something that might be related. When I first installed Manjaro Deepin I did not have this issue. However, I had a very similar problem where my cursor would keep spinning after startup until I would open my first window(usually deepin file manager). Once I had opened a window, it would stop. Then an update came that made this spinning "permanent"

**Comment by hualet** [comment] 2017-04-21 02:03
What's the content of that update ?

**Comment by JulianLai** [comment] 2017-04-21 14:09
@joksik No, it is a PC with intel i5-4460 and AMD RX460

**Comment by ag14774** [comment] 2017-04-22 00:25
@hualet Sorry I can't remember but it must have been towards the end of February when my problems started. I had opened this issue when it first happened for me: https://github.com/linuxdeepin/dde-desktop/issues/16.

**Comment by JulianLai** [comment] 2017-04-22 00:50
It has been fixed for me now.

**Comment by joksik** [comment] 2017-04-23 17:01
**oberon2007** maybe you have right. few times i was see some strange dock enteries but
I never connected

**Comment by joksik** [comment] 2017-04-29 16:08
I see that the topic has dropped can I somehow help to locate the error? Any extra logs or give remote access to computer?

**Comment by DanyGee** [comment] 2017-09-20 12:53
For me on Deepin 15.4.1 the cause of the busy cursor was Geary and its option to monitor for new messages. Turning it off brought normal cursor after every reboot/login. So, a good practice in similar case will be to check autostart apps and their autostart features.

**Comment by ViciousMagician** [comment] 2017-10-26 13:39
I have had this start happening to me in the last week or so.  When I reboot i have to login - logout - login again to get the wait cursor to go away.  It only happens on my primary monitor not my secondary.  My primary is an external running over mini-dp and secondary is the laptop screen.  Im running on a Dell Precision 5510.

**Comment by jouyouyun** [comment] 2017-11-06 06:46
@electricface

**Comment by mitchellkrogza** [comment] 2019-03-10 12:37
Same problem for me on Linux manjaro-cinnamon 4.20.11-1-MANJARO
I tried deleting the line StartupNotify=true in /etc/xdg/autostart/pamac-tray.desktop and rebooted but alas ... that does not work. How can I please disable this spinning mouse pointer, it drives me mad.

**Comment by DanyGee** [comment] 2019-03-10 14:14
> Same problem for me on Linux manjaro-cinnamon 4.20.11-1-MANJARO
> I tried deleting the line `StartupNotify=true` in `/etc/xdg/autostart/pamac-tray.desktop` and rebooted but alas ... that does not work. How can I please disable this spinning mouse pointer, it drives me mad.

Check autostart apps (and their in-app settings).
You can also quickly open system monitor after login and see what is taking resources at start - this might point the direction where to look next.

**Comment by mitchellkrogza** [comment] 2019-03-10 14:19
Thanks @DanyGee my problem is not at startup though, it happens after I've been working for some time. I might switch to a tab in a browser or open text editor, or even just file manager and then it starts with the rotating mouse "busy" animation. It seems many apps randomly trigger it to start animating.

**Comment by hualet** [comment] 2019-03-13 06:14
I just submit a PR to give the startup notification a timeout of 15s, hope it can workaround that situation a little bit? https://cr.deepin.io/#/c/dtkwidget/+/41962 @zccrs

**Comment by mitchellkrogza** [comment] 2019-03-13 15:41
@hualet will this solve anything? Why can someone not just add an option "Animate mouse cursor = NO"

**Comment by mitchellkrogza** [comment] 2019-03-25 07:28
@oberon-manjaro will there ever be a solution to turn this mouse animation OFF completely? It's a severe annoyance to me, try working in wordpress all day long and trying to position your mouse at a certain part of text with a big ball spinning in front of you all the time. There seriously must be options to turn off things that Linux people do not want or need otherwise we are just becoming Windows and Mac which is sad. It's also nothing to do with Firefox because I have disabled StartupNotify in firefox ... to no effect and it happens in Nemo, TextEdit and just about everything else. 
![IMG_20190325_092415](https://user-images.githubusercontent.com/9961541/54901821-5491e880-4ee0-11e9-9b29-4a21c6d0a6b0.jpg)

**Comment by mitchellkrogza** [comment] 2019-03-25 13:40
This is by no means a permanent solution to the problem, but for now this gets rid of the annoying busy animation. Today is one of those days it has been driving me utterly mental, it seem ajax events inside wordpress trigger the cursor to animate.

Navigate to your cursor theme folder, in this example I am using capitaine-cursors
```
cd /usr/share/icons/capitaine-cursors/cursors/
sudo mv wait wait.old
sudo cp left_ptr wait
sudo reboot
```
This simply replaces the wait icon with the regular pointer, so when it's now busy it just won't show you anything but your regular pointer.

**Comment by oberon-manjaro** [comment] 2019-03-25 14:03
We don't yet have a new release of **dtkwidget** including @hualet 's patch.
I will for now repackage **2.0.9.17** for manjaro and include the patch so we can at least find out if that will solve the problem ...

**Comment by mitchellkrogza** [comment] 2019-03-25 15:03
Thanks @oberon-manjaro look forward to see if this can be resolved for good

**Comment by oberon-manjaro** [comment] 2019-03-25 15:43
@mitchellkrogza if you would like to test the patched version:
If you don't want to wait for the update to arrive via your mirror you can install the pkg directly, but since currently we have two different qt5 versions, make sure you install the matching one for your branch! :wink:
If you are on n Manjaro unstable or testing branch you have to install
`sudo pacman -U https://mirror.philpot.de/manjaro/pool/overlay/dtkwidget-2.0.9.17-2.3-x86_64.pkg.tar.xz.sig`
while on stable branch you will need
`sudo pacman -U https://mirror.philpot.de/manjaro/pool/overlay/dtkwidget-2.0.9.17-2.2-x86_64.pkg.tar.xz.sig`

**Comment by oberon-manjaro** [comment] 2019-03-26 08:03
Apparently the feedback for this patch is not good:
https://forum.manjaro.org/t/deepin-bug-after-dtkwidget-update/80470 :disappointed: 
@mitchellkrogza have you tested? I'm afraid I will have to roll this back...

**Comment by mitchellkrogza** [comment] 2019-03-26 08:06
Morning @oberon-manjaro not tested yet but think I should hold back based on that feedback

**Comment by oberon-manjaro** [comment] 2019-03-26 08:08
No, please test!

**Comment by mitchellkrogza** [comment] 2019-03-26 08:17
@oberon-manjaro will do, how do I revert if it causes me grief?

**Comment by oberon-manjaro** [comment] 2019-03-26 08:19
I will push the original un-patched **2.0.9.17** version to our repos now. You can then simply update. Or I will instruct - I'm here and working on it... :wink: 
I can provide direct links to packages for you for whichever version you need in the end.

**Comment by mitchellkrogza** [comment] 2019-03-26 08:23
Great @oberon-manjaro let me try now and will keep you updated

**Comment by mitchellkrogza** [comment] 2019-03-26 08:24
```
 dtkwidget-2.0.9.17-2.2-x86_64.sig                                                  310.0   B  43.2K/s 00:00 [################################################################] 100%
error: failed retrieving file 'dtkwidget-2.0.9.17-2.2-x86_64.pkg.tar.xz.sig.sig' from mirror.philpot.de : The requested URL returned error: 404
warning: failed to download https://mirror.philpot.de/manjaro/pool/overlay/dtkwidget-2.0.9.17-2.2-x86_64.pkg.tar.xz.sig.sig
loading packages...
error: '/var/cache/pacman/pkg/dtkwidget-2.0.9.17-2.2-x86_64.pkg.tar.xz.sig': package missing required signature
```

**Comment by keybreak** [comment] 2019-03-26 08:25
@oberon-manjaro 
Based on reading here, i would say timer is a little overkill even for a temporary solution :smile:

**Comment by oberon-manjaro** [comment] 2019-03-26 08:33
Actually I don't see how @hualet 's [patch](https://github.com/linuxdeepin/dtkwidget/commit/79473dfab2ba17694ded8568431a0f55c87d0492) is causing the other issues - but what do I know :wink: 
@mitchellkrogza I'm currently rolling back versions ... maybe the server was just syncing when you tried to installl :stuck_out_tongue_winking_eye: 
Stay tuned, I will send you some new links when I am done here ...

**Comment by oberon-manjaro** [comment] 2019-03-26 08:35
@mitchellkrogza are you on stable branch?

**Comment by keybreak** [comment] 2019-03-26 08:39
Well,...Some voodoo magic there :smile_cat: 

> Visual inspection is because the code of the dock limits the frequency of icon refreshes. 

(c) **listenerri** translated from ttps://github.com/linuxdeepin/developer-center/issues/1023

**Comment by mitchellkrogza** [comment] 2019-03-26 08:50
@oberon-manjaro yes on stable

**Comment by oberon-manjaro** [comment] 2019-03-26 09:01
Alright, @mitchellkrogza here's your selection:
* original un-patched **2.0.9.17** release:
`sudo pacman -U http://www.oberon.at/oberon/src/dtkwidget-2.0.9.17-2.4-x86_64.pkg.tar.xz`
* @hualet 's patch included:
`sudo pacman -U http://www.oberon.at/oberon/src/dtkwidget-2.0.9.17-2.5-x86_64.pkg.tar.xz`
* latest git snapshot:
`sudo pacman -U http://www.oberon.at/oberon/src/dtkwidget-2.0.9.17-2.6-x86_64.pkg.tar.xz`
Thanks a lot for your help!

**Comment by mitchellkrogza** [comment] 2019-03-26 09:03
Ok great, Assuming I should try the one with @hualet's patch?

**Comment by oberon-manjaro** [comment] 2019-03-26 09:04
Just try them all and let us know what happens! :grinning: ADVENTURE!

**Comment by mitchellkrogza** [comment] 2019-03-26 09:09
Ok have installed 2.0.9.17-2.5 and rebooted. So far so good, not currently seeing the issue reported with the dock resetting.

Now for 2.0.9.17-2.6

**Comment by oberon-manjaro** [comment] 2019-03-26 19:01
Thank you. Feedback on the Manjaro forum is that the latest git snapshot seems to work fine for everyone. So I will package it like that for now.

> when I always log into cinnamon for the first time....

Cinnamon?

**Comment by erikKeresztes** [comment] 2020-07-13 02:46
Still happening. I use latest deepin v20 distro with deepin DE.

**Comment by tsic404** [comment] 2022-01-07 03:13
Still happening?

**Comment by tsic404** [comment] 2022-01-21 10:03
This issue will close, if you still have problem you can reopen this.

**Closed by tsic404** 2022-01-21 10:03 UTC
