### ISSUE TITLE
[Arch Linux] Dock windows preview on mouse click / hover becomes unusable

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1200] opened 2019-05-19 17:27 UTC
## Describe the bug
Preview is very buggy now on **deepin-mutter** (which is still default for Arch / Manjaro):
1. On mouse hover only shows first selected Windows and then get stuck and doesn't update other windows.

2. On mouse click with 90% probability creates another window on background (which is just a copy of selected window and not active), everything becomes very glitchy and a lot of times you can't even move selected window, same goes on next preview window click.

Basically described problems makes whole functionality of switching windows from dock preview unusable.

## To Reproduce
1. Video 1
https://i.imgur.com/3gzndbB.mp4

2. Video 2
https://i.imgur.com/oqrTe4N.mp4

## Expected behavior
Just bring back what was always working very good:
1. Preview on mouse hover should show selected window

2. Preview on mouse click should:
    - Bring selected window on top
    - Should **NOT** hide all other windows
    - Should **NOT** create some buggy copy of selected Windows which is impossible to close / move

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 4.19.42-1-MANJARO
Shell: bash 5.0.7
DE: Deepin 15.10.1
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.3.0
tk: Qt 5.12.3
dm: LightDM

### Distro & Version
Arch / Manjaro Deepin

### Related package version
deepin-wm  1.9.38-1

### Additional context
Started happen on **deepin-mutter** ~ month ago, in the process of moving to **deepin-kwin**.
That's kinda break a lot of working habits...Really need to be fixed

**Comment by antechdesigns** [comment] 2019-05-19 22:39
I can confirm this is happening on my archdeepin.

**Comment by Lokke** [comment] 2019-05-20 10:03
i am able to reproduce this as well

![DeepinBildschirmfoto_Bereich auswählen_20190520120149](https://user-images.githubusercontent.com/6406275/58013595-33700180-7af7-11e9-88b2-d377b5fbd8af.png)


deepin-account-faces 1.0.11-1
deepin-anything 0.0.9-1
deepin-anything-dkms 0.0.9-1
deepin-api 3.18.4-1
deepin-boot-maker 2.0.4.11-1
deepin-calculator 1.0.11-1
deepin-calendar 1.2.7-1
deepin-clone 1.1.2.1-1
deepin-clutter 1.26.2-2
deepin-cogl 1.22.5-2
deepin-control-center 4.10.4-1
deepin-crossover 16.0.6-1
deepin-daemon 3.27.2-1
deepin-desktop-base 2:2019.05.12-1
deepin-desktop-schemas 3.13.1-1
**deepin-dock 4.9.13-1**
deepin-draw 1.0.0-2
deepin-editor 1.2.6.4-1
deepin-file-manager 1:4.8.4.1-1
deepin-grub2-themes 1.0.0-3
deepin-gtk-theme 17.10.10-1
deepin-icon-theme 15.12.70-1
deepin-iconthemes-manjaro 20170918-1
deepin-image-viewer 1.3.13-1
deepin-launcher 4.6.10-1
deepin-manual 2.0.19-1
deepin-menu 3.4.8-1
deepin-metacity 3.22.24-1
deepin-movie 1:3.2.22.1-1
deepin-music 3.1.17.1-1
deepin-mutter 3.20.38-1
deepin-network-utils 0.1.4-1
deepin-picker 1.6.5-1
deepin-polkit-agent 0.2.6-1
deepin-polkit-agent-ext-gnomekeyring 0.1.0-1
deepin-qt-dbus-factory 1.1.1-2
deepin-qt5dxcb-plugin 1.2.0-1
**deepin-qt5integration 0.3.11-2**
deepin-screen-recorder 2.7.11-1
deepin-screensaver 0.0.8-1
deepin-screenshot 4.1.11-1
deepin-session-ui 4.9.7-1
deepin-shortcut-viewer 1.3.5-1
deepin-sound-theme 15.10.3-1
deepin-system-monitor 1.5.0-1
deepin-terminal 3.2.3.1-1
deepin-turbo 0.0.3-1
deepin-voice-recorder 1.4.0-1
deepin-wallpapers 1:1.7.7-1
deepin-wallpapers-extra 1.5-1
**deepin-wm 1.9.38-1**
qt4 4.8.7-29
**qt5-base 5.12.3-2**
qt5-declarative 5.12.3-2
qt5-graphicaleffects 5.12.3-1
qt5-location 5.12.3-1
qt5-multimedia 5.12.3-1
qt5-quickcontrols 5.12.3-1
qt5-quickcontrols2 5.12.3-1
qt5-script 5.12.3-1
qt5-sensors 5.12.3-1
qt5-speech 5.12.3-1
qt5-styleplugins 5.0.0.20170311-13
qt5-svg 5.12.3-1
qt5-tools 5.12.3-1
qt5-webchannel 5.12.3-1
qt5-webengine 5.12.3-2
qt5-webkit 5.212.0alpha2-28
qt5-websockets 5.12.3-1
qt5-x11extras 5.12.3-1
qt5-xmlpatterns 5.12.3-1
qtractor 0.9.7-1
qtwebkit-bin 2.3.4-9

**Comment by sonald** [comment] 2019-05-22 08:28
@zccrs  this should be a problem of dde-dock or it is due to deepin-wm-dbus ?

**Comment by Lokke** [comment] 2019-05-22 20:54
i've played around on this topic.
i could figure out that switching between dde-file-managers without "windows effects" will result into similar effects - but the dde-dock will disapear for a short time. 

killed dde-dock, restarted it in deepin-terminal and did the same as before. 

```
2019-05-22, 22:41:22.122 [Debug  ] [                                                         0] app item clicked, name: "Datei-Manager" id: "e0T5ce53287" my-id: "e0T5ce53287" icon: "dde-file-manager"
2019-05-22, 22:41:24.121 [Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x5630aa7ff100, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
2019-05-22, 22:41:29.959 [Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x5630aa7ff100, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
2019-05-22, 22:41:31.394 [Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x5630aa7ff100, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
2019-05-22, 22:41:32.722 [Debug  ] [                                                         0] app item clicked, name: "Datei-Manager" id: "e0T5ce53287" my-id: "e0T5ce53287" icon: "dde-file-manager"
2019-05-22, 22:41:33.839 [Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x5630aa7ff100, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
2019-05-22, 22:41:35.416 [Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x5630aa7ff100, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
2019-05-22, 22:41:36.683 [Debug  ] [                                                         0] app item clicked, name: "Datei-Manager" id: "e0T5ce53287" my-id: "e0T5ce53287" icon: "dde-file-manager"
2019-05-22, 22:41:37.825 [Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x5630aa7ff100, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
2019-05-22, 22:41:41.423 [Warning] [                                                         0] requestActivate() called for  QWidgetWindow(0x5630aa7ff100, name="Dtk::Widget::DArrowRectangleClassWindow")  which has Qt::WindowDoesNotAcceptFocus set.
2019-05-22, 22:41:41.536 [Warning] [dregionmonitor.cpp   Dtk::Widget::DRegionMonitor::registerRegion 44] region already registered!
[1]    11173 segmentation fault (core dumped)  dde-dock

```
https://www.youtube.com/watch?v=Sm5S0_sLzqM

**Comment by Lokke** [comment] 2019-05-23 20:59
![DeepinBildschirmfoto_dde-desktop_20190523225332](https://user-images.githubusercontent.com/6406275/58286159-67c11780-7dae-11e9-9f44-2759fb1ae759.png)
still pressend

**Comment by BLumia** [comment] 2019-06-29 15:52
dde-kwin seems no longer have this issue, did this issue still happens under Manjaro? If do, what's the package version? Thanks.

**Comment by keybreak** [comment] 2019-06-29 17:41
@BLumia 
1. Yes - Arch, Manjaro & Deepin under kwin all has:
    1) Hover part of problem still active (which looks little different than in this bug description of deepin-wm) - specifically if you open multiple windows of program, minimize them all - hover on preview will not reveal them and once you hover - preview window itself closes immediately.
    2) Click part of the problem - if you click sometimes not always window become transparent (like 5% opacity) and ghosted, but unlike deepin-wm you can at least restore it or close - since it's still same single window.
    3) On Arch i use latest deepin-kwin  0.0.11-1, on Linux Deepin also latest up to date - those were tested under VirtualBox VM.

2. Under deepin-wm:
   1) Hover part of problem was solved recently.
   2) Click part of problem is still here (up to date Manjaro / Arch setups on real hardware) - this is the worst part of problem show in bug description on video 2 **please solve it**.

**Comment by BLumia** [comment] 2019-06-29 18:07
Thanks for the additional info!

For dde-kwin cc @zccrs . for deepin-wm, it's deprecated from deepin team so there probably will no longer have bugfix, but I'm not sure if @sonald (`deepin-wm` maintainer before `dde-kwin` released) or other contributer still would like to offer some help.

For the dde-kwin issue if I remember correctly it's already fixed but I'm not quite sure about which commit/version fixed the related issue(I'm not the dde-kwin maintainer). Will test it again later under a non-dev enviroment.

**Comment by keybreak** [comment] 2019-06-29 18:13
Before deprecating **deepin-wm** completely it would be a good idea to make **deepin-kwin** at least somewhat more usable under Arch / Manjaro, or at least behave exactly same as under Linux Deepin.

**Comment by hbhgwtf** [comment] 2019-07-07 02:18
This problem also appeared on my computer from deepin unstable version 15.10 to 15.10.2.

**Comment by SiamSami** [comment] 2020-02-28 03:07
@keybreak Okay, I have managed to partially fix this issue.

**Comment by SiamSami** [comment] 2020-02-28 03:23
> @BLumia
> 
> 1. Yes - Arch, Manjaro & Deepin under kwin all has:
>    
>    1. Hover part of problem still active (which looks little different than in this bug description of deepin-wm) - specifically if you open multiple windows of program, minimize them all - **hover on preview will not reveal them and once you hover** - preview window itself closes immediately.

For that, open ~/.config/.kwinrc
Look for "[Compositing]" and under that, search for "HiddenPreviews" and set it's value to 6;
If you don't find "HiddenPreviews", then under "[Compositing]" type "HiddenPreviews=6".

Or,
You can try this program, https://github.com/SiamSami/Deepin-kwin-settings
Then, select the marked option and click on apply.
![deepin-screen-recorder_Select area_20200228092300](https://user-images.githubusercontent.com/33563064/75507699-f92f7b00-5a0b-11ea-8ba6-d534fe25da2b.gif)

**Comment by SiamSami** [comment] 2020-06-29 04:42
https://github.com/linuxdeepin/dde-dock/pull/280
Fixed and merged. Can anyone close it?

**Comment by BLumia** [comment] 2020-06-30 16:09
Here you go :)

**Closed by BLumia** 2020-06-30 16:09 UTC
