### ISSUE TITLE
Problem with lock screen

### ISSUE THREAD

**Issue by Peuczynski** [linuxdeepin/developer-center#479] opened 2018-02-21 07:39 UTC
When there are notification popups displayed and you enter wrong password, the textbox will periodically select all the content and show a hint that the password is wrong. This makes entering the password correctly almost impossible because when this happens while you correct the password, one of the characters in the sequence will replace the whole text entered.

**This doesn't happen when there are no popups displayed**

Steps how to reproduce:

1. Login with wifi on
2. Make the machine sleep (I closed the lid)
3. Enter the password wrong while the popups are displayed (to be sure just hit enter few times with wrong password)
4. Try entering the password
5. Good luck

To be able to do anything with the computer (even rebooting from the lock screen requires password) I have to either:

- switch to tty2 login and reboot from command line
- enter password one character at the time right after the text is selected and you press right arrow to deselect and be at the end of the input (this is what I did in the video)

This was happening way before the qt bug I reported few days ago (#476)

Please see the video attached
[deepin-screen-recorder_Select area_20180221082332.mp4.tar.gz](https://github.com/linuxdeepin/developer-center/files/1743164/deepin-screen-recorder_Select.area_20180221082332.mp4.tar.gz)

On another note: my password is normally 22 characters long; I change the password in order to be able to create this video.

Please note that:
1. If it's problematic to fix this please consider disabling the automatic selection of wrong password until it's fixed
2. There are way too many notifications for wifi, decreasing the number of popups is a good idea anyway IMO
3. I don't see the setting for the popup delay - decreasing this value would be good idea too

**Comment by Peuczynski** [comment] 2018-02-22 15:41
Turns out the popups doesn't matter

**Comment by hualet** [comment] 2018-02-23 03:19
You can just re-type your password after the text is selected and it'll be unlocked, I don't see this as a bug.

I'll close this issue for now.

**Comment by Peuczynski** [comment] 2018-02-23 18:12
No you can't. While typing the password the text will select itself again and every key stroke will replace, not add character to the textbox; making it almost impossible to unlock. Please refer to the video in the original post.

**Comment by hualet** [comment] 2018-02-24 01:55
Can't reproduce here, maybe it's been fixed ? @kirigayakazushin

**Comment by Peuczynski** [comment] 2018-02-26 08:12
@hualet If you can't reproduce, please leave it for a while; let me test on another machine I have Deepin + Arch installed. It's older versions so I can test as is and after updating to latest packages. I need a day to confirm.

**Comment by hualet** [comment] 2018-02-26 11:05
OK thanks
Peuczynski <notifications@github.com>于2018年2月26日 周一16:12写道：

**Comment by Peuczynski** [comment] 2018-02-26 21:52
@hualet  So I confirmed that on another machine that hasn't been updated since last year (I think) the problem exists. Because you couldn't reproduce I performed a fresh install for you on Virtualbox, and did these steps:
1. lock screen
2. typed wrong password (many random characters)
3. pressed enter several times
4. saved the state for you

you can download it here
https://we.tl/kW1e3BIdIA
https://we.tl/nqQJVDqtuB

Because you can't export the vbox machine with the saved state, I had to compress the machine folder.
To restore it you have to place the folder in VBox's VM's folder, and open the .vbox file with the virtualbox executable.

the correct password is "password"

BTW I think I found the most efficient workaround for now which is switching to another tty and then back to tty7, this disables the infinite textbox selection.

**Comment by hualet** [comment] 2018-02-27 03:08
OK, I'll try after the download is complete.

**Comment by jouyouyun** [comment] 2018-02-27 07:14
@felixonmars Try this cr: https://cr.deepin.io/32015

**Comment by hualet** [comment] 2018-02-27 07:16
@Peuczynski We've reproduced the problem on Arch, and @jouyouyun has submitted a CL to fix it as you can seen.

**Comment by yech1990** [comment] 2019-01-16 05:42
@felixonmars  @hualet  
The problem still exist.

**Comment by hualet** [comment] 2019-01-18 02:59
> @felixonmars @hualet
> The problem still exist.

Can you take a video of what you've encountered?

**Comment by yech1990** [comment] 2019-01-24 16:40
@hualet It is difficult to take a video when screen is locked.  Just as the description, the focus is lost, and the input not run into the password field.  The most weird thing is that input of keyboard control the opening applications directly, even the screen is locked.  This is extremely unsecured.

I had turn system auto suspension off, and just lock the screen. This happened only when the screen is locked for a long time (overnight).

**Comment by hualet** [comment] 2019-01-31 02:18
> @hualet It is difficult to take a video when screen is locked. Just as the description, the focus is lost, and the input not run into the password field. The most weird thing is that input of keyboard control the opening applications directly, even the screen is locked. This is extremely unsecured.
> 
> I had turn system auto suspension off, and just lock the screen. This happened only when the screen is locked for a long time (overnight).
> 
> My platform is Arch Linux on PC with Nvidia 1060 graphic card. I suspect that this issue is relative to the graphic card.

package versions?

**Comment by yech1990** [comment] 2019-01-31 06:54
It is the latest one in Arch Linux.

**Comment by justforlxz** [comment] 2021-04-23 07:08
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Closed by justforlxz** 2021-04-23 07:08 UTC
