### ISSUE TITLE
My desktop went black again!!!

### ISSUE THREAD

**Issue by daleybortolon** [linuxdeepin/developer-center#4591] opened 2023-05-31 18:37 UTC
### SUMMARY | 问题概要

My desktop went black again! But this time, just one of the 3 desktops went black, in the other 2 desktops I could see wallpapers, but not the ones I had set. All wallpapers were reset to Deepin ones.

carlos@carlos-PC:~$ dde-desktop
load translate "/usr/share/dde-file-manager/translations/dde-file-manager_en_GB"
20230531.13:50:24.268[Info][main 198 0x5560a30dfa50 ] start desktop "6.0.18" pid 9791 parent id 9754 argments ("dde-desktop") "Wed May 31 13:50:24 2023"
20230531.13:50:24.269[Error][main 205 0x5560a30dfa50 ] registerService Failed, maybe service exist QDBusError("", "")

A small window with an option to type my password on the black desktop (it had the word keyring in it, I think) appeared. After typing and changing desktops, all desktops had Deepin wallpapers again. Apparently, the problem happens when I set my own wallpapers!

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
Deepin 23
```

### STEPS TO REPRODUCE | 复现步骤

1.Turn on the computer
2. Desktop is black with a small window asking for password.
3. Changed desktop (I have 3) to next one. Could see wallpaper.
4. Afer a while I went back to the first one and it was working.

**Comment by BLumia** [comment] 2023-06-01 01:42
I don't have enough monitors to try to reproduce this issue. @babyfengfjx could you check if you can reproduce the issue?

btw, @daleybortolon what's the version of dde-desktop? (`apt policy dde-desktop`)

**Comment by babyfengfjx** [comment] 2023-06-01 02:34
@luodeepin  ，I suggest trying to replicate the issue to see if it exists. Currently, I have not encountered any similar problems in either single or dual-screen mode.

**Comment by daleybortolon** [comment] 2023-06-01 09:01
carlos@carlos-PC:~$ apt policy dde-desktop
dde-desktop:
  Installed: 6.0.18
  Candidate: 6.0.18
  Version table:
 *** 6.0.18 500
        500 https://community-packages.deepin.com/beige beige/main amd64 Packages
        500 https://proposed-packages.deepin.com/beige-testing unstable/dde amd64 Packages
        100 /var/lib/dpkg/status

**Comment by BLumia** [comment] 2024-01-05 06:10
Since we cannot reproduce this issue with your "steps to reproduce" info, we will close this for now as cannot reproduce. If you believe you can still reproduce this with the most recent version of the system, please feel free to let us now by sending a feedback within the preinstalled **deepin Home** app or create a new issue with detailed reproduce steps. Thanks!

**Closed by BLumia** 2024-01-05 06:10 UTC
Labels: triage | need more information, triage | need confirmation
