### ISSUE TITLE
Ghost in the shell

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1836] opened 2020-07-28 23:08 UTC
[Screen-cast](https://github.com/linuxdeepin/developer-center/files/4991593/Ghost.zip)

**Comment by gardotd426** [comment] 2020-08-06 05:58
Duplicate of #1776

**Comment by xmuli** [comment] 2020-08-24 05:41
Due to repeated closures, there will be updates later see #1776

**Closed by xmuli** 2020-08-24 05:41 UTC
Labels: duplicate | repeat or similar, place | WH
