### ISSUE TITLE
Deepin Launcher do not open after upgrading to Deepin 20.2.3

### ISSUE THREAD

**Issue by eduardomozart** [linuxdeepin/developer-center#2604] opened 2021-08-30 16:52 UTC
After upgrading from Deepin 20.2.2 to Deepin 20.2.3 through ``sudo apt-get dist-upgrade`` command, the Deepin Launcher stopped working. When I attempt to open it, it just flashes a kind of blur kind of effect but do not open (screen capture below):

https://user-images.githubusercontent.com/2974895/131375148-52f321ee-0ac2-4721-95c7-2338a233f982.mp4

When I reboot the computer, it starts working again but after sometime it stops working again.

It works normally when I run ``dde-launcher`` from Terminal. Only the following errors are shown into Terminal when running ``dde-launcher``, but I do not believe they are related to this problem:

```
No appenders assotiated with category dde.dsvg
[Warning] <> set cache file modified date time failed, error message: "Argumento inválido" , cache file: "/home/eduardo/.cache/deepin/icons/62a0a25a24f8543edc46a21aea0673b2c153ba7a.png" , svg file: "/var/lib/flatpak/exports/share/icons/hicolor/scalable/apps/com.gitlab.ColinDuquesnoy.MellowPlayer.svg"
2021-08-30, 13:45:23.403 [Warning] [  ] libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by hhaim** [comment] 2022-03-22 08:01
@JiashunLi very strange that this basic bug wasn't solved already

**Comment by JiashunLi** [comment] 2022-03-22 08:27
@hhaim 我现在是 20.4 目前好像正常了，我不确定是否是个例。

**Comment by hhaim** [comment] 2022-03-22 08:29
@JiashunLi but you reported that 20.4 does not work too (a big delay)? was it a one time thing?

**Comment by JiashunLi** [comment] 2022-03-22 08:32
@hhaim 是的，刚升级到20.4的时候，确实还存在有延迟，需要多点击几次才能打开启动器。
在经过几次更新之后，最近没有发现这个问题了。但是官方更新说明里并没有说修复了这个问题。

**Comment by hhaim** [comment] 2022-03-22 08:34
@JiashunLi understood. It is strange that it wasn't reported as a solved issue.

**Comment by BLumia** [comment] 2022-03-22 08:34
@hhaim we're sorry we didn't pay too much attention to repos that outside **developer-center** repo before. This issue itself might be solved already and I'm just transferring issues from different repos to the develop-center repo.

We'll re-verify if the issue still exists and will close them if the related bug is fixed, and we'll pay more attention to community feedback so issues like this one will get responses timely.

**Comment by JiashunLi** [comment] 2022-03-22 08:42
@hhaim 或许，你可以在你的计算机上测试一下是否还存在这样的问题。

**Comment by BLumia** [comment] 2022-03-28 03:44
Hi, I did verify this issue and it's no longer exists on `deepin v20.4` with `dde-launcher 5.5.6-1`.

I'll close this issue for now. If you still got a similar issue, please feel free to create another issue with the necessary detailed information so we could look into it. Thanks!

**Closed by BLumia** 2022-03-28 03:44 UTC

**Comment by celiorodriguesvieira** [comment] 2022-03-30 01:43
Hi,

I have this problem with deepin v20.4  and dde-launcher-dbgsym (5.5.6-1). 

`No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"
2022-03-29, 22:40:34.902 [Warning] [  ] QWidget::setMinimumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (204,-6) are not possible
2022-03-29, 22:40:34.902 [Warning] [  ] QWidget::setMaximumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (204,-6) are not possible
2022-03-29, 22:40:34.902 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-104,-6) are not possible
2022-03-29, 22:40:34.905 [Warning] [  ] QWidget::setMinimumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (204,-6) are not possible
2022-03-29, 22:40:34.905 [Warning] [  ] QWidget::setMaximumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (204,-6) are not possible
2022-03-29, 22:40:34.905 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-104,-6) are not possible
2022-03-29, 22:40:34.905 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-104,-6) are not possible
2022-03-29, 22:40:34.908 [Warning] [  ] QWidget::setMinimumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (306,-6) are not possible
2022-03-29, 22:40:34.908 [Warning] [  ] QWidget::setMaximumSize: (/Dtk::Widget::DHBoxWidget) Negative sizes (306,-6) are not possible
2022-03-29, 22:40:34.908 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-104,-6) are not possible
2022-03-29, 22:40:34.908 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-104,-6) are not possible
2022-03-29, 22:40:34.908 [Warning] [  ] QWidget::setMinimumSize: (/AppGridView) Negative sizes (-104,-6) are not possible
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
2022-03-29, 22:40:34.942 [Warning] [  ] QLayout::parentWidget: A layout can only have another layout as a parent.
No appenders assotiated with category dtk.dsg.config
[Warning] <Dtk::Core::{anonymous}::DBusBackend::load> dbus path="/dde_launcher/default/1000"`

**Comment by BLumia** [comment] 2022-03-30 02:10
> Hi,
> 
> I have this problem with deepin v20.4 and dde-launcher-dbgsym (5.5.6-1).

Hi @celiorodriguesvieira, please consider _**opening another issue**_ for your report since it might be caused by different reasons and replying to old issues might make bug hard to track.

**Comment by PrzemekSkw** [comment] 2022-03-30 20:19
Hello, I have the same issue after upgrade today. 
Deepin 20.4.
Regards

**Comment by BLumia** [comment] 2022-03-31 01:11
Hi @PrzemekSkw, please consider **_opening another issue_** instead of reply to this one for your report since it might be caused by different reasons and replying to old issues might make bug hard to track.

Please also provide your log file of the launcher and the output of `dmesg` so we could know what's going on.
