### ISSUE TITLE
[Terminal] Auto theme doesn't work

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3256] opened 2022-06-19 16:23 UTC
When setting the Terminal theme to automatic mode, it turns out that the other day (after turning on the computer), the application adjusts itself to the dark theme (ignoring the user's initial setting).

Another problem is the automatic change of the system theme; where the Terminal cannot change the theme automatically to accompany the system (part of the application is displayed in one theme and the rest in another theme - see attachment).

deepin-terminal 5.4.28
deepin Community 20.6 (OsBuild=11038.004)

![Capturar_select-area_20220618180250](https://user-images.githubusercontent.com/45263160/174485159-c3de7893-c548-4267-b4ea-9472dbb645f0.png)

**Comment by BLumia** [comment] 2022-06-20 01:18
> When setting the Terminal theme to automatic mode, it turns out that the other day (after turning on the computer), the application adjusts itself to the dark theme (ignoring the user's initial setting).

@babyfengfjx could you confirm if this exists? Thanks!

> Another problem is the automatic change of the system theme; where the Terminal cannot change the theme automatically to accompany the system (part of the application is displayed in one theme and the rest in another theme - see attachment).

I cannot reproduce this issue, did I missed something?

![2022-06-20_09-16-19](https://user-images.githubusercontent.com/10095765/174509011-3dbcea0d-41ce-453b-b729-7788f1685761.gif)

**Comment by Octavian-Q** [comment] 2022-06-20 08:07
> > When setting the Terminal theme to automatic mode, it turns out that the other day (after turning on the computer), the application adjusts itself to the dark theme (ignoring the user's initial setting).
> 
> @babyfengfjx could you confirm if this exists? Thanks!
> 
> > Another problem is the automatic change of the system theme; where the Terminal cannot change the theme automatically to accompany the system (part of the application is displayed in one theme and the rest in another theme - see attachment).
> 
> I cannot reproduce this issue, did I missed something?
> 
> ![2022-06-20_09-16-19](https://user-images.githubusercontent.com/10095765/174509011-3dbcea0d-41ce-453b-b729-7788f1685761.gif) [ ](https://user-images.githubusercontent.com/10095765/174509011-3dbcea0d-41ce-453b-b729-7788f1685761.gif) ![2022-06-20_09-16-19](https://user-images.githubusercontent.com/10095765/174509011-3dbcea0d-41ce-453b-b729-7788f1685761.gif) [ ](https://user-images.githubusercontent.com/10095765/174509011-3dbcea0d-41ce-453b-b729-7788f1685761.gif)

I managed to replicate the issues, is hard to explain but I will try my best. 
1. Set terminal to System Theme
2. If theme is dark for example, close the terminal, then change theme to light
3. Open terminal again and will stay dark (this to specify it auto selected dark theme, I set every time System Theme and never change)
![Screenshot_select-area_20220620105923](https://user-images.githubusercontent.com/98664445/174553861-9b2abca0-2189-4816-8917-8281c3653fa3.png)
Same happens vice versa, If I am in light theme, I close the terminal with option System Theme selected then after closing I change theme to dark, it stays light (doesnt auto change after closing terminal and theme is changed)
![Screenshot_select-area_20220620105848](https://user-images.githubusercontent.com/98664445/174554333-40309e3c-6a53-4300-acbd-6d483f2f7f78.png)

**Comment by babyfengfjx** [comment] 2022-06-20 08:23
Yes, your terminal will only follow the change when you set the theme of the terminal to follow the theme option of the system, and if you manually switch the terminal to another theme at this time, it will no longer follow the theme of your system.

**Comment by Octavian-Q** [comment] 2022-06-20 08:26
> Yes, your terminal will only follow the change when you set the theme of the terminal to follow the theme option of the system, and if you manually switch the terminal to another theme at this time, it will no longer follow the theme of your system.

Problem is it auto changes settings. I am setting theme to System theme (it follows the theme as should) but, when I close the terminal, change theme from dark to light, terminal stays dark and option Dark theme is auto selected. When I made sure I use System Theme before terminal being closed

**Comment by SuperEffie** [comment] 2022-09-29 02:59
Thanks for your feedback.We got what you mean. We have also reproduced the issue and submitted it to the developers for repair. Before changing the system theme, we need to close the terminal.
If the problem is solved later, we will informed you here.Welcome to provide us with more suggestions.

**Comment by SuperEffie** [comment] 2023-02-02 06:43
The terminal has been upgraded to version 5.9.40 in the Deepin 20.8. This problem you mentioned has been fixed, which you can help us confirm. Now I want to close this issue. 
Thank you again and welcome to provide us with more feedback~

**Closed by SuperEffie** 2023-02-02 06:43 UTC
Labels: triage | need more information, triage | need confirmation
