### ISSUE TITLE
A white square border flashes on the close button when clicking on the preview window popup of dock

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#66] opened 2016-03-09 14:46 UTC
Demo:

![white_square](https://cloud.githubusercontent.com/assets/1006477/13638762/bc202556-e648-11e5-9ee7-c4298c17116b.gif)

**Comment by fasheng** [comment] 2016-03-09 15:07
@sbwtw @Match-Yang

**Comment by hualet** [comment] 2016-04-18 07:38
I think this issue is fixed by someone, can't reproduce it here anymore. @felixonmars

**Closed** 2016-07-08 00:59 UTC
Labels: dock
