### ISSUE TITLE
Strings of translations truncated in many places in Deepin Linux

### ISSUE THREAD

**Issue by Atalanttore** [linuxdeepin/developer-center#3307] opened 2022-07-17 18:34 UTC
In many places in Deepin Linux, the text fields for translated strings are too short, and the text is then truncated.

As an example, here is a screenshot showing a window with the German translation of the Deepin installer. The red framed string is truncated at both the beginning and the end. This is neither beautiful nor easy to read.

![Deepin_20 5_installation_german](https://user-images.githubusercontent.com/628474/179419801-664c41ed-8821-45ec-9bce-a37c1ee7ae7e.png)

**Comment by raspin0** [comment] 2022-07-18 16:37
Installed - Zainstalowano
there's really no shorter translation for Polish
![obraz](https://user-images.githubusercontent.com/39202451/179559907-40db978f-d47e-4f15-b14d-f0f6b0371fd6.png)

**Comment by BLumia** [comment] 2022-07-19 01:22
@babyfengfjx might need to take a look :)

**Comment by babyfengfjx** [comment] 2022-08-04 03:46
Thanks for  your feedback, let's take a look at the issue.

**Comment by SuperEffie** [comment] 2022-08-04 06:33
Thanks for your feedback.
Now that we are planning a new version of the installer, this ability to display logs will be removed. Besides the installer having incomplete display, is there any other place where this is happening? We will also keep an eye on the incomplete text display, and welcome your feedback!

**Comment by raspin0** [comment] 2022-08-04 11:13
> Thanks for your feedback. Now that we are planning a new version of the installer, this ability to display logs will be removed. Besides the installer having incomplete display, is there any other place where this is happening? We will also keep an eye on the incomplete text display, and welcome your feedback!

deepin-album
All photos -> Wszystkie zdjęcia
![obraz](https://user-images.githubusercontent.com/39202451/182833464-be633953-583f-40c4-9d87-47ec9ab97f35.png)

**Comment by Atalanttore** [comment] 2022-08-05 16:40
> Now that we are planning a new version of the installer, this ability to display logs will be removed.

The problem is gone, but there is one less feature.

> Besides the installer having incomplete display, is there any other place where this is happening? We will also keep an eye on the incomplete text display, and welcome your feedback!

There are plenty of places in various Deepin apps where translations are truncated.

**Comment by BLumia** [comment] 2022-08-05 17:12
> There are plenty of places in various Deepin apps where translations are truncated.

Please consider list them here so we can look into these issues. Thanks!

**Comment by raspin0** [comment] 2022-08-11 17:37
Deepin file manager samba share password
Language: Polish
![obraz](https://user-images.githubusercontent.com/39202451/184197593-4fc38678-1602-4c76-955f-4d3f80310dd2.png)

**Comment by SuperEffie** [comment] 2022-08-16 09:33
It seems the problem has been fixed after file manager and album upgrade. But the app store still exists and we'll notify the developers. If the problem is solved, we will inform you here.

**Comment by SuperEffie** [comment] 2022-08-16 09:48
![Zrzut ekranu_dde-file-manager_20220816170607](https://user-images.githubusercontent.com/58986464/184849965-fc3dfcf2-bec5-46b0-b4b4-1bd382552c63.png)
![Zrzut ekranu_deepin-album_20220816170640](https://user-images.githubusercontent.com/58986464/184850041-c93c4ce3-1768-4e86-afe3-4260bc16d97f.png)
As shown in the image above, it seems to be fixed in the file manager and albums.

**Comment by raspin0** [comment] 2022-08-16 16:29
As you can see, there's a workaround to bypass the issue. There's only one string called `Zdjęcia`, which isn't an exact translation to `All Photos` (Wszystkie zdjęcia). The change has been reverted on transifex

**Comment by raspin0** [comment] 2022-08-16 16:41
![obraz](https://user-images.githubusercontent.com/39202451/184933277-69ccd212-f222-4d40-beef-4022a9976662.png)

Deepin album -> Photo info

**Comment by raspin0** [comment] 2022-08-16 16:45
![obraz](https://user-images.githubusercontent.com/39202451/184933782-50c1030f-9418-427c-9382-d0fc879321c9.png)

I think names of modules or applications should be capitalised
Display in file manager -> Display in File Manager

**Comment by raspin0** [comment] 2022-08-16 16:52
![obraz](https://user-images.githubusercontent.com/39202451/184935166-f1db117c-98e0-43a2-90f5-56895962678c.png)

Give more space for error messages in file manager file transfer dialog. As far as I know the issue is also in English

**Comment by raspin0** [comment] 2022-08-16 16:54
![obraz](https://user-images.githubusercontent.com/39202451/184935514-b926748b-97f5-4c3e-81ac-fe279b21f217.png)

**Comment by raspin0** [comment] 2022-08-16 16:57
![obraz](https://user-images.githubusercontent.com/39202451/184935796-e30804e8-fc70-4299-b4b1-867971981ed5.png)

Username -> Nazwa użytkownika. There's no better and shorter translation in Polish. We could workaround the issue to translate Username as User(POL: Użytkownik) which would have basically the same meaning.

**Comment by raspin0** [comment] 2022-08-16 17:12
![obraz](https://user-images.githubusercontent.com/39202451/184937525-805e4b4f-db3a-4f23-b2b0-acc9a50d8b41.png)

Change English translation to more humane format: 
Video CodecID -> Video Codec 
VideoCodeRate -> Video Bitrate or simply Bitrate? 
Proportion -> Proportions

Audio CodeclD -> Audio Codec
Audio CodeRate -> Bitrate 
Audio digit -> Bit Depth? (I'm not sure here)

**Comment by raspin0** [comment] 2022-08-16 17:31
![obraz](https://user-images.githubusercontent.com/39202451/184942313-f1ca752d-2b27-48f5-b51e-7cf46005fc71.png)

Folders generated by deepin apps are untranslated

**Comment by raspin0** [comment] 2022-08-16 17:41
![obraz](https://user-images.githubusercontent.com/39202451/184944146-e5a496ab-0f5f-488d-8454-968d248cd39e.png)

Add space between New Folder and incrementing number

**Comment by raspin0** [comment] 2022-08-25 16:27
![obraz](https://user-images.githubusercontent.com/39202451/186719416-0f237c22-9b88-4b0d-a68e-50ce079a7061.png)

**Comment by WebTimeout** [comment] 2022-09-01 14:29
![image](https://user-images.githubusercontent.com/28079139/187939380-11cfd975-f12e-4b50-b55e-e984b99dcca2.png)
this version 20.7 installation is not fully in portuguese like old 20.6

**Comment by BLumia** [comment] 2022-09-02 02:12
cc @SuperEffie @babyfengfjx

**Comment by SuperEffie** [comment] 2022-09-09 10:19
> ![image](https://user-images.githubusercontent.com/28079139/187939380-11cfd975-f12e-4b50-b55e-e984b99dcca2.png) this version 20.7 installation is not fully in portuguese like old 20.6

This problem does exist when installing in Portuguese. We have submitted it to the developers and will fix it as soon as possible。

**Comment by SuperEffie** [comment] 2022-09-09 10:27
> 

Thanks for your feedback. We have submitted some problems you mentioned  to the developers for repairing.And some suggestions have been submitted to the product manager.
Best wishes!

**Comment by raspin0** [comment] 2022-10-08 15:24
![obraz](https://user-images.githubusercontent.com/39202451/194714923-9e08cf58-1ec0-48cf-afca-07caf0326e6a.png)

Deepin text editor -> Go to line 
Polish language

**Comment by SuperEffie** [comment] 2022-10-10 07:17
> Folders generated by deepin apps are untranslated

Thanks,we've got it and submitted it to developers.The situation that we use Polish is not very often.  You are welcomed to  give us more feedback!

**Comment by SuperEffie** [comment] 2022-11-01 10:02
> ![obraz](https://user-images.githubusercontent.com/39202451/184933277-69ccd212-f222-4d40-beef-4022a9976662.png)
> 
> Deepin album -> Photo info
Now deepin album has been updated to version 5.10.7. You can upgrade it in the App Store and this problem has been fixed.

**Comment by SuperEffie** [comment] 2022-11-01 10:04
> ![obraz](https://user-images.githubusercontent.com/39202451/194714923-9e08cf58-1ec0-48cf-afca-07caf0326e6a.png)
> 
> Deepin text editor -> Go to line Polish language
And our text editor has been updated to version 5.10.39 and this problem also has been fixed.You can try to confirm it.

**Comment by raspin0** [comment] 2022-12-21 21:03
![obraz](https://user-images.githubusercontent.com/39202451/209002215-36965ef8-4eb8-4bf8-8bd0-b7ee6fe9399f.png)

Context menu of scrollbar in notification center doesn't seem to be translated

**Comment by raspin0** [comment] 2023-01-28 15:45
![obraz](https://user-images.githubusercontent.com/39202451/215275776-e7a5e17b-100e-411d-bb44-78310137b70d.png)

There's not enough space for the strings.

**Comment by SuperEffie** [comment] 2023-02-02 06:11
> 
We do not have fixed Polish translators. When external contributors do not provide translations for us, we will present them in English. Would you like to provide us with a translation? Thanks again for your feedback.

**Comment by SuperEffie** [comment] 2023-02-02 06:34
> ![obraz](https://user-images.githubusercontent.com/39202451/215275776-e7a5e17b-100e-411d-bb44-78310137b70d.png)
> 
> There's not enough space for the strings.

We have fed back this problem to the developer, and will reply you here if it is fixed later

**Comment by raspin0** [comment] 2023-02-02 16:41
> > 
> 
> We do not have fixed Polish translators. When external contributors do not provide translations for us, we will present them in English. Would you like to provide us with a translation? Thanks again for your feedback.

I couldn't find these strings through Transifex. On Transifex Polish language is 100% complete. 

> We have fed back this problem to the developer, and will reply you here if it is fixed later

Cool, thanks! :thumbsup:

**Comment by raspin0** [comment] 2023-02-02 16:47
Translation:
```
Scroll here -> Pzewiń tutaj
Top -> Góra
Bottom -> Dół
Page up -> Strona w górę
Page down -> Strona w dół
Scroll up -> Przewiń w górę
Scroll down -> Przewiń w dół
```

**Comment by SuperEffie** [comment] 2023-03-06 09:02
> Translation:
> 
> ```
> Scroll here -> Przewiń tutaj
> Top -> Góra
> Bottom -> Dół
> Page up -> Strona w górę
> Page down -> Strona w dół
> Scroll up -> Przewiń w górę
> Scroll down -> Przewiń w dół
> ```
Thanks,wo got it.

**Comment by raspin0** [comment] 2023-03-16 22:53
![obraz](https://user-images.githubusercontent.com/39202451/225769890-d92b6ab6-b01e-41e0-84ca-6fbc07a17906.png)

Translation doesn't fit in dialog. This prompt appears after trying to delete a file which is too big to be moved into trash.

**Comment by raspin0** [comment] 2023-05-09 21:28
![image](https://github.com/linuxdeepin/developer-center/assets/39202451/e440df72-eba3-4f1c-b48d-d8c93ea48d2e)

Downloader application. The prompt located in Settings -> Monitored links -> HTTPS -> Advanced. There's not enough space for two strings located at the top of the prompt.

**Comment by babyfengfjx** [comment] 2023-05-22 02:16
> ![image](https://user-images.githubusercontent.com/39202451/237224358-e440df72-eba3-4f1c-b48d-d8c93ea48d2e.png)
> 
> Downloader application. The prompt located in Settings -> Monitored links -> HTTPS -> Advanced. There's not enough space for two strings located at the top of the prompt.

@SuperEffie  该问题可以在V23版本尝试复现一下，如果有类似问题，可以提交issue跟进。
@raspin0  Thank you very much for submitting the issue. As version V20.9 and later will no longer receive updates, we will continue to monitor this issue in deepin V23. If you are able to use V23 in the future and encounter any problems, please feel free to submit them. We will close this issue for now and keep an internal record. Thank you again for your attention.

**Closed by babyfengfjx** 2023-05-22 02:16 UTC
Labels: i18n | internationalization and localization, Meta | Task List
