### ISSUE TITLE
deepin-application-manager 1.1.4-1 bug in arch linux 

### ISSUE THREAD

**Issue by Azguard-Cybernetics** [linuxdeepin/developer-center#6662] opened 2023-12-28 23:58 UTC
### SUMMARY | 问题概要

after an update of deepin-application-manager to deepin-application-manager 1.1.4-1 some characters are in chinese

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

```plain
deepin-application-manager 1.1.4-1
```

### STEPS TO REPRODUCE | 复现步骤

fix      deepin-application-manager 1.1.4-1 update

**Comment by BLumia** [comment] 2023-12-29 02:30
Any additional information so we could reproduce?

**Comment by Azguard-Cybernetics** [comment] 2023-12-29 21:38
> Any additional information so we could reproduce? e.g. Which app has this issue? Any screenshot could be very helpful.

will attach a screenshot shortly

**Comment by Azguard-Cybernetics** [comment] 2023-12-29 22:03
Uploading Record_dde-desktop_20231229235937.mp4…

this is a video of the characters

**Comment by Azguard-Cybernetics** [comment] 2023-12-29 22:09
here is a link to a short video https://drive.google.com/file/d/1VBxB0Ler4jz52-z2Y-A8jXXCmV5VaIcg/view?usp=drive_link i tried everything i could think of to fix the issue but the only solution was to block deepin apps and deepin-application-manager from updating.

**Comment by BLumia** [comment] 2023-12-30 06:31
I see.

Please consider install `deepin-launchpad` instead since that one is going to replace `deepin-launcher` in upcoming updates.

As for the application manager translation issue, cc @ComixHe

**Comment by Azguard-Cybernetics** [comment] 2023-12-30 08:25
> I see.
> 
> Please consider install `deepin-launchpad` instead since that one is going to replace `deepin-launcher` in upcoming updates. And you won't need to bloack `deepin-application-manager` from updating as well :)
> 
> As for the application manager translation issue, cc @ComixHe

okay thank you

**Comment by ComixHe** [comment] 2024-01-05 06:02
This is an incorrect behavior of `dde-launcher`, you could try 'dde-launchpad'.

**Comment by BLumia** [comment] 2024-01-05 06:05
I'll close this one for now since `dde-launchpad` is going to replace `dde-launcher` in the next update. Thanks again for reporting the issue :)

**Closed by BLumia** 2024-01-05 06:05 UTC
Labels: triage | need more information
