### ISSUE TITLE
Bluetooth not working.

### ISSUE THREAD

**Issue by Aadi-mone** [linuxdeepin/developer-center#3508] opened 2022-11-28 17:02 UTC
### SUMMARY | 问题概要

I don't see a Bluetooth option on my PC settings or a way to use it, although the device manager shows my Bluetooth adapter and its driver name, I still can't use it.

### STEPS TO REPRODUCE | 复现步骤

1. Buy Lenovo S145
2. Install Deepin
3. Search for Bluetooth
4. there is no Bluetooth so report it on discord, then come back to Github.

### OBSERVED RESULT | 观察到的结果

my pc turns on and I can feel the Bluetooth waves going through my body :) 

### EXPECTED RESULT | 期望的结果

Bluetooth should be shown on the dock or in the settings. I don't see any options to use that.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

![image](https://user-images.githubusercontent.com/87631878/204337623-277a01e3-6062-4aa9-ab8d-c18a15822093.png)

### ADDITIONAL INFORMATION | 额外补充

I use liquid nitrogen to cool my laptop.

**Comment by Aadi-mone** [comment] 2022-12-04 15:11
![image](https://user-images.githubusercontent.com/87631878/205498631-82030331-7399-4033-82fc-23d2afa74f36.png)

**Comment by BLumia** [comment] 2022-12-05 01:30
> 1. Buy Lenovo S145

:joy: That's a costy step. Could you also try provide the output of `hcitool dev` and `rfkill`? Thanks!

**Comment by Aadi-mone** [comment] 2022-12-05 01:58
![image](https://user-images.githubusercontent.com/87631878/205532629-2211233e-1c0f-4733-bf6b-db9b4ba8e699.png)

btw I forgot to mention, my trackpad on this laptop doesn't work too

**Comment by Aadi-mone** [comment] 2022-12-13 13:47
HELLO?

**Comment by BLumia** [comment] 2022-12-13 14:16
cc @babyfengfjx

**Comment by BLumia** [comment] 2022-12-13 14:17
btw I suggest upgrade to v20.8 and see if that fixes your issue.

**Comment by Aadi-mone** [comment] 2022-12-23 06:32
Hi, I have updated deepin to 20.8 and still Bluetooth doesn't work, is there any way to install these drivers manually?

**Comment by Aadi-mone** [comment] 2022-12-23 06:41
with that one more thing comes up, after updating CPU's fan is at full speed even with lower loads
![image](https://user-images.githubusercontent.com/87631878/209285363-cf8474cb-8ebc-4de4-83a5-001e8087ae34.png)
the clock frequency is also high without any big programs running.

**Comment by Aadi-mone** [comment] 2022-12-25 12:15
@BLumia ??? anyone here? why is it taking too long just to guide me to install a Bluetooth driver??

**Comment by BLumia** [comment] 2022-12-25 13:47
Since your bluetooth device is unblocked so it's not likely a driver issue. I'm not an expert about hardware issue troubleshooting and I also don't use any bluetooth device on my PC, so all I can do is tagging related workmate and see if they can help.

Sadly, in China we are currently facing serious COVID issue in recent days. Most of our workmates (including the one I tagged above) got COVID and are resting at their home, so sorry we're not able to response to troubleshooting threads in a timely matter.

In the meantime, I personally suggest you google about your issue so you might get some related results by yourself. Or you can also consider join a deepin related discussion group like <https://t.me/deepin> and see if there are people who are good at hardware troubleshooting.

**Comment by Aadi-mone** [comment] 2022-12-26 11:46
uh, how did you know my Bluetooth device was unblocked? and I'm here from discord 🤣 I have already googled so many ways to fix this issue, of course, there are many posts but none of them helped xD anyway, I'll try asking for help by telegram.

thank you and take care mate!

**Comment by BLumia** [comment] 2022-12-26 16:22
> how did you know my Bluetooth device was unblocked?

From the output you provided above https://github.com/linuxdeepin/developer-center/issues/3508#issuecomment-1336623677

> thank you and take care mate!

Thanks, you too :)

**Comment by babyfengfjx** [comment] 2023-01-09 02:56
To some internal test user's consultation, temporarily not found to have such problems with the device, not too sure why it happens, I wonder if you can reinstall the system to see if it is normal?

**Comment by Aadi-mone** [comment] 2023-01-27 18:02
It never worked on my Laptop, instead I installed Deepin on my desktop computer and removed Deepin from my laptop.

**Comment by babyfengfjx** [comment] 2023-02-08 05:55
That is not adapted to your laptop model, very sorry not adapted to the hardware, at present deepin may only be compatible with most devices better, there will be hardware compatibility problems with some devices.

**Comment by Aadi-mone** [comment] 2023-02-15 03:01
yeah, that's alright. It's working on my desktop, that's enough. Thank you :)

**Comment by babyfengfjx** [comment] 2023-02-15 10:15
I sincerely apologize for the inconvenience caused by the compatibility issue with your laptop. We are committed to providing a better user experience in our upcoming releases. As for the current issue, we will need to close it for now. However, please do not hesitate to reach out if you have any other questions or concerns during your future use. We are always here to help.

**Closed by babyfengfjx** 2023-02-15 10:15 UTC
