### ISSUE TITLE
Deepin File Manager does not automount the internal hard drive on startup.

### ISSUE THREAD

**Issue by laichiaheng** [linuxdeepin/developer-center#521] opened 2018-05-16 10:52 UTC
I have to open Deepin File Manager twice to make it work

**Comment by BLumia** [comment] 2018-05-16 11:50
Hi,

Not quite sure what's your means but dde-file-manager itself doesn't auto-mount any external devices when you are just starting a new dde-file-manager instance (i.e. open that program). Any available external devices will displayed in computer view (computer:///) and the left sidebar, when you manually click these item, then that device will be auto-mounted (triggered by your click action, not when you launching a dde-file-manager instance).

Feel free to let us know if you still have any questions.

**Comment by laichiaheng** [comment] 2018-05-16 12:43
@BLumia If you need to manually click it to mount the device, it is not auto-mount, it is manual-mount
![deepinscreenshot_select-area_20180516204005](https://user-images.githubusercontent.com/9532105/40117403-74f52e62-5949-11e8-8adb-d9ad05a83b4e.png)
It worked before, but it is broken now.

**Comment by BLumia** [comment] 2018-05-16 13:11
Could you please provide more details like which distro are you using and which version of dde-file-manager you are using? Posting log file may also helps.

> The 1TB hard drive was mounted automatically in the past, but it isn't now.

Did you do anything like upgrading packages or any other action may tend to the result?

btw a new release of dde-file-manager will comes out in the upcomming day(s), you can also check if the newer release has already fixed the problem or not.

**Comment by BLumia** [comment] 2018-05-17 01:05
I've checked the behavior of auto-mount and it works well on my machine, so please provided a log file will be much more helpful to detect where the problem is.

btw, the auto-mount function also requires dde-dock module to work, so you can try restart the dde-dock program and check if that caused the problem.

cc @zccrs .

**Comment by laichiaheng** [comment] 2018-05-17 13:39
@BLumia What log should I provide to solve the problem?

**Comment by BLumia** [comment] 2018-05-17 13:44
Log file path `~/.cache/deepin/dde-file-manager/dde-file-manager.log`

You can delete the already existed log file first and then launch `dde-file-manager`, reproduce the problem and then attach the generated log file to here.

**Comment by laichiaheng** [comment] 2018-05-17 13:50
[dde-file-manager.log](https://github.com/linuxdeepin/developer-center/files/2013385/dde-file-manager.log)

**Comment by BLumia** [comment] 2018-08-12 04:39
This issue should be fixed in v1.7 release. Please check if upstream updated the dde-file-manager package in the distro which you are using. Feel free to reopen this issue if you have any future questions.

**Closed by BLumia** 2018-08-12 04:39 UTC

**Comment by SiamSami** [comment] 2019-02-18 08:11
In Archlinux, you have to do some stuff to automount hard drive. Watch this video,
https://www.youtube.com/watch?v=6TPj6L7JAq0
