### ISSUE TITLE
dde-desktop permanently using 12% cpu

### ISSUE THREAD

**Issue by DasJott** [linuxdeepin/developer-center#299] opened 2017-06-07 10:11 UTC
Why is the dde-Desktop permanently using 12% cpu? No matter what I do.

Using Arch Anywhere with newest Deepin.

**Comment by hualet** [comment] 2017-06-08 01:09
I think this is not a common issue?
@felixonmars @jouyouyun @zccrs

**Comment by DasJott** [comment] 2017-06-08 06:18
Fresh start today and around 12% right form the start. Without doing anything.

**Comment by hualet** [comment] 2017-06-08 06:32
@DasJott You can help us with:

1.  provide a copy of ~/.cache/deepin/dde-desktop/dde-desktop.log
or 
2. install ltrace tool, run  ltrace -Cc -p DDE_DESKTOP_PID in your terminal for a while  and hit Ctrl-C, copy the output and paste it here.

Thanks.

**Comment by DasJott** [comment] 2017-06-08 06:50
My system while doing nothing. Just started Franz and Chrome Browser and this is what the 8 CPUs are doing: [CPUs.zip](https://github.com/linuxdeepin/developer-center/files/1060131/CPUs.zip)

The dde-desktop.log is constantly pumped up with one single message:

Warning: "Für den Typ »video/x-rle, layout=(string)quicktime, depth=(int)16, width=(int)450, height=(int)348, framerate=(fraction)25/1, pixel-aspect-ratio=(fraction)1/1« ist kein Decoder vorhanden."

In english:
Warning: No decoder available for type: »video/x-rle, layout=(string)quicktime, depth=(int)16, width=(int)450, height=(int)348, framerate=(fraction)25/1, pixel-aspect-ratio=(fraction)1/1«

That seems to be strange.


Will install that trace tool soon and paste again here.

**Comment by felixonmars** [comment] 2017-06-08 06:51
~6% here. There's nothing in the logs. Here's the ltrace output:

```
% time     seconds  usecs/call     calls      function
------ ----------- ----------- --------- --------------------
  9.31    0.002753         458         6 QAbstractScrollArea::viewport() const
  8.71    0.002575         429         6 QWidget::hasFocus() const
  8.39    0.002479         413         6 QBrush::~QBrush()
  5.47    0.001617         539         3 QWidget::update()
  4.90    0.001450         483         3 QTimer::setInterval(int)
  4.52    0.001335         445         3 QAbstractItemView::model() const
  4.48    0.001324         441         3 QPainter::QPainter(QPaintDevice*)
  4.36    0.001289         429         3 QColor::setRgb(int, int, int, int)
  4.33    0.001279         426         3 QAbstractItemView::selectionModel() const
  4.30    0.001270         423         3 QMetaObject::cast(QObject*) const
  4.29    0.001267         422         3 QBrush::QBrush(QColor const&, Qt::BrushStyle)
  4.27    0.001261         420         3 QPainter::setBrush(QBrush const&)
  4.25    0.001255         418         3 QAbstractItemView::state() const
  4.19    0.001239         413         3 QPainter::~QPainter()
  4.12    0.001218         406         3 QFont::~QFont()
  4.06    0.001200         400         3 QIcon::~QIcon()
  4.04    0.001195         398         3 QStyleOption::~QStyleOption()
  4.03    0.001191         397         3 QListData::detach(int)
  4.01    0.001184         394         3 QLocale::~QLocale()
  3.99    0.001181         393         3 QListData::dispose(QListData::Data*)
------ ----------- ----------- --------- --------------------
100.00    0.029562                    69 total
```

**Comment by DasJott** [comment] 2017-06-08 06:58
```
^C% time     seconds  usecs/call     calls      function
------ ----------- ----------- --------- --------------------
 67.76    1.983746         289      6841 QArrayData::deallocate(QArrayData*, unsigned long, unsigned long)
  3.74    0.109584         267       410 QMetaObject::cast(QObject*) const
  3.67    0.107406         268       400 operator<(QString const&, QString const&)
  2.53    0.073978         264       280 QBrush::~QBrush()
  2.50    0.073243         266       275 QBrush::QBrush(QColor const&, Qt::BrushStyle)
  2.05    0.059926         266       225 QPalette::setBrush(QPalette::ColorGroup, QPalette::ColorRole, QBrush const&)
  1.69    0.049620         268       185 QAbstractItemView::model() const
  1.64    0.048021         266       180 operator delete(void*)
  1.64    0.047979         266       180 QColor::setNamedColor(QLatin1String)
  1.63    0.047834         265       180 DFileViewHelper::parent() const
  0.91    0.026593         268        99 QListData::dispose(QListData::Data*)
  0.86    0.025104         264        95 QAbstractItemView::selectionModel() const
  0.81    0.023785         264        90 QItemSelectionModel::isSelected(QModelIndex const&) const
  0.81    0.023764         264        90 DFileSystemModel::fileInfo(QModelIndex const&) const
  0.81    0.023732         263        90 QRect::intersects(QRect const&) const
  0.81    0.023670         263        90 QUrl::~QUrl()
  0.74    0.021768         272        80 QListData::append()
  0.50    0.014673         271        54 QListData::detach_grow(int*, int)
  0.45    0.013253         265        50 QColor::setRgb(int, int, int, int)
  0.43    0.012482         277        45 DFileSystemModel::index(DUrl const&, int)
  0.42    0.012228         271        45 QItemSelectionModel::selectedIndexes() const
  0.42    0.012185         270        45 DUrl::toLocalFile() const
  0.41    0.012134         269        45 QArrayData::allocate(unsigned long, unsigned long, unsigned long, QFlags<QArrayData::AllocationOption>)
  0.41    0.012075         268        45 QAbstractItemView::itemDelegate() const
  0.41    0.012071         268        45 DFileSystemModel::getUrlByIndex(QModelIndex const&) const
  0.41    0.011891         264        45 DUrl::fromLocalFile(QString const&)
  0.41    0.011873         263        45 QColor::QColor(Qt::GlobalColor)
  0.40    0.011793         262        45 QRegion::rects() const
  0.10    0.002991         299        10 QAbstractScrollArea::viewport() const
  0.09    0.002743         274        10 QWidget::hasFocus() const
  0.07    0.002036         407         5 QWidget::update()
  0.06    0.001639         327         5 QTimer::setInterval(int)
  0.05    0.001571         314         5 QPainter::QPainter(QPaintDevice*)
  0.05    0.001322         264         5 QAbstractItemView::state() const
  0.04    0.001316         263         5 QStyleOption::~QStyleOption()
  0.04    0.001316         263         5 QPainter::setBrush(QBrush const&)
  0.04    0.001306         261         5 QPainter::~QPainter()
  0.04    0.001284         256         5 QLocale::~QLocale()
  0.04    0.001279         255         5 QIcon::~QIcon()
  0.04    0.001277         255         5 QFont::~QFont()
  0.02    0.000623         311         2 QWidget::enterEvent(QEvent*)
  0.02    0.000550         275         2 QWidget::leaveEvent(QEvent*)
------ ----------- ----------- --------- --------------------
100.00    2.927664                 10373 total
```

**Comment by hualet** [comment] 2017-06-08 06:59
@DasJott I think dde-desktop is trying to create thumbnails for video files on your desktop, and it fails and repeats to do the same thing, you can try to move them to other places?

**Comment by DasJott** [comment] 2017-06-08 07:15
@hualet Yeah it does that message every 20-30ms. On the desktop is no video file. There was a mp4 file but I deleted that one. Anyway it had a thumbnail ;)

**Comment by hualet** [comment] 2017-06-08 07:22
@DasJott Sorry, video/x-rle is a type of animated picture file or what, I'm not sure, but please find it and try to move it to another place.

**Comment by hualet** [comment] 2017-06-08 07:24
@DasJott try this: find ~/Desktop | xargs file --mime-type

**Comment by DasJott** [comment] 2017-06-08 07:27
There is no picture file on my desktop. There is a script and two plain text files and two chrome links.

**Comment by DasJott** [comment] 2017-06-08 08:18
I tried the find command with a grep for the issued type, but nothing was found.

**Comment by zccrs** [comment] 2017-06-08 08:21
Thank you feedback, We have found the cause of the bug.

**Comment by DasJott** [comment] 2017-06-08 08:37
@zccrs Is it hard to fix or will it be fixed soon?

**Comment by zccrs** [comment] 2017-06-08 08:46
@DasJott Fixed soon.

**Comment by DasJott** [comment] 2017-06-08 13:15
You really have to love Deepin to use it even though the fan is running on full speed and the harddrive is getting fuller and fuller if you do not delete the 20MB log files once in a while... ;)

**Comment by hualet** [comment] 2017-06-08 13:25
The log files will be rotated.

**Comment by DasJott** [comment] 2017-06-08 14:09
![deepinscreenshot20170608154027](https://user-images.githubusercontent.com/6298761/26932786-e1e615a6-4c64-11e7-9f31-199d95227afb.png)

**Comment by hualet** [comment] 2017-06-08 14:21
@DasJott Have you installed the gstreamer plugins? you can try to install them and see if the CPU usages get lower.

**Comment by hualet** [comment] 2017-06-08 14:35
Or you can wait for a new version of dde-file-manager/dde-desktop which should've fixed the problem. I just received a message from @felixonmars that he's building the new version.

**Comment by DasJott** [comment] 2017-06-08 14:44
I only had the ugly ones left to install, all other "versions" have already been installed.
But that didn't make the trick. Same thing, still.

I'm really looking forward to the fix! :)  Big THANKS to you!

**Comment by felixonmars** [comment] 2017-06-08 14:51
You may also try to install gst-libav :/

**Comment by DasJott** [comment] 2017-06-08 14:56
Yes, THAT actually did something! The system is runnign quietly again! Thank you!
I was already searching, but didn't know, where to get the missing codec... (whoever that needs).

**Comment by hualet** [comment] 2017-06-08 15:05
Great !!! 
I'll close this issue for now. @DasJott you can reopen it if you get this issue again.

**Closed by hualet** 2017-06-08 15:05 UTC

**Comment by JulianLai** [comment] 2017-06-08 15:06
Antergos user confirmed this issue, and also confirmed that it had been solved by updating the new version of dde-file-manager.

**Comment by DasJott** [comment] 2017-06-08 15:38
There was no update available by then. gst-libav did the trick for now. Am at home now and will try the update of the file manager.

**Comment by JulianLai** [comment] 2017-06-08 16:18
@DasJott Maybe you can change the mirror.

**Comment by DasJott** [comment] 2017-06-09 07:28
Arch Anywhere uses the Arch repos and AUR. Everything okay. This is all about my Laptop at work and I simply was home already, missing the update ;)
