### ISSUE TITLE
Screenshots show selection UI in final image

### ISSUE THREAD

**Issue by benpaulsen-qut** [linuxdeepin/developer-center#2681] opened 2021-04-06 06:35 UTC
Hi there,
I have noticed this issue since I started using deepin 20, but I am only now reporting it since it hasn't been fixed yet.

Basically, when you take a screenshot with the selection tool (on either a window or custom select) the dotted line surrounding the selection and sometimes the selection drag points also show up in the final image when they should not. The UI becomes more noticeable on smaller images, but is clearly visible on basically every selection screenshot (I have included an example with annotations).

![example](https://user-images.githubusercontent.com/64248614/113668435-9079fe00-96f5-11eb-8319-03dc1031a029.png)

I am using Deepin 20.2 (but the issue has existed since Deepin 20) with screen recorder version 5.9.3-1 according to apt.
Im not sure if it matters, but I am also using 2 monitors with an Nvidia RTX 2080 and the latest driver version 460.

**Comment by BLumia** [comment] 2022-04-02 07:47
Hi, does this still happen in the most recent release (we are on v20.5 now)?

**Comment by SuperEffie** [comment] 2022-04-12 07:00
Thanks for your feedback.Due to no reply for a long time,I close this issue now.Our system has been updated to version 20.5 and the Screen Capture has been updated to version 5.10.15. This issue seems to have been fixed and we cannot reproduce it. If your issue still exists on the latest version,you can apply to reopen the issue.Then we will help to deal with it.

**Closed** 2022-04-12 09:47 UTC
Labels: project: deepin-screen-recorder
