### ISSUE TITLE
File Manager : Disk renaming forcing named to uppercase ... needs to be corrected for all case names !

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#990] opened 2019-03-13 06:02 UTC
Hi,

The option to rename disks(partitions) is a good feature but its forcing the names to all 'uppercase' ... i guess this needs to be corrected to handle 'any case' the user intends to name their disks(partitions) as !

Eg. ... I prefer to name a disk 'videoTuts' ... but the current implementation is forcing it to 'VIDEOTUTS' ... which i don't like ...

**Comment by BLumia** [comment] 2019-03-13 06:40
Cannot reproduce here, maybe you enabled the Caps Lock by mistake?

**Comment by keybreak** [comment] 2019-03-13 07:09
Also can't reproduce it

btw, is there any easy way to rename system drive?)

**Comment by BLumia** [comment] 2019-03-13 07:25
> is there any easy way to rename system drive?

Enter a livesystem and rename partition label via any partition management software like [KDE Partition Manager](https://kde.org/applications/system/kdepartitionmanager/), [GNOME Partition Editor](https://gparted.org/) or the dde-file-manager?

But FYI under dde-file-manager, the root partition will always display its name as "System Disk", whatever you labeled it another name or not.

**Comment by keybreak** [comment] 2019-03-13 07:37
> the root partition will always display its name as "System Disk"

Yep, that's what i was asking, should be changed i guess.
Because i was testing other languages, some of them are longer like russian for example, so it pushes the Volume line down, which ain't cool at all..

**Comment by keybreak** [comment] 2019-03-13 07:45
Maybe better option would be use 'System Disk' defaults unless changed?
It won't change loger languages behaviour, but at least would be a very user-friendly way (even though you still have to use Live)

**Comment by BLumia** [comment] 2019-03-13 07:56
Maybe you should open another issue for that feature request :)

**Comment by keybreak** [comment] 2019-03-13 08:04
Sure, also followed by lot of bugs that i've found with other languages due to their differences in number of characters :)

**Comment by keybreak** [comment] 2019-03-13 09:56
https://github.com/linuxdeepin/developer-center/issues/992

**Comment by aiamuzz** [comment] 2019-03-14 09:58
please find the screen capture in the process of renaming ...

![deepin-screen-recorder_Select area_20190314152647](https://user-images.githubusercontent.com/3283676/54347836-cc088200-466d-11e9-951e-7be06a72ee41.gif)

**Comment by keybreak** [comment] 2019-03-14 10:01
Hmm...
One quick question, try to rename it first to something very different, like TEST, and then try videoTuts

**Comment by BLumia** [comment] 2019-03-14 11:28
Is that a FAT32 format partition?

**Comment by aiamuzz** [comment] 2019-03-27 15:57
> Is that a FAT32 format partition? [(info)](https://superuser.com/questions/137569/setting-a-mixed-case-volume-label-for-a-fat32-drive-on-windows)

@BLumia ... yes ... its filesystem is 'vfat' ...

**Comment by BLumia** [comment] 2019-03-28 01:49
> yes ... its filesystem is 'vfat' ...

So that is a limit of the file system itself, not a bug of the file manager. Google it for more details.

Closing.

**Closed by BLumia** 2019-03-28 01:49 UTC
Labels: info needed, need confirm
