### ISSUE TITLE
[Serious] Wrong disk size: used / free / copy misscalculations & math errors

### ISSUE THREAD

**Issue by keybreak** [linuxdeepin/developer-center#1149] opened 2019-05-03 15:07 UTC
## Describe the bug
All size calculations in Deepin is full of sh*t and need to fix the math universally.

sdf BACKUP 2 disk formatted to ext4 / gpt:
- Computer reports:
2600 G of 2750 G used
- Disk - Properties reports:
2,7 TB used / 149,5 GB free
- Select all files on drive - Properties:
2,5 TB used

lsblk as only reliable source reports:
2,6 T used of 2,7 T

Some of those calculations telling the truth, and rest are full of sh*t.

And worst part - it is absolutely impossible to actually get what's actual capacity of drive and what can be transferred.

By all accounts on this screenshot below this drive have AT LEAST 150-200 Gb of free space, which ain't small amount at all.

Guess what happens when you try to copy just 11 Gb file?
Yes, copy dialog reporting no free space!

## To Reproduce
1. Actually use OS / DE
2. Probably test most basic operations, without breaking them in the future.

## Expected behavior
- Use universal bug-free format for math **EVERYWHERE**, especially in copy dialog free-space restrictions.
- Use universal sensible human readable format everywhere:
2.75 TB
149.5 GB
- Hopefully not mix up bits and bytes in the process of any calculation.
- Immediately tell user if copy operation will fail due to lack of space (even though all of other counters say there's loads of free-space left), instead of showing this warning 6 hours later, after whole drive copy failed in the end and it's impossible to determine what's actually left to copy, so the only viable option is to start over and **try to guess** what's suppose to be free space left by excluding some files.
- Not wasting 16 hours of anyone's life on 3 consequent attempts of backup in order not to loose any files and actually copy them, because it's absolutely impossible to figure out how much of free space copy operation decides to block file transfer on!

No comments.

## Screenshots
![Image of Yaktocat](https://i.imgur.com/k1zWFPh.png)

## Enviroments:
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.0.9-2-MANJARO
Shell: bash
DE: Deepin 15.10
WM: Deepin WM
WM Theme: deepin
GTK Theme: deepin [GTK2/3]
Icon Theme: deepin
compiler: gcc 8.3.0
tk: Qt 5.12.3
dm: LightDM

### Distro & Version
All distros / up to date

### Related package version
deepin-file-manager  1:4.8.3-1

### Additional context
As i've said before, now i have zero motivation to help testing / improving something, that was controlled ruined for months to come by unnecessary rush of 15.10 updates extremely raw deepin-kwin, very bad overall testing lately and insane amount of bugs.

But this...
Let's just say i have a lot of pity for innocent users who will actually encounter this situation on most basic operations and waste insane amounts of time for something, that just work on any Linux distro / DE for literally ages.

And this is not even scratching a surface of serious bugs that should be fixed without introducing extreme amounts of new ones by pushing something raw & not fixing test process before just ruining everything else even worse.

**Comment by keybreak** [comment] 2019-05-14 11:52
@BLumia 
Any news on this?

This one and also tons of segfaults / coredumps in other issues mentioned last few weeks - not something that could be just forgotten & buried by some minor stuff / feature requests.

**Comment by BLumia** [comment] 2019-05-15 01:40
These data are basicly from GIO so nothing can be done from the file manager side. You should get the very same result from `gio info`, and sorry I cannot read Russian so I'm not sure what did you means *error* from the screenshot.

The `2600/2750 G` display can be easily fixed, will fix it later. Selecting all file and see the result may not match the one you see on disk property menu, since filesystem itself may allocate some space to save metadata like inode and etc.

---------------

BTW I really want to point out that, we do really like to help the community to build better software, but please just do **NOT** treat us like free-of-charge tech support and order us to do blah blah. We both got limited time and resource to work on all these project, so if you can help us fix bug, patches via Pull Requests are always welcome, if not, fire a bug with steps to reproduce is also pretty good for us too. We will look into the reported bugs once we have time / resource, and if we confirmed and associated the bug, we'll fix it and release a new version after next release cycle.

Bug, sometimes, cannot be fixed timely since associating a bug is not as easy as found the bug, and fix a bug also need a proper way to do. Talk is cheap, so just please do *not* yelling us to fix some bug. We will do it once we can do, if we cannot do it timely, we also hope other community people can give us their hands, and we also would love to help peoples if they want to help community but don't know what/how to do.

**Comment by BLumia** [comment] 2019-05-15 03:19
Found out that the `XXXX/XXXX G` a designed behavior.

https://github.com/linuxdeepin/dde-file-manager/blob/0650f690e7adfe2d2d6c9d9d775048b9633682a5/dde-file-manager-lib/shutil/fileutils.cpp#L442-L450

Consider update this behavior? @wangjia12

**Comment by wangjia12** [comment] 2019-05-15 05:53
https://github.com/linuxdeepin/internal-discussion/issues/1593

**Comment by keybreak** [comment] 2019-05-15 08:02
@BLumia 
> and sorry I cannot read Russian so I'm not sure what did you means error from the screenshot.

This is actually the root of the main problem, to quote myself, for all described circumstances in this issue:
> And worst part - it is absolutely impossible to actually get what's actual capacity of drive and what can be transferred.

> By all accounts on this screenshot below this drive have AT LEAST 150-200 Gb of free space, which ain't small amount at all.

> Guess what happens when you try to copy just 11 Gb file?
Yes, **copy dialog reporting no free space**!

I have gave enough precise information describing bug (at the moment i was testing russian locale to take screenshot in the process of 5+ hours of copy - so used this screenshots as proof, but still described everything up there in text).

Copy dialog restricting actual space - is the main problem, incorrect designed behavior of reporting space is just cosmetics (but i suspect it could probably be connected).

I don't know how to put it better in words, it's all in issue.

**Comment by BLumia** [comment] 2019-05-15 08:12
That may probably be a bug of copy-move dialog/model, cc @zccrs . The reproduce steps you provided doesn't helps, though.

So if I understand correctly, this issue can be devided to two sub-issue:

 1. On computer view, the indicator display file size greater than 1024GiB still in `G` format.
 2. File copy failed but you still have enough spaces.

Correct?

**Comment by keybreak** [comment] 2019-05-15 08:21
@BLumia 
I guess, yeah.

Something like that:
1. The main operation (backup of whole disk) failed, so i had to skip rest of the files, and check why it happened, because it shouldn't.

2. By all available methods to my knowledge:
   - Computer reports
   - Disk - Properties reports
   - Select all files on drive - Properties
   - lsblk
   etc...

Those reported there a lot of free space left, to summ up, something like: 150-200 Gb of free space

3. So ok, i've decided to test it out, tried to copy file of 11 Gb, and copy-move dialod/model was unable to do this saying that disk have no free space, and this was clearly not the case.

____
I'm not sure how you can test / reproduce it (maybe it only happens on huge disks like mine, because of some math error in calculating Tb?).

Destination disk is:
WD Caviar red WD30EFRX \| 7200rpm, 64Mb, SATA 3, 3Tb
When formatted to gpt / ext4, as you see it's ~2.7 T

**Comment by BLumia** [comment] 2019-05-15 08:32
> I'm not sure how you can test / reproduce it (maybe it only happens on huge disks like mine, because of some math error in calculating Tb?).

Me either, will look into this issue later, but i guess it probably is not caused by calc error, the copy-move dialog will always display the last given error text if I remember correctly. @zccrs may know more details about how copy-move module works.

btw, you can use deepin-clone or clonezilla to do backup job, or use tools like free-file-sync to keep your files sync well between your storage devices.

**Comment by keybreak** [comment] 2019-05-15 08:38
> the copy-move dialog will always display the last given error text if I remember correctly

Yes this is correct, and btw this is also part of problem in case of this bug, because to quote myself from expected behavior:

> Immediately tell user if copy operation will fail due to lack of space (even though all of other counters say there's loads of free-space left), instead of showing this warning 6 hours later, after whole drive copy failed in the end and it's impossible to determine what's actually left to copy, so the only viable option is to start over and try to guess what's suppose to be free space left by excluding some files.

Not sure if it's possible or doable, but this would at least saved time and brain cells of users in case of such kind of failure...

> btw, you can use deepin-clone or clonezilla to do backup job, or use tools like free-file-sync to keep your files sync well between your storage devices.

Sure, and i've ended up just using terminal, which worked...
But that beats the purpose of having Deepin at all then, still better to use bug-free file manager in my opinion)

**Comment by keybreak** [comment] 2019-05-15 09:32
@BLumia 
Considering your rant about bur-report / help ethics - can't speak for anyone else, but we both was doing pretty good so far until some major failures considering testing and kwin-rush lately.

I myself was completely demoralized with 0 feedback and deliberately making situation worse - so it is absolutely not clear for me if it's worth continuing detailed reproducible bug-reports at all.

> Bug, sometimes, cannot be fixed timely since associating a bug is not as easy as found the bug, and fix a bug also need a proper way to do. Talk is cheap, so just please do not yelling us to fix some bug. We will do it once we can do, if we cannot do it timely, we also hope other community people can give us their hands, and we also would love to help peoples if they want to help community but don't know what/how to do.

Nobody sane would argue that and rush you if it was clear what's going on (on contrary there are a lot of people asking to slow down the rush and reduce bugs / improve testing).

So let's be clear:
1. In this particular case - bug is serious, and i was waiting for **any** kind of reaction for 12 days. In my perspective you've missed it completely and was taking care about much more minor issues / feature requests in upstream.

2. That's why i've mentioned you here, to see if you're aware of it at all, doesn't seem to be the case before that. So i'm sorry if that wasn't appropriate way to do this - what should one do next time?

3. Maybe you should always use some tags (like help wanted / need confirm) or something to mark that issue at least have been read and considered, so bug-reporters should at least know that their work is not thrown out?

4. I myself can't make pull request / fix bugs since i don't know C / C++ / Go, but i know people who will and can help directly. For example, when you've asked for help here https://github.com/linuxdeepin/developer-center/issues/889#issuecomment-483974079 - took me just one message on manjaro forum, and 5 minutes from this guy to find cause of problem - which now should be easy to fix.

5. So if you really want community to actually help - it's very easy to do by not letting people down in complete silence and clearly expressing needs / struggles that needs to be taken care of. I could help spread the word for pull-requests / help needs, if you're up for this. But of course no one knows your software better than you, so this part is crucial.

**Comment by BLumia** [comment] 2019-05-15 10:11
> Nobody sane would argue that and rush you if it was clear what's going on (on contrary there are a lot of people asking to slow down the rush and reduce bugs / improve testing).

Sometimes I think if there is a community fork of DDE would be quite good, there are a bunch of reason we release 15.10 in a hurry (actually 15.10 got delayed twice internally), a main reason is the enterprise repo / codebase migration, so we got very limited time working on that release (as you can see we still very busy these days). We are sorry about it bring some bad experience but the release itself doesn't as bad as you imaged (for example, something breaks we find out it is because of the repo changed to debian stable, not because 15.10 codebase). Community fork will probably comes with much less pressure from enterprise user, project management deadline and etc.

> In this particular case - bug is serious

Yep, all bugs are serious, and we also take all bugs seriously. But associate / fix bug is not as easy as you may image, get time processing/filtering issue from all of the places will also requires time.

> Maybe you should always use some tags (like help wanted / need confirm) or something to mark that issue at least have been read and considered, so bug-reporters should at least know that their work is not thrown out?

Yep, I do that, but I only familiar on a few project, sometimes I personally cannot make sure which componment caused a issue, so I will leave that issue as-is and wait for other maintainer dispatch the issue. Sometimes a person who does much more familiar with some specific problem can solve the problem much faster.

> ...and 5 minutes from this guy to find cause of problem - which now should be easy to fix.

Patches are welcome.

Maybe we need a issue/thread to discuss problem like these generic discussion. since it's off-topic from this issue and what we discussed cannot be gathered for further discussion. I personally really would like to help and I just hope you guys understand if we cannot response all issue timely. Sorry about that.

**Comment by SiamSami** [comment] 2019-05-25 15:51
@keybreak Have you tested it with other file managers?

**Comment by keybreak** [comment] 2019-05-25 16:00
@SiamSami 
If you mean copy mechanism - no, but copy through terminal - yes - it works fine under same circumstances...

So i assume it's exclusive bug to deepin-file-manager.

**Comment by SiamSami** [comment] 2019-05-25 16:05
@keybreak I mean, have you tested if other file managers report the same wrong info?

**Comment by keybreak** [comment] 2019-05-25 16:10
Oh, those that i've tested before using Deepin i don't think had same wrong info in different places...

I've used Ubuntu / Gnome / KDE / Mint / XFCE and haven't noticed any obvious differences.

**Comment by SiamSami** [comment] 2019-05-25 16:19
@keybreak I think it's a problem with `gio` instead. Here's a photo from Nautilus file manager.
![DeepinScreenshot_select-area_20190525221850](https://user-images.githubusercontent.com/33563064/58372127-1abe7c00-7f3b-11e9-9dcb-ed3c6bf2f3c0.png)


**Note: Deepin file manager and Nautilus file manager both use `gio` and both report wrong information.**

**Comment by SiamSami** [comment] 2019-05-25 16:40
By the way, I don't think there's anything wrong after all.
If you right-click and select properties, then it shows you "Total space" and "Free space".
"BACKUP 2"'s "Total space" is 2.7 TB and that is correct.
The "Free space" is 149.5 GB.
So, the used space is (2750-149.5) = 2600.5 or ~2.6 TB.
Correct me if I'm wrong.

**Comment by keybreak** [comment] 2019-06-16 00:12
@BLumia 
On uniformity of disk size in different places part of this problem, i've noticed you made some changes to Computer when showing T (which is integer now), it makes even less sense:

![image](https://user-images.githubusercontent.com/47599989/59557421-48e72700-8fe2-11e9-804c-20a171c8a74a.png)

Coz in reality it's something like:
1.54 TB / 3.65 TB


@SiamSami 
Differences in 3 places mentioned differed from 2.5 to 2.7 Tb, so in some cases your math is correct, in some don't...Which leads to bigger problem on copy dialog.

**Comment by BLumia** [comment] 2019-06-16 07:51
> @BLumia
> On uniformity of disk size in different places part of this problem, i've noticed you made some changes to Computer when showing T (which is integer now), it makes even less sense:
> 
> ![image](https://user-images.githubusercontent.com/47599989/59557421-48e72700-8fe2-11e9-804c-20a171c8a74a.png)
> 
> Coz in reality for STORAGE 1 it's something like:
> 1.54 TB / 3.65 TB
> 
> So it's impossible to judge...
> 
> @SiamSami
> Differences in 3 places mentioned differed from 2.5 to 2.7 Tb, so in some cases your math is correct, in some don't...Which leads to bigger problem on copy dialog.

That can be easy to fix, would like to fix it later, or patch welcome :)

btw, you can always create a new issue for a certain problem (instead of a big one contains a lots of issues), and that can make issue tracking much more clearly to do.

**Comment by BLumia** [comment] 2019-06-25 07:09
> Differences in 3 places mentioned differed from 2.5 to 2.7 Tb, so in some cases your math is correct, in some don't...Which leads to bigger problem on copy dialog.

Update:

Just for your info there will be a design change for the computer view and here is a (design) preview :)

![image](https://user-images.githubusercontent.com/10095765/60076763-f254b800-975a-11e9-828f-cd7271144707.png)

**Comment by keybreak** [comment] 2019-06-25 11:03
Well, if you ask me design is the last thing that need to change in Deepin (if at all), this particular problem is more about numbers, rather then design...

But thx for info anyway

**Comment by BLumia** [comment] 2019-06-26 03:45
The new design will also change the number display format so we can always display in `XXX.Y GB` format since we have larger place to display number. So we do no need to worry about if the number string take too width.

**Comment by SiamSami** [comment] 2019-06-26 13:26
@BLumia Looks pretty nice to me.

**Comment by keybreak** [comment] 2019-07-13 18:44
@BLumia 
That's pretty hardcore size difference, if i'm not missing anything..

![image](https://user-images.githubusercontent.com/47599989/61175393-45ca6100-a5b7-11e9-8506-f14724b5c320.png)

**Comment by BLumia** [comment] 2019-07-14 12:49
Since this number is [almost directly from `QStorageInfo`](https://github.com/linuxdeepin/dde-file-manager/blob/master/dde-file-manager-lib/dialogs/propertydialog.cpp#L986), try install [`pyqt5`](https://www.archlinux.org/packages/extra/x86_64/python-pyqt5/) and run the following script with python3, then provide the output, thanks.

``` python3
from PyQt5.QtCore import QStorageInfo

info = QStorageInfo("/dev/sdc1")

print(info.bytesAvailable())
```

**Comment by keybreak** [comment] 2019-07-14 13:59
Here it is:
```
16830279680
```

Assuming that on Arch / Manjaro this package is one of those already installed:
![image](https://user-images.githubusercontent.com/47599989/61184632-c2f9e280-a658-11e9-8119-cdcc3bbc7e68.png)

**Comment by keybreak** [comment] 2019-07-14 14:07
Since you suspect it's bug of dependency, maybe it's good idea to use some more low-level command directly?

Like lsblk value or something of that nature, since it appears to be more reliable for years and years, and it won't break like some higher-level dependencies of qt / python...

**Comment by BLumia** [comment] 2019-07-15 02:08
> since it appears to be more reliable for years and years

Actually `lsblk` got the new `FSAVAIL` column [around 10 month ago](https://github.com/karelzak/util-linux/commit/bc405d641e41030254e44fe7dc58b465537f99a6) so the `lsblk` vendor by deepin still doesn't have that column so I currently I cannot check this behavior.

The number you provided (`16830279680`) seems doesn't match your screenshot, that's a block device with `15.673828125 GiB` free space, did you using the same device at the time when you run the script? If your device mount point changed, you need also update the script, replace `/dev/sdc1` with the new mount point.

btw could you also take a look what number `nautilus` displayed?

> maybe it's good idea to use some more low-level command directly?

I guess no(if only for this reason). If we can confirm there is a bug from Qt (or whatever which dependencie), we can submit a bug report/patch so this bug can be fixed by whatever open source community or the maintainer and all user will get benefit from this :)

**Comment by keybreak** [comment] 2019-07-15 06:47
Yes, it's same sdc1, nothing changed:
![image](https://user-images.githubusercontent.com/47599989/61199131-75778700-a6e5-11e9-8a2b-f7f492e0eca3.png)

**Comment by BLumia** [comment] 2019-07-15 08:14
Oh sorry I forgot, the argument passed to QStorageInfo is wrong, my fault.

You need to replace the argument(`/dev/sdc1`) to the actual mount point. In your case it's `"/run/media/x133/STORAGE 2"`.

**Comment by keybreak** [comment] 2019-07-15 08:22
Yep, now more realistic, it returns:
```
802309984256
```

Which should mean 802,309 Gb ?

That is 3rd different number now :rofl:

**Comment by BLumia** [comment] 2019-07-15 08:30
> Yep, now more realistic, it returns:
> 
> ```
> 802309984256
> ```
> 
> Which should mean 802,309 Gb ?
> 
> That is 3rd different number now

Although dde-file-manager display it as GB but it actually is GiB (1GiB = 1024 KiB). (ps, 1 B = 8 b so it's not Gb)

As the number you given it's `747.209400177002 GiB` (same with `lsblk` result), then I guess it's using `gio` instead of QStorageInfo ([related code](https://github.com/linuxdeepin/dde-file-manager/blob/909d8bfcd0e4faac1406b78b7a16e4045427c8a7/dde-file-manager-lib/deviceinfo/udiskdeviceinfo.cpp#L189)). Since there are no extra log to check some value, I'll looking into it later.

**Comment by keybreak** [comment] 2019-07-15 08:34
Also i've been talking about this on Manjaro forum, check it out, probably worth mentioning:

**dalto**
I haven't investigated that specific issue or the cause but generally speaking shouldn't that dialog use bytesFree() instead of bytesAvailable(). It probably isn't the solution to the problem but it seems like it would make more sense.

**keybreak**
Well, if i change his example script It returns same number.

Wonder why it's 2 separate functions though, how can drive free space differ on per-user base?
> qint64 bytesAvailable() - returns the space available for current user.
> qint64 bytesFree() - returns the free space on the volume.

**dalto**
quotas

**Comment by BLumia** [comment] 2019-07-16 01:25
> Oh, then i think it should use real Gb universally - mixing units is not cool - will lead to more errors 

No deepin doesn't even use the `Gb` unit (did you means `GB`? Deepin display unit like `GB` but actually it is `GiB` since most of user doesn't fimilar with the `GiB` unit but we actually use it all the time), this is also not an issue of mixing display unit.

Technically there may be someplace mixed data from `gio`, `udisks2` and `QStorageInfo`, and all `gio` calling for local disk will be refactor to `udisks2` calls but this is not yet be done due to the limit of time and resources.

In this case, the volume number is from `gio` instead of `QStorageInfo` and that caused the number not match.

> but generally speaking shouldn't that dialog use bytesFree() instead of bytesAvailable()

Well, using `bytesAvailable()` is intended and that's the funnest part. When maintaining dde-file-manager I doesn't realize the original string is `Free space` since most of the time I use `LANGUAGE=zh_CN` (Chinese) and the locale string is "可用空间" which means "Available space". You may know there may have some weird English local strings which is actually translated from Chinese, I think this is the main issue :joy:

@zhuxiujuancindy @wangjia12

**Comment by zhuxiujuancindy** [comment] 2019-07-16 01:36
文案修改：
【可用空间】【Available space】

**Comment by justforlxz** [comment] 2021-04-23 06:59
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Closed by justforlxz** 2021-04-23 06:59 UTC
