### ISSUE TITLE
Improved kwinrc

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1232] opened 2019-05-25 15:45 UTC
I have finely crafted a [kwinrc config file](https://bin.privacytools.io/?d7451c88d74ff713#7LWulqcPPtAfQf7ljMyDNMFW6Rvtsso305PRDvlYdMc=) so Kwin integration on Deepin is the best.

It follows the same style as Deepin on Muter. You can try it out and give feedback. In a week I will make a pull request.

**Comment by alexwender1** [comment] 2019-05-28 04:28
Is it possible for the windows to memorize their position when closing? For example, I usually use maximized windows; when opening again, they open at normal size - and I need to maximize them manually.

**Comment by BLumia** [comment] 2019-05-28 05:58
> Is it possible for the windows to memorize their position when closing? For example, I usually use maximized windows; when opening again, they open at normal size - and I need to maximize them manually.

It's possible but this sort of work should be done from the application's side. It's the developer's choise to support this feature or not.

**Comment by alexwender1** [comment] 2019-05-28 12:44
> > Is it possible for the windows to memorize their position when closing? For example, I usually use maximized windows; when opening again, they open at normal size - and I need to maximize them manually.
> 
> Generally it's possible but this sort of work should be done from the application's side. It's the developer's choise to support this feature or not.
> 
> For kwin, https://www.reddit.com/r/kde/comments/7ws6py/windowslike_window_positioning_rules_for_kwin/du2x38l which requires `systemsettings` package to tweak kwin configurations. (ps. It's not recommended and not supporteded to do that, so please make sure you know what you are doing once you decided to do)

I mean the Deepin Apps (File Manager, System Monitor and App Store, for example).

Until version 15.6 or 15.7, this problem was not occurring. Since then, it's this bother with the windows.

**Comment by BLumia** [comment] 2019-05-29 03:35
> > > Is it possible for the windows to memorize their position when closing? For example, I usually use maximized windows; when opening again, they open at normal size - and I need to maximize them manually.
> > 
> > 
> > Generally it's possible but this sort of work should be done from the application's side. It's the developer's choise to support this feature or not.
> > For kwin, https://www.reddit.com/r/kde/comments/7ws6py/windowslike_window_positioning_rules_for_kwin/du2x38l which requires `systemsettings` package to tweak kwin configurations. (ps. It's not recommended and not supporteded to do that, so please make sure you know what you are doing once you decided to do)
> 
> I mean the Deepin Apps (File Manager, System Monitor and App Store, for example).
> 
> Until version 15.6 or 15.7, this problem was not occurring. Since then, it's this bother with the windows.

Cannot reproduce on my machine with Deepin and dde-kwin, tested with the file manager and system monitor.

Please consider submit a separate issue for this bug.

**Comment by alexwender1** [comment] 2019-05-29 04:11
> > > > Is it possible for the windows to memorize their position when closing? For example, I usually use maximized windows; when opening again, they open at normal size - and I need to maximize them manually.
> > > 
> > > 
> > > Generally it's possible but this sort of work should be done from the application's side. It's the developer's choise to support this feature or not.
> > > For kwin, https://www.reddit.com/r/kde/comments/7ws6py/windowslike_window_positioning_rules_for_kwin/du2x38l which requires `systemsettings` package to tweak kwin configurations. (ps. It's not recommended and not supporteded to do that, so please make sure you know what you are doing once you decided to do)
> > 
> > 
> > I mean the Deepin Apps (File Manager, System Monitor and App Store, for example).
> > Until version 15.6 or 15.7, this problem was not occurring. Since then, it's this bother with the windows.
> 
> Cannot reproduce on my machine with Deepin and dde-kwin, tested with the file manager and system monitor.
> 
> Please consider submit a separate issue for this bug.

Thanks for the interest.

I made another request and I marked you.

**Comment by es20490446e** [comment] 2019-06-01 11:21
https://github.com/linuxdeepin/dde-kwin/pull/83

**Comment by Iiari** [comment] 2019-07-05 01:36
Thank you for this finely crafted config file.  It contains a few things I was looking for (including center opening of windows) and I added the coverflow alt+tab and the windows command to allow Firefox to hide its titlebar to my own file.

Thank you again!

**Comment by Iiari** [comment] 2019-07-05 01:43
Thank you for this finely crafted config file.  It contains a few things I was looking for (including center opening of windows) and I added the coverflow alt+tab and the windows command to allow Firefox to hide its titlebar to my own file.

Thank you again!

Addendum: I'm not sure what yet, but something in this script breaks some hot corners.

**Comment by es20490446e** [comment] 2019-07-10 23:47
Updated the [kwinrc file on first comment](https://bin.privacytools.io/?d7451c88d74ff713#7LWulqcPPtAfQf7ljMyDNMFW6Rvtsso305PRDvlYdMc=), so it follows the Deepin on Mutter look and feel.

**Comment by aiamuzz** [comment] 2019-07-11 05:36
> I have finely crafted a [kwinrc config file](https://bin.privacytools.io/?d7451c88d74ff713#7LWulqcPPtAfQf7ljMyDNMFW6Rvtsso305PRDvlYdMc=) so Kwin integration on Deepin is the best.
> 
> It follows the same style as Deepin on Muter. You can try it out and give feedback. In a week I will make a pull request.

Oh ... Is it ... i would love to try it out ... can you tell me how this can be made functional on Deepin OS directly ... do i just need to save this config file in its default location and kwin will work like mutter based deepin-wm ...

**Comment by es20490446e** [comment] 2019-07-11 09:57
Exactly.

**Comment by es20490446e** [comment] 2019-07-11 10:15
@zccrs said:
> Thank you. This PR needs to be modified according to the following rules:
> 
> * Rebase your repository
> * Don't modify existing entries (eg: org.kde.kdecoration2/library)
> * Some values don't need to be specified, we need it to be the default (eg: Compositing/Backend)
> * Don't add settings that change the default behavior (eg: Script-runcommandaction)

**Comment by es20490446e** [comment] 2019-07-11 10:18
- [Version with the suggested changes](https://bin.privacytools.io/?a1cb76ddc9bf3d01#3kpifC0PN9gtg5EZTMO3IHa6vwG55R7bcHd7F2fuzEY=)
- [Current version](https://github.com/linuxdeepin/dde-kwin/blob/master/configures/kwinrc)

As far as I know "Script-runcommandaction" is needed for the control center to work using hot corners.

**Comment by zccrs** [comment] 2019-07-12 03:38
> @zccrs
> 
>     * [Version with the suggested changes](https://bin.privacytools.io/?a1cb76ddc9bf3d01#3kpifC0PN9gtg5EZTMO3IHa6vwG55R7bcHd7F2fuzEY=)
> 
>     * [Current version](https://github.com/linuxdeepin/dde-kwin/blob/master/configures/kwinrc)
> 
> 
> As far as I know "Script-runcommandaction" is needed for the control center to work using hot corners.

Any corner settings is empty with default. So, don't add settings for "Script-runcommandaction" group.

**Comment by zccrs** [comment] 2019-07-12 03:45
> @zccrs
> 
>     * [Version with the suggested changes](https://bin.privacytools.io/?a1cb76ddc9bf3d01#3kpifC0PN9gtg5EZTMO3IHa6vwG55R7bcHd7F2fuzEY=)
> 
>     * [Current version](https://github.com/linuxdeepin/dde-kwin/blob/master/configures/kwinrc)
> 
> 
> As far as I know "Script-runcommandaction" is needed for the control center to work using hot corners.

Add setting items must based this file(https://github.com/linuxdeepin/dde-kwin/blob/master/configures/kwinrc), but do not make other changes and do not change the order of setting items.

**Comment by aiamuzz** [comment] 2019-07-12 09:08
> > > It follows the same style as Deepin on Muter. You can try it out and give feedback. In a week I will make a pull request.

> > Oh ... Is it ... i would love to try it out ... can you tell me how this can be made functional on Deepin OS directly ... do i just need to save this config file in its default location and kwin will work like mutter based deepin-wm ...


> exactly 

@es20490446e ... do i need to install any additional packages ... somewhere in the conversation i cam across a mention of something called "breeze" ... is this a package i need to install or is it pre-installed on DeepinOS ?

**Comment by aiamuzz** [comment] 2019-07-12 14:25
> @zccrs
> 
> * [Version with the suggested changes](https://bin.privacytools.io/?a1cb76ddc9bf3d01#3kpifC0PN9gtg5EZTMO3IHa6vwG55R7bcHd7F2fuzEY=)
> * [Current version](https://github.com/linuxdeepin/dde-kwin/blob/master/configures/kwinrc)
> 
> As far as I know "Script-runcommandaction" is needed for the control center to work using hot corners.

@es20490446e ... can you please post a screenrecorder gif video here on the deepin mutter like modifications your kwinrc file enables ... excited to see it ... my system is affected currently and i am not able to view your work(features and functions)

thanks.

**Comment by es20490446e** [comment] 2019-07-12 15:23
### === You have the last word ===

That said my aim isn't to reach perfect consensus, but the further as possible consensus. You have the last word on what to include or not.

Also there's the option of modifying the proposed file by yourselves. Just keep in mind that everything I do is for a reason.

Lets review your observations.

### === Hot corner ===

I thought it was default. Nowadays are you sure you don't want a hot corner for the Control Center?

The Control Center is way more useful that way, as it allows fast changing configuration of constantly modified settings. Like the screen brightness or the sound source.

Having it as a hot corner instead of an icon makes the dock uncluttered, so it eases visually locating other icons.

Plus the user doesn't have any option right now to enable it by themselves.

### === Settings order ===

The order of the provided file is as the KDE Control Center leaves it, which is alphabetical. Won't be better if both orders were consistent with each other?

### === Consistency with the current settings ===

I have reviewed the current settings one by one. The only setting that is not consistent is the mouse bindings, which work-arounds the issue of not being able to resize windows with certain themes, and most likely in practice will never be noticeable by the user.

**Comment by es20490446e** [comment] 2019-07-12 15:27
@aiamuzz Nope, that would take time I don't have 😛

**Comment by aiamuzz** [comment] 2019-07-12 16:06
> @aiamuzz Nope, that would take time I don't have

:cry: ... :cry ... :sob: 

anybody else who has tried @es20490446e ... fine tuned kwinrc ... post a gif screen recorder here ?

I really want to see the features/functions ...

**Comment by es20490446e** [comment] 2019-07-12 18:51
Then just use the file, it's super easy 😁

**Comment by Iiari** [comment] 2019-07-12 18:54
And save a copy/backup of your old file in case it's not to your liking...

**Comment by aiamuzz** [comment] 2019-07-12 19:03
> And save a copy/backup of your old file in case it's not to your liking...

i don't know i tried using the file but i just couldn't see the mutter styled UX ...

@Iiari ... can you post a GIF screen video showing the muttle styled UX and features ?

**Comment by es20490446e** [comment] 2019-07-12 22:33
It isn't that it looks like mutter graphically, but more that it behaves like Mutter. For example having equal animations, work-spaces, visual effects...

**Comment by BLumia** [comment] 2019-07-13 06:37
> === You have the last word ===

Well I though you would like to get your kwinrc merged :joy: , and I would like to let you know the pull request merging process requires minimum changes and atomic commit so multiple changes which affact different behavior may cause your PR harder to merge and maintainer may request change in that case.

Thanks for sharing your config :heart:

**Comment by aiamuzz** [comment] 2019-07-13 08:00
> It isn't that it looks like mutter graphically, but more that it behaves like Mutter. For example having equal animations, work-spaces, visual effects...
> 
> The colors and look and feel mostly depends on the chosen theme.

As its hard for me to comprehend what you mean when you say "equal animations, work-spaces, visual effects" ... hence the request for a gif video ... :sob: !!!

**Comment by Iiari** [comment] 2019-07-14 20:52
The latest updates seem to have broken/removed some kwin effects.  Coverflow alt+tab no longer works for me.  Does it work for anyone else still?  Thanks!

**Comment by aiamuzz** [comment] 2019-07-14 20:54
video ... video ... video ... of the effects please ... :sob:

**Comment by justforlxz** [comment] 2021-04-23 06:58
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.

**Closed by justforlxz** 2021-04-23 06:58 UTC
