### ISSUE TITLE
Stick on f*** login screen...20beta...archlinux-zen

### ISSUE THREAD

**Issue by ArSd-g** [linuxdeepin/developer-center#1720] opened 2020-05-09 21:23 UTC
![15890593183562240409897440257282](https://user-images.githubusercontent.com/42816950/81485237-eb884400-924b-11ea-8cdb-272d13e5f11c.jpg)
Cant do nothing...no password entry...autologin is on...using lightdm ..FIX THIS or give instructions to downgrade deepin

**Comment by Y0ngg4n** [comment] 2020-05-12 17:15
I think its a duplicate of this: https://github.com/linuxdeepin/developer-center/issues/1721

**Closed** 2020-05-12 22:50 UTC
