### ISSUE TITLE
Stuck on shutdown after upgrade to deepin 20.5

### ISSUE THREAD

**Issue by snjvm** [linuxdeepin/developer-center#3100] opened 2022-04-18 16:31 UTC
Stuck on shutdown after upgrade to deepin 20.5

### STEPS TO REPRODUCE | 复现步骤
1. Shutdown is not happening.
2. Have to force press the Power to stop the system.
3. Have to get into BIOS to restart the system every-time.
4. Fear of losing the HDD because of forced power down.

### OBSERVED RESULT | 观察到的结果

![image](https://user-images.githubusercontent.com/62160616/163839163-7b73a3d8-70cb-4488-a926-a97663a2054c.png)
![image](https://user-images.githubusercontent.com/62160616/163839202-b0a5ef5e-99b5-4a71-8593-7c1b2e7b6e6a.png)
![image](https://user-images.githubusercontent.com/62160616/163839249-cb327e0c-2455-4371-9088-848ed162e6f3.png)
![image](https://user-images.githubusercontent.com/62160616/163839299-2748b121-6ca5-467d-8c94-795ac17b9412.png)

### EXPECTED RESULT | 期望的结果
After pressing Power --> Shut down or shutdown -h now, system shutdown completes.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
![image](https://user-images.githubusercontent.com/62160616/163839711-64c0c934-7517-4063-b5be-f5ef9bc42f44.png)

### ADDITIONAL INFORMATION | 额外补充
After 20.5 upgrade multiple other issues have started.
1. Auto start applications take around 4 ~ 5 minutes to start after login.
2. Device Manager hangs after launch.

**Comment by BLumia** [comment] 2022-04-19 01:13
> Shutdown is not happening.

This is not something we can easily reproduce, so I'd like to ask: are you using `sudo apt upgrade` for the v20.4 to v20.5 system upgrade? and does it happen *while* the updating process (e.g. stuck at 99%)?

**Comment by snjvm** [comment] 2022-04-19 02:17
Yes upgraded to v20.5 using **sudo apt update && sudo apt upgrade**. Upgrade completed successfully. OS works fine apart from Sound Issue. Shutdown process is stuck as you could see on the attached images in **Observed Result**.

**Comment by Zeno-sole** [comment] 2022-04-19 02:20
Please use sudo apt dist-upgrade or control center update

**Comment by snjvm** [comment] 2022-04-22 02:24
executed sudo apt dist-upgrade, still the shutdown hangs. **Should i reinstall deepin**. I have made a lot of customisations starting from 15.11.

**Comment by Zeno-sole** [comment] 2022-04-26 08:15
I don't know what you have set. The log prompts read-only. Did you upgrade from deepin 15? There may be many problems. It is not recommended to use this way.

**Comment by snjvm** [comment] 2022-05-27 17:08
Yes it was upgraded from deepin 15 to all the sequential versions, until these problems arose.
1. Stuck on shutdown after upgrade to deepin 20.5
2. No Sound Devices after upgrade to deepin 20.5
After installing fresh deepin 20.5, the sound issue was still present. I have installed Ubuntu 22.04 LTS which has solved the issue. Thanks to all people who supported me in the troubleshooting.

**Comment by BLumia** [comment] 2022-06-15 01:44
I'll close this one since upgrading from deepin v15 to v20.5 is very unlikely to be supported now. A clean installation should be able to resolve the stuck on shutdown issue.

As for the sound issue. It might be able to resolve by switching kernel version. If you are still interested, you can try a clean deepin installation (now we are on v20.6) and see if the current kernel have the sound issue, if not, you can create a new issue and we'll see if we can help you install a testing kernel version and see if we can resolve it in v20.7 release.

Thanks again for the report!

**Closed by BLumia** 2022-06-15 01:44 UTC
