### ISSUE TITLE
Not able to copy files to any connected devices (phones and usb drives)

### ISSUE THREAD

**Issue by sachin-dahal** [linuxdeepin/developer-center#2338] opened 2021-07-05 15:28 UTC
Whenever I try to copy any media or files from my pc to any connected devices, I am getting an **Operation Unsupported** error.
I am using Deepin 20.1 desktop [Community Edition]. I've been facing this issue a lot.

I am completely not sure why deepin's system file manager is not able to send files to any connected devices. :(

**Comment by BLumia** [comment] 2022-05-31 07:06
Sorry for the super late response.

I'm not sure about 20.1. We just released deepin v20.6 today. I have tested your issue on both deepin v20.5 and v20.6 and cannot reproduce this issue, so it's probably fixed during updates.

I'll close this issue for now and I suggest you update the system and see if it's fixed at your end. If you are still facing this issue, please feel free to open a new issue with detailed information so we can look into it.

Thanks!

**Closed by BLumia** 2022-05-31 07:06 UTC
