### ISSUE TITLE
 Printer Manger Driver Problem: Unable to Print

### ISSUE THREAD

**Issue by realPoudel** [linuxdeepin/developer-center#3150] opened 2022-05-09 10:54 UTC
Printer Manger Hard to Recognize USB. (Pc Vendor: Dell OptiPlex 3070)
If Found Unable to Print. 
Printer Name: Cannon Laser Shot LBP 2900.
Os Version: 20.5.

@BLumia @meiyixiang  @justforlxz

**Comment by babyfengfjx** [comment] 2022-05-10 10:02
I think this printer should be able to support, if you can not directly add through the print manager, perhaps the model printer driver is not integrated, you can try to manually install the driver:https://asia.canon/en/support/LASER%20SHOT%20LBP2900/model
![image](https://user-images.githubusercontent.com/24642999/167603832-48d053b8-b40d-46a5-aca4-d5c37913e0a4.png)

**Comment by sarojpoudel33** [comment] 2022-05-11 07:07
![Screenshot_dde-file-manager_20220511122638](https://user-images.githubusercontent.com/45546591/167789543-9ca5c71a-c10f-43eb-9c42-883767ecea5a.png)
![Screenshot_dde-printer_20220511121706](https://user-images.githubusercontent.com/45546591/167789546-6791edae-fe96-4d7c-be23-807cb98d61f3.png)
![Screenshot_google-chrome_20220511122609](https://user-images.githubusercontent.com/45546591/167789550-4ecae4f3-1d81-4b08-9b54-1f83c838d27d.png)

https://user-images.githubusercontent.com/45546591/167789589-352281f3-7eca-48af-bed8-af5932a1ab3e.mp4

[System Log.txt](https://github.com/linuxdeepin/developer-center/files/8667500/System.Log.txt)
[Device Info20220511_124627.txt](https://github.com/linuxdeepin/developer-center/files/8667501/Device.Info20220511_124627.txt)

**Comment by sarojpoudel33** [comment] 2022-05-11 07:08
Above Method Wont Work. @babyfengfjx

**Comment by sarojpoudel33** [comment] 2022-05-11 07:12
@meiyixiang @babyfengfjx  
https://user-images.githubusercontent.com/45546591/167790417-5cf5be75-9ac5-441b-9ac9-0fcf7510e86e.mp4

**Comment by babyfengfjx** [comment] 2022-05-12 06:14
I'm very sorry we don't have that model of device and can't confirm the root cause of the problem in time. From the video, it looks like the system should have recognized the printer correctly, I don't know if trying to install a driver with a non-recommended option will help? Did the official download file with both applications installed successfully also have no effect?
![image](https://user-images.githubusercontent.com/24642999/168003271-577b0900-0af0-405d-94d0-cc92ea4e704a.png)

**Comment by sarojpoudel33** [comment] 2022-05-14 02:04
![image](https://user-images.githubusercontent.com/45546591/168406815-91a21d6a-1802-4ea0-9555-9b08c9b5078e.png)

Tried but result is same.

**Comment by babyfengfjx** [comment] 2022-05-18 01:06
I'm sorry this doesn't help you, but I was wondering if anyone else using this printer has encountered similar problems and might have a solution.

**Comment by babyfengfjx** [comment] 2023-02-08 05:37
Hi brother, I wonder if the problem has been solved on linux? At the moment it seems that the driver issue may need help from the hardware manufacturer to adapt it.

**Comment by babyfengfjx** [comment] 2023-02-14 05:19
Therefore, the issue requires hardware manufacturers to adapt, deepin team temporarily unable to deal with, we will first close this issue for processing, the subsequent use of deepin have other functional issues are welcome to submit at any time ~

**Closed by babyfengfjx** 2023-02-14 05:19 UTC
