### ISSUE TITLE
dde-file-manager 5.5.10 flaky failures on installation

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/developer-center#3036] opened 2022-04-08 00:52 UTC
```
make[1]: Entering directory '/build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-file-manager'
make[1]: Entering directory '/build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-select-dialog-x11'
make[1]: Entering directory '/build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-select-dialog-wayland'
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-file-manager/dde-file-manager.desktop /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/applications/dde-file-manager.desktop
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-file-manager/translations/dde-file-manager-app.qm /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/dde-file-manager/translations/dde-file-manager-app.qm
/usr/bin/qmake-qt5 -install qinstall -exe dde-file-manager /build/deepin-file-manager/pkg/deepin-file-manager/usr/bin/dde-file-manager
/usr/bin/qmake-qt5 -install qinstall -exe dde-select-dialog-x11 /build/deepin-file-manager/pkg/deepin-file-manager/usr/bin/dde-select-dialog-x11
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-file-manager/pkexec/com.deepin.pkexec.dde-file-manager.policy /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/polkit-1/actions/com.deepin.pkexec.dde-file-manager.policy
/usr/bin/qmake-qt5 -install qinstall -exe /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-file-manager/pkexec/dde-file-manager-pkexec /build/deepin-file-manager/pkg/deepin-file-manager/usr/bin/dde-file-manager-pkexec
/usr/bin/qmake-qt5 -install qinstall -exe /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-file-manager/dde-property-dialog /build/deepin-file-manager/pkg/deepin-file-manager/usr/bin/dde-property-dialog
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/assets/dde-file-manager /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/deepin-manual/manual-assets/application/dde-file-manager
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-desktop/dbus/filedialog/com.deepin.filemanager.filedialog.xml /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/dbus-1/interfaces/com.deepin.filemanager.filedialog.xml
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-file-manager/dde-open.desktop /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/applications/dde-open.desktop
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-desktop/dbus/filedialog/com.deepin.filemanager.filedialog.service /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/dbus-1/services/com.deepin.filemanager.filedialog.service
/usr/bin/qmake-qt5 -install qinstall -exe /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-select-dialog-x11/com.deepin.filemanager.filedialog_x11.service /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/dbus-1/services/com.deepin.filemanager.filedialog_x11.service
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-desktop/dbus/filedialog/com.deepin.filemanager.filedialog.service /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/dbus-1/services/com.deepin.filemanager.filedialog.service
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-file-manager/translations/dde-file-manager-app_am_ET.qm /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/dde-file-manager/translations/dde-file-manager-app_am_ET.qm
/usr/bin/qmake-qt5 -install qinstall /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-desktop/dbus/filedialog/com.deepin.filemanager.filedialogmanager.xml /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/dbus-1/interfaces/com.deepin.filemanager.filedialogmanager.xml
Error copying /build/deepin-file-manager/src/dde-file-manager-5.5.10/src/dde-desktop/dbus/filedialog/com.deepin.filemanager.filedialog.service to /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/dbus-1/services/com.deepin.filemanager.filedialog.service: Cannot create /build/deepin-file-manager/pkg/deepin-file-manager/usr/share/dbus-1/services/com.deepin.filemanager.filedialog.service for output
make[1]: *** [Makefile:550: install_filedialog_service] Error 3
make[1]: *** Waiting for unfinished jobs....
```

It's a flaky issue, not always reproducible.

**Comment by babyfengfjx** [comment] 2022-04-08 02:55
@SuperEffie  提交给子项目帮忙分析。

**Comment by SuperEffie** [comment] 2023-02-16 03:16
Due to no reply for a long time and lack of necessary information, we cannot reproduce this issue and we close this issue for now. If the problem still exists, please consider prvoide the necessary information to reopen the issue, or creating another issue. Thank you~
Best wishes!

**Comment by wineee** [comment] 2023-03-13 06:05
dde-file-manager 6.0.0 use cmake now, this issue maybe have been resolved

**Closed** 2024-04-17 12:24 UTC
