### ISSUE TITLE
[Arch Linux] Rendering issues after new updates

### ISSUE THREAD

**Issue by gustavodlima** [linuxdeepin/developer-center#227] opened 2017-04-01 14:33 UTC
Description
-----------------
One of the new issues that came up with updates are this one with the rendering in Dock. Lastest graphics driver, everything updated.

*Note: at some point, you can see in the GIF that volume control is buggy, this is related to #225*

Info
-----------------
updated packages: `deepin-api`;`*-calendar`;`*-daemon`;`*-desktop-schemas`;`*-dock`;`*-file-manager`;`*launcher`;`*-menu`;`*-notifications`;`*-qt5-integration`;`*-session-ui`;`startdde`.

Footage
-----------------
![rendering-issue](https://cloud.githubusercontent.com/assets/14314943/24579582/90c203b8-16ce-11e7-9249-fe0d8d6cdc88.gif)
_____________

**Comment by funilrys** [comment] 2017-04-01 14:35
Duplicate of #224

**Comment by funilrys** [comment] 2017-04-01 14:37
But agree it's happen on 3 deepin installation by me ...

**Comment by gustavodlima** [comment] 2017-04-01 14:37
@funilrys Oh, gonna close it then :)

**Closed** 2017-04-01 14:38 UTC
