### ISSUE TITLE
File Manager BUG ??? ... Size column for folders !!!

### ISSUE THREAD

**Issue by aiamuzz** [linuxdeepin/developer-center#663] opened 2018-11-15 16:13 UTC
## Describe the bug

The Size column information of folders shows the folder size which is a wasteful information ... If i remember right ... folders should show the no of items inside the folder rather than its size ... even if it did show size currently it shows as '4kb' ... if it at least gave the full size of the folder, this information would be useful ...

## Screenshots

![deepinscreenshot_select-area_20181115213840](https://user-images.githubusercontent.com/3283676/48565828-791cf900-e91f-11e8-9961-345ef41683b9.png)

### Distro & Version

Linux Deepin 15.8

### Related package version

dde-file-manager 4.7.1.1

**Comment by BLumia** [comment] 2018-11-19 06:40
For performance reason we did changed this to display the size of the folder it self (same size in `ls -lh` and same behavior in Thunar). After discuss with the product manager and designer, in the upcoming update it will no longer display a size.

![image](https://user-images.githubusercontent.com/10095765/48690278-d7402980-ec08-11e8-9f2b-83af5ea09d4a.png)

Not a bug, closing, thx for reporting this issue.

**Closed by BLumia** 2018-11-19 06:40 UTC

**Comment by aiamuzz** [comment] 2018-11-19 07:15
@BLumia ...

so will the folder show nothing or will it show the no of items inside the folder ?
Displaying the no of items was helpful to get an idea of the contents of a folder ...

**Comment by aiamuzz** [comment] 2018-12-01 14:16
@BLumia ...

Could it be reverted back to displaying the number of items inside the folder ?
for one ... it would suggest the folder is not empty ... and also the column is wasted when some information could be displayed using up the space ...

![deepinscreenshot_select-area_20181201194445](https://user-images.githubusercontent.com/3283676/49329209-a5807880-f5a1-11e8-96b3-28534ae8b121.png)

Can you tell which folder is empty and can be deleted without bothering to look inside ?
