### ISSUE TITLE
Language switching

### ISSUE THREAD

**Issue by D8ma** [linuxdeepin/developer-center#3243] opened 2022-06-13 17:15 UTC
One drawback, however, remained - the input language indication on the panel does not work, this glitch has not yet been fixed.

**Comment by D8ma** [comment] 2022-06-14 20:49
> Since you skipped the issue template, could you give more detail so we could know what exactly is the problem and how to reproduce them? e.g. What input languages are you currently using? How is it working currently and what's the expected behavior?

When pressing the keyboard, the combination of keys to switch the language does not switch between English and Russian

**Comment by D8ma** [comment] 2022-06-14 20:52
> Since you skipped the issue template, could you give more detail so we could know what exactly is the problem and how to reproduce them? e.g. What input languages are you currently using? How is it working currently and what's the expected behavior?

Why does language switching work in Windows, but not in Deepin?

**Comment by D8ma** [comment] 2022-06-14 20:54
> Since you skipped the issue template, could you give more detail so we could know what exactly is the problem and how to reproduce them? e.g. What input languages are you currently using? How is it working currently and what's the expected behavior?

This is a common problem, look at the reviews on YouTube in Russian

**Comment by D8ma** [comment] 2022-06-14 21:00
> Since you skipped the issue template, could you give more detail so we could know what exactly is the problem and how to reproduce them? e.g. What input languages are you currently using? How is it working currently and what's the expected behavior?

https://user-images.githubusercontent.com/107427853/173687991-7e6ce451-0c68-4b2c-92a4-90a3e3f6c1f8.mp4

**Comment by BLumia** [comment] 2022-06-15 01:32
Sorry if that caused a bad user experience. As I already said, could you provide more details so we could know what's the problem and how do you expect to work? Our developers are using both Chinese and English keyboard layout with fcitx and in this case it works out-of-the-box. Since we are not Russian user, we really need to know what is broken and how it should be fixed, so detail information could be helpful than just told us it doesn't work since we don't really know what's the expected behavior.

> look at the reviews on YouTube in Russian

Could you link the review here if possible? If the review provides related information we need, then maybe we can look into it and fix it. Also, as said before, filling the issue template could be helpful since we will know how to reproduce and know what's the expected behavior.

**Comment by Octavian-Q** [comment] 2022-06-15 05:46
> > Since you skipped the issue template, could you give more detail so we could know what exactly is the problem and how to reproduce them? e.g. What input languages are you currently using? How is it working currently and what's the expected behavior?
> 
>  Screenrecorder-2022-06-14-23-58-22-683.0.0.mp4

I found in Deepin language switching works a bit different than windows. Try put the cursor where want to type, check if is there, then while you are on the typing field use the keyboard shortcut to change language

**Comment by BLumia** [comment] 2024-01-05 06:18
> I found in Deepin language switching works a bit different than windows. Try put the cursor where want to type, check if is there, then while you are on the typing field use the keyboard shortcut to change language

Yeah fcitx do work in this way. Then I guess this is not a bug. I'll close this one then.

Thanks for letting us know. Feel free to send any other feedback via the built-in **deepin Home** app or via the GitHub Discussion forum if you are not 100% sure if it is a bug, or via the Issue board if you can confirm it is indeed a bug :)

**Closed by BLumia** 2024-01-05 06:18 UTC
Labels: triage | need more information, project: IME
