### ISSUE TITLE
shutdown not work deepin

### ISSUE THREAD

**Issue by dbinary** [linuxdeepin/developer-center#151] opened 2017-01-25 20:48 UTC
When i try shutdown from deepin icon bar doesn't work, and journal show this:
Linux Arch 4.8.13-1-ARCH

```Jan 25 14:33:52 Arch dbus-daemon[1219]: Activating service name='com.deepin.dde.shutdownFront'
Jan 25 14:33:52 Arch dbus-daemon[1219]: Successfully activated service 'com.deepin.dde.shutdownFront'
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.124 [Debug  ] [main.cpp             main                                62] dbus registration success.
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.125 [Debug  ] [boxframe.cpp         BoxFrame::BoxFrame                  37] this geometry QRect(0,0 1280x1024)
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.126 [Debug  ] [shutdownframe.cpp    ShutdownFrame::ShutdownFrame        24] this geometry: QRect(0,0 1280x1024)
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.152 [Debug  ] [contentwidget.cpp    ShutDownFrame::getInhibitReason     324] m_login1Inter is valid!
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.153 [Debug  ] [contentwidget.cpp    ShutDownFrame::getInhibitReason     331] inhibitList: 1
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.153 [Debug  ] [contentwidget.cpp    ShutDownFrame::getInhibitReason     344] shutdown Reason! ""
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.176 [Debug  ] [userwidget.cpp       UserWidget::getUsernameList         137] getUsernameList: ("user1", "user2")
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.176 [Debug  ] [userwidget.cpp       UserWidget::initUI                  66] whiteList:              ("user1", "user2")
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.224 [Debug  ] [userwidget.cpp       UserWidget::initUI                  80] whiteList:  ("user1", "user2")
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.231 [Debug  ] [userwidget.cpp       UserWidget::currentUser             344] currentUser: "user1"
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.247 [Debug  ] [shutdownframe.cpp    ShutdownFrame::initShutdownManager  59] shutdownManager: QRect(0,0 1280x1024)
Jan 25 14:33:52 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:52.539 [Debug  ] [boxframe.cpp         BoxFrame::setBackground             135] create new bg:  QRect(0,0 1280x1024)
Jan 25 14:33:53 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:53.446 [Debug  ] [boxframe.cpp         BoxFrame::setBackground             135] create new bg:  QRect(0,0 1280x1024)
Jan 25 14:33:54 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:54.486 [Debug  ] [contentwidget.cpp    ShutDownFrame::getInhibitReason     324] m_login1Inter is valid!
Jan 25 14:33:54 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:54.487 [Debug  ] [contentwidget.cpp    ShutDownFrame::getInhibitReason     331] inhibitList: 1
Jan 25 14:33:54 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:54.487 [Debug  ] [contentwidget.cpp    ShutDownFrame::getInhibitReason     344] shutdown Reason! ""
Jan 25 14:33:54 Arch com.deepin.dde.shutdownFront[1219]: 2017-01-25, 14:33:54.487 [Debug  ] [accountsutils.cpp    AccountsUtils::GetLoggedInUsers     33] All logged in users:  ("user1")
Jan 25 14:33:54 Arch kernel: QDBusConnection[2346]: segfault at d50 ip 0000000000000d50 sp 00007f932e9969b8 error 14 in dde-shutdown[400000+fd000]
```

**Comment by felixonmars** [comment] 2017-01-26 02:23
dde-shutdown is expected to segfault on exit (on Arch), but this shouldn't break any functionality. Did you see the shutdown selection window, or just clicked on dock and nothing happened?

**Comment by dbinary** [comment] 2017-01-26 16:42
Yes I see shutdown selection window, but when I do click in any button ( shutdown, restart, suspend ) of selection window nothing happened and selection window is closed only works lock and logout.

Sorry for my bad English!

**Comment by funilrys** [comment] 2017-04-08 08:00
It's an isolated issue ... Or it's fixed ...

We (maybe) can close this @hualet

**Comment by hualet** [comment] 2017-04-08 15:02
Close issue due to issue not reproducable.

**Closed by hualet** 2017-04-08 15:02 UTC
