### ISSUE TITLE
Can't change shortcuts

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#3152] opened 2022-05-11 06:13 UTC
### SUMMARY | 问题概要
Can't change the shortcut keys in Deepin control center

### STEPS TO REPRODUCE | 复现步骤

1. Open Deepin Control Center
2. Go to "Keyboard and Language"
3. Go to Shortcuts
4. Try to change the shortcuts
5. Shortcuts don't change

### OBSERVED RESULT | 观察到的结果

![Record_dde-control-center_20220511120742](https://user-images.githubusercontent.com/33563064/167780725-3213198c-593d-427b-ab98-5c78e62429d8.gif)

### EXPECTED RESULT | 期望的结果

Shortcuts should change

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Distro: Deepin 20.5
DE: Deepin DE
Deepin Control Center version: 5.5.16.2

**Comment by BLumia** [comment] 2022-05-11 06:20
Can be confirmed with `dde-control-center 5.5.16.2-1` under deepin v20.5

**Comment by babyfengfjx** [comment] 2022-05-11 08:26
Hi brother, thanks for the feedback!
I found that the current use can modify the shortcut keys normally, I don't know which key combination you need to set it to? Some of the subsequent special key combinations are not allowed to be set?
![录屏_选择区域_20220511162204](https://user-images.githubusercontent.com/24642999/167803804-1f6fc29b-e22f-48ce-991a-cfaccb4d8b1f.gif)

**Comment by BLumia** [comment] 2022-05-11 08:44
> Hi brother, thanks for the feedback! I found that the current use can modify the shortcut keys normally, I don't know which key combination you need to set it to? Some of the subsequent special key combinations are not allowed to be set?

Try setting Grand Search to <kbd>Shift+/</kbd> and see if it works?

**Comment by luodeepin** [comment] 2023-02-01 05:21
在最新 20.8，控制中心 5.5.156 上可以正常修改快捷键

**Comment by BLumia** [comment] 2023-02-01 05:24
> 在最新 20.8，控制中心 5.5.156 上可以正常修改快捷键

I can still reproduce this issue in `5.5.157-1` under Arch Linux. Are you sure it's fixed? Please use <kbd>Shift+/</kbd> for testing.

**Comment by luodeepin** [comment] 2023-03-10 02:01
如使用 shift 作为其中的快捷键时，请配合 ctrl 、super 或 alt 加其他键，进行修改;
当前设计时不能直接使用shift 和其他单键进行设置

**Comment by BLumia** [comment] 2023-03-10 02:08
@meiyixiang could you confirm? 可以确认一下是否设计如此吗？

**Comment by meiyixiang** [comment] 2023-03-10 06:18
Currently, shift+character input is not supported, and this problem is also true in other distributions, because it can cause other conflicts, so the original shortcut will be automatically restored if the setting is unsuccessful.

**Comment by BLumia** [comment] 2023-03-10 06:22
Thanks! I'll mark this as won't fix then.

**Closed by BLumia** 2023-03-10 06:22 UTC
Labels: triage | confirmed / verified
