### ISSUE TITLE
Releasing shift in a full-screen program causes the dock to open

### ISSUE THREAD

**Issue by jhalounix** [linuxdeepin/developer-center#1687] opened 2020-04-19 14:33 UTC
I do not know if this function has been intentional, but it is very annoying, especially in video games where you cannot press shift because the dock is coming at you.

If you press "Shift" in a fullscreen game, the moment you release it, the dock will open in full game.

If you press "Shift" but then press something else like a "Click" or another key, this will not happen.

In order for this not to happen, the dock must be put into keep hidden mode, not even the intelligent hidden one works.

**Comment by Zeno-sole** [comment] 2022-01-11 13:30
Can you describe the specific phenomenon, I have not reproduced here, perhaps the new version has fixed the problem

**Comment by Zeno-sole** [comment] 2022-01-24 09:57
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue

**Closed** 2022-01-24 09:58 UTC
Labels: other | need confirmation
