### ISSUE TITLE
deepin-editor: Double clicking tab entries with *middle mouse button* can also maximize editor window

### ISSUE THREAD

**Issue by RigoLigoRLC** [linuxdeepin/developer-center#2578] opened 2021-07-02 08:16 UTC
Other apps like Deepin Terminal don't have this issue. I discovered this bug when closing multiple files in a row quickly with MMB, and suddenly the editor goes maximized.

**Comment by BLumia** [comment] 2022-04-01 06:53
Sorry for the super late reply since we didn't look into issues that were created outside the developer-center repo.

I can reproduce this issue in deepin v20.5 with `deepin-editor 5.10.14-1`. And `deepin-terminal 5.4.28-1` doesn't have this issue.

**Comment by babyfengfjx** [comment] 2022-04-08 09:49
Thanks for your feedback,we are very sorry that we did not communicate for a long time, the current issue we found in the latest version of normal, we first close this issue, if there are new issue later,  please feedback to us.

**Closed by babyfengfjx** 2022-04-08 09:49 UTC
Labels: bug | functional behavior
