### ISSUE TITLE
Deepin 15.11 and V20 BETA not booting on Lenovo Yoga

### ISSUE THREAD

**Issue by londonuk371** [linuxdeepin/developer-center#1602] opened 2019-12-01 13:46 UTC
Hello,

I am afraid that the coming V20 won't boot on Lenovo Yoga 720 computers and certainly also on others versions of Lenovo computers. I tried to install the V15.11 and older version without success. 
I downloaded the V20 beta version from:
https://www.mediafire.com/file/7fp0u68tqq31vyo/uos-20-beta-desktop-amd64.iso/file
So I create the USB Key from the ISO tool DEEPIN_B.EXE. I boot and click on *Install Deepin and then nothing, it does not load anything from the USB key!
Here are my BIOS features:
**Information:**
![IMG_8184](https://user-images.githubusercontent.com/22617037/69914738-e70f6200-1447-11ea-9d51-ad5afb57ffe0.JPG)
**Configuration**
![IMG_8185](https://user-images.githubusercontent.com/22617037/69914827-eaefb400-1448-11ea-8d99-83e6166483f4.JPG)
**Security**
![IMG_8186](https://user-images.githubusercontent.com/22617037/69914831-f3e08580-1448-11ea-800e-1e4f4dfd5e84.JPG)
**Boot**
![IMG_8187](https://user-images.githubusercontent.com/22617037/69914839-ffcc4780-1448-11ea-8585-ef3bda1bae39.JPG)

Booting (Step1):
![IMG_8188](https://user-images.githubusercontent.com/22617037/69914845-0fe42700-1449-11ea-8f8b-2d9368ec489d.JPG)

Then nothing...
![IMG_8189](https://user-images.githubusercontent.com/22617037/69914849-183c6200-1449-11ea-8c7c-261960b25f64.JPG)

As mentioned by @BLumia the V20 will be released on kernel version 4.19, but does this freeze comes from the kernel?

**Comment by BLumia** [comment] 2019-12-04 02:41
Try the second option from grub. If it still happens, maybe the kernel is still a little bit old for your laptop.

btw v20 not yet ready for a beta release now (beta may get released in the middle of this month), the one you linked here is an early version for internal test, I'd not recommend you use that image for daily use.

**Comment by londonuk371** [comment] 2019-12-10 12:46
The second option failsafe gives the same result...it's loading from the USB key for 5 seconds then nothing! I can see that it's accessing the USB key thanks to a led.

I could boot with all others Linux distro I tried like Ubuntu 18 or Fedora so I am not sure the problem comes from the kernel version. Even old distro...

Maybe it's the video card which is not compatible. My laptop: https://www.lenovo.com/us/en/laptops/yoga/700-series/Yoga-720-15/p/88YG7000828

Is there any log somewhere to know exactly what is going on?
![image](https://user-images.githubusercontent.com/22617037/70530354-fd59a400-1b52-11ea-92e1-399948536ebb.png)

**Comment by gvansanden** [comment] 2020-09-11 13:17
I have a Yoga 330, it will not install either.  I just get a blinking cursor over the lenovo logo, no grub even.  Same bios settings as reporter.  Ubuntu works fine on it and Debian 10 installs also

**Comment by elrandar** [comment] 2020-11-26 22:27
I have a Yoga Slim 7. Same behaviour. Grub starts but nothings happens when I install

**Comment by myml** [comment] 2021-12-30 03:23
Duplicate of #1578

**Closed by myml** 2021-12-30 03:23 UTC
Labels: bug | functional behavior, duplicate | repeat or similar
