### ISSUE TITLE
[BUG] cannot transfer any file to samsung android

### ISSUE THREAD

**Issue by SiamSami** [linuxdeepin/developer-center#975] opened 2019-03-06 04:11 UTC
## Describe the bug
We cannot transfer any file to Samsung device.
## To Reproduce

Steps to reproduce the behaviour:
1. Plug an android with a USB.
2. Try to copy a file from the computer to the android.
3. See the error.

## Expected behavior

We should be able to copy any file to Android devices.

## Screenshots

![image](https://user-images.githubusercontent.com/33563064/53855446-ddabb300-3ff7-11e9-98a2-72ec5bd1a261.png)

## Enviroments:
Desktop environment: Deepin
### Distro & Version

Distro: Archlinux
Architecture: x86_64
### Related package version
dde-file-manager v1.8.2(4.7.7.1-1)

### Additional context

GVFS Version: 1.38.1+9+gd4dab113-2

**Comment by iamthevoid** [comment] 2019-03-06 09:28
Maybe stupid question, but... Are you sure that you copy file to correct volume? Some vendors makes two volumes available when phone connected. First represents /emulated/0/ ('sdcard' directory, rw), second - read only - is small place when drivers placed.

In Manjaro Deepin i haven't met this problems. But my phone is not manufactured by Samsung :)

**Comment by SiamSami** [comment] 2019-03-06 15:32
> Maybe stupid question, but... Are you sure that you copy file to correct volume? Some vendors makes two volumes available when phone connected. First represents /emulated/0/ ('sdcard' directory, rw), second - read only - is small place when drivers placed.
> 
> In Manjaro Deepin i haven't met this problems. But my phone is not manufactured by Samsung :)

I get the error both when I try to copy a file from my computer to sd card and when I try to copy it to internal storage.

**Comment by tribunal2000** [comment] 2019-03-08 07:45
Does it work when you are using Nemo, for example?
It seems something is wrong with mount point or mount options

**Comment by SiamSami** [comment] 2019-03-08 15:24
Yes, it works with other file managers. I tested it with Nautilus.

**Comment by SiamSami** [comment] 2019-06-18 17:01
@BLumia Since you guys don't use any Samsung device, can you tell me where _could_ the problem be?

**Comment by BLumia** [comment] 2019-06-19 01:00
I'm not sure since I cannot reproduce but maybe you can take a look at `dfilecopymovejob.cpp` ?

**Comment by ydvaditya** [comment] 2020-02-04 18:47
is there any fix for this ?

**Comment by babyfengfjx** [comment] 2022-01-21 09:20
![image](https://user-images.githubusercontent.com/24642999/150500583-9bc09f53-a077-46fa-86bf-3bb6c5ae2216.png)
I don't know in V20.4 version  still have this problem? We can use other Android phones normally. Can we provide more operation information, and the latter try to replace Android devices?

**Comment by babyfengfjx** [comment] 2022-02-22 08:07
I haven't received your feedback for a long time,we close  this  issue now , any new issue  are welcome to feedback~

**Closed** 2022-02-22 08:07 UTC
