### ISSUE TITLE
AppImage no longer added to launcher

### ISSUE THREAD

**Issue by aksh1618** [linuxdeepin/developer-center#837] opened 2019-01-20 07:31 UTC
## Describe the bug

The prompt asking to add an AppImage to launcher, which used to appear on running an appimage, no longer appears.

![screenshot from 2019-01-31 20-32-00_cropped](https://user-images.githubusercontent.com/26065812/52063188-1f2fe500-2598-11e9-9738-f2c3e9482fa2.png)

## To Reproduce

Double click an (executable) AppImage in Deepin File Manager.

## Expected behavior

A prompt should appear asking to add AppImage to the launcher, accepting which should create a desktop file like `~/.local/share/applications/appimagekit-<App Name>.desktop`

### Distro & Version

Arch Linux

**Comment by hualet** [comment] 2019-01-30 07:31
Did AppImage really create the desktop file? If yes, please use `desktop-file-validate` command on the file to check if it's valid.

**Comment by aksh1618** [comment] 2019-01-31 14:08
@hualet Yep, in `~/.local/share/applications/appimagekit-<App Name>.desktop`, as I said. Running `desktop-file-validate` on any of the existing ones gives no errors.

**Comment by alexwender1** [comment] 2019-02-05 18:40
I have the same problem.

**Comment by hualet** [comment] 2019-03-13 06:27
I can't reproduce this on either deepin or arch, tested with raven-reader appimage version.

can you just give me the appimage file that having this issue?

**Comment by aksh1618** [comment] 2019-03-13 06:52
I was trying with [AO](https://github.com/klaussinani/ao/releases), also just tried Raven Reader, doesn't work either. Double clicking, this shows up: 
![DeepinScreenshot_select-area_20190313121955](https://user-images.githubusercontent.com/26065812/54259066-8e7ef880-458a-11e9-9f76-3e2e8dfa8814.png)

Clicking on Run, the app starts. No prompts. Would you happen to know where the code responsible for creating the desktop file is? Or which tool is responsible for it?

**Comment by hualet** [comment] 2019-03-13 07:18
![image](https://user-images.githubusercontent.com/2023967/54260069-df025000-45a2-11e9-9231-9873d6be13d8.png)

I think the prompt dialog is from appimagekit, maybe you should ask @probonopd, the creator of appimage :)

**Comment by aksh1618** [comment] 2019-03-13 09:55
For now, I have installed `appimaged`, as:
``` bash
wget "https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-x86_64.AppImage"
chmod +x appimaged-x86_64.AppImage
./appimaged-x86_64.AppImage --install
```
It kinda works, with no prompt and no icons.

**Comment by aksh1618** [comment] 2019-03-13 09:56
For now, I have installed `appimaged`, as:
``` bash
wget "https://github.com/AppImage/appimaged/releases/download/continuous/appimaged-x86_64.AppImage"
chmod +x appimaged-x86_64.AppImage
./appimaged-x86_64.AppImage --install
```
It kinda works, but no prompt, it auto-adds anything in the monitored paths

**Comment by hualet** [comment] 2019-03-13 14:30
@aksh1618 Just drop the `--install` option, that means you choose to install the desktop, so there's no prompts any more I think.

**Comment by aksh1618** [comment] 2019-03-16 19:46
@hualet No, `--install` command is for installing appimaged. Anyway I'm using AppImageLauncher for now instead of appimaged and it's been good.

**Comment by hualet** [comment] 2019-03-17 03:55
@aksh1618 I still don't think it's DE related 😂 , and I found that appimage owns it's forum https://discourse.appimage.org, maybe you can ask there?

**Comment by probonopd** [comment] 2019-03-17 09:07
Some AppImages used to contain a bash script that showed the dialog posted above. This is no longer recommended. Instead, users who wish desktop integration are advised to install the optional [appimaged](https://github.com/AppImage/appimaged) daemon. 

Please report any issues with it over at https://github.com/AppImage/appimaged/issues, thanks.

**Comment by hualet** [comment] 2019-03-31 06:22
So, I'll close this for now.

**Closed by hualet** 2019-03-31 06:22 UTC
Labels: info needed
