### ISSUE TITLE
Discountinuing archdeepin

### ISSUE THREAD

**Issue by antechdesigns** [linuxdeepin/developer-center#1260] opened 2019-06-01 14:57 UTC
After the latest deepin update I will be Discountinuing archdeepin, what an absolute mess!! So to save both of us from embarrassment, I will be moving to a different DE.
I wish you good luck in the future...

## Describe the bug
to many to mention, most have been posted!!

## To Reproduce
Just boot the thing up and try using it

## Expected behavior
Less bugs than there were before update

## Screenshots
Cant open deepin-screenshot, it segfaults

### Distro & Version
archdeepin and probably others...

### Related package version
Not sure, can't be bothered checking at this point, already been posted!!!

### Additional context
was this last update a joke?

**Comment by keybreak** [comment] 2019-06-01 15:03
I feel your pain here.
Each Arch update lately, with little exceptions it feels like we do 1 step forward and 3 steps back.

A lot of what was working good breaks.

All comes down to this discussion https://github.com/linuxdeepin/developer-center/issues/1093

**Comment by felixonmars** [comment] 2019-06-01 16:23
I have no idea about your deepin-screenshot segfault since it works normally here. I cannot help since it seems you are bothered too much to post a stack trace here.

**Comment by keybreak** [comment] 2019-06-01 16:43
@felixonmars 
Give him a break man. It's a liiiiiiiiiiittle bit frustrating to bug-report as much as him and myself do and have very little fixed (include super-hardcore bugs like https://github.com/linuxdeepin/developer-center/issues/1200 / https://github.com/linuxdeepin/developer-center/issues/891 / https://github.com/linuxdeepin/developer-center/issues/1149 i'm not even getting into kwin territory here, for obvious reasons), with new bugs coming way more with each update instead.

What he's clearly saying: test before release, actually use your own product.

For example, i myself can hardly believe that you don't see coredumps / segfaults of control-center https://github.com/linuxdeepin/developer-center/issues/945#issuecomment-497938449 if you really use Arch Deepin daily.

____

Pretty sure that if you try to:
1. Take screenshot & check sudo journalctl -p3 -xb
2. Take screen recorder & check sudo journalctl -p3 -xb
3. Much more other stuff reported previously...

You'll see a lot on clean up to date Arch Deepin :smiley:

**Comment by aiamuzz** [comment] 2019-06-01 16:54
i am not on arch ... but even the standard DeepinOS seems to have moved into a similar space ... with `kwin` rushed in with it made default when its nothing more than barebone ... and reporting bugs seems of no use as the team seems to be thin on resources ... with no timely fixes and responses !!!

**looks like the team chewed on more than it can swallow ???**

**Comment by keybreak** [comment] 2019-06-01 17:03
> looks like the team chewed on more than it can swallow ???

Even if it is so - it's perfectly normal situation in development & i can understand that.

But it's not hard to avoid all those mistakes that was made & still continues:
1. Priority for most hardcore & obvious bugs over ANY feature requests.

2. Not making new bugs and killing what worked - by improving testing process after changes was implemented.

3. Do at least some manual testing prior to new packages release, because even ordinary users can see obvious stuff right away, pretty sure devs will too.

____

I personally respect the good work when i see one, but amount of **new** bad is way above amount of good that's still left or was introduced recently.

Please don't kill this cool project that easily.

**Comment by felixonmars** [comment] 2019-06-01 17:11
> @felixonmars
> What he's clearly saying: test before release, actually use your own product.

I really think you have made your point on these because I **always** do. Like I have said many times before, I wouldn't have bumped the packages if problems like a segfault on startup, doesn't open, failed to install are present in my testing. I use my packages daily, really.

> For example, i myself can hardly believe that you don't see coredumps / segfaults of control-center [#945 (comment)](https://github.com/linuxdeepin/developer-center/issues/945#issuecomment-497938449) if you really use Arch Deepin daily.

I was able to see some coredumps but it never actually affected usage. I don't know the cause either but I can hardly believe this is a blocker level bug.

> Pretty sure that if you try to:
> 
>     1. Take screenshot & check sudo journalctl -p3 -xb
> 
>     2. Take screen recorder & check sudo journalctl -p3 -xb

These two, however, always work fine here. For screenshot there is no segfault here. The segfault-on-exit issue of screen-recorder also doesn't affect usage.

>     3. Much more other stuff reported previously...
> 
> 
> You'll see a lot on clean up to date Arch Deepin smiley

I can understand your frustration if you are experiencing issues like this, and I really feel sorry. But repeating false claims like I never tested before pushing a package or I don't use my own packages really don't help here and made me feel really exhausted.

**Comment by keybreak** [comment] 2019-06-01 18:00
> Like I have said many times before, I wouldn't have bumped the packages if problems like a segfault on startup, doesn't open, failed to install are present in my testing.

Ok...If it is so then question is - how come you don't have what 2 separate people have on different hardware configuration & even VMs?

I don't think it is possible, unless you have some really intense differences / settings on your enviroment, than what we as end-users have...

> I was able to see some coredumps but it never actually affected usage. I don't know the cause either but I can hardly believe this is a blocker level bug.

Hopefully it's not, but ain't all coredumps / segfaults are indicators of blockers / serious bugs regardless of reasons?

Plus it's getting harder and harder to debug, since journal is flooded, so hopefully we could figure out reason.

____

> These two, however, always work fine here. For screenshot there is no segfault here.

I think he was referencing those errors mainly which seems to be related to the fact that both screenshot and recorder have no gui, so it would make sense to catch those errors before releasing package (even if it's not necessarily blocker, looks like it's just uncaught warning level message which floods error journal of **sudo journalctl -p3 -xb** for some reason):
```
jun 01 20:39:38 x133-pc deepin-turbo-invoker[24523]: error: Failed to initiate connect on the socket for type dtkwidget.
jun 01 20:39:38 x133-pc deepin-turbo-invoker[24523]: error: Failed to initiate connect on the socket for type generic.
jun 01 20:39:38 x133-pc deepin-turbo-invoker[24523]: error: Start application /usr/bin/deepin-screenshot as a binary executable without launcher...
````

Also this looks kinda weird (throws it after ending of record):
```
jun 01 20:41:02 x133-pc deepin-screen-recorder[24563]: QThread: Destroyed while thread is still running
```
> The segfault-on-exit issue of screen-recorder also doesn't affect usage.

Yes, and that one still too...Not cool 

Also **screen-recorder** still has this https://github.com/linuxdeepin/developer-center/issues/940 on intel hardware + **video-linux** drivers only, nvidia proprietary and VirtualBox VM is fine for me.

Also i can hardly believe that you actually tried to minimize / maximize / close terminal :smile: It's super-buggy now, extends and shrinks or maximizes on it's will (and some functionality related to resize was mentioned in some of changelogs, so...makes sense to test it).

____

> But repeating false claims like I never tested before pushing a package or I don't use my own packages really don't help here and made me feel really exhausted.

No offense man, i don't have anything against you personally, considering amount of Arch packages even outside of Deepin you have to deal with, it's nearly impossible to keep up even if there would be 0 manual testing.

But @BLumia for example uses KDE a lot, so it would make sense at least to assume, considering whole situation that it's pretty hard not to notice some stuff.

Really more and more people, even very devoted ones seeing no sense in detail reporting, hence all frustration...
So i really get what @antechdesigns is actually saying here.

**Comment by antechdesigns** [comment] 2019-06-01 18:16
@keybreak its not just that, I am tired of reporting bugs that don't get addressed, example: you still can't open dedit as root, this was posted months ago and yet 'feature requests' are taking priority and causing more bugs there are many more (567 open bugs) but I just can't be bothered anymore...

**Comment by felixonmars** [comment] 2019-06-01 18:23
> > Like I have said many times before, I wouldn't have bumped the packages if problems like a segfault on startup, doesn't open, failed to install are present in my testing.
> 
> Ok...If it is so then question is - how come you don't have what 2 separate people have on different hardware configuration & even VMs?

Because I am not a boss and doing packaging for Arch is completely voluntary.

> I don't think it is possible, unless you have some really intense differences / settings on your enviroment, than what we as end-users have...

It is possible due to different packages/configurations/hardware/drivers/... And no, the world is not perfect and not every bug is always reproducible everywhere.

> > I was able to see some coredumps but it never actually affected usage. I don't know the cause either but I can hardly believe this is a blocker level bug.
> 
> Hopefully it's not, but ain't all coredumps / segfaults are indicators of blockers / serious bugs regardless of reasons?

Not always. I agree they should be fixed and they are already present for too long. But that alone doesn't make it a serious bug.

> Also i can hardly believe that you actually tried to minimize / maximize / close terminal on this last update smile It's super-buggy now, extends and shrinks or maximizes on it's will (and some functionality related to resize was mentioned in some of changelogs, so...makes sense to test it).

I have tried many times but it still works correctly here. I am using deepin-kwin, in case that's the difference.

I understand that it's annoying to open many issues but get only a few fixed. I am not happy with that either but that's the nature of open source software. In general anyone can help here and I always open PR to fix serious bugs myself. The others, however, are up to whoever cares enough and also has time.

**Comment by aiamuzz** [comment] 2019-06-01 18:24
> 2\. Not making new bugs and killing what worked - by improving testing process after changes was implemented.

exactly ... we find things that worked before and we have gotten comfortable and they are suddenly missing

> So in plain words - at least don't actively kill the good things which we already have & enjoy.

all good things have been lost ... with `kwin` ... `deepin-wm(mutter)` was so good and efficient at managing the desktop/workspaces ... it had become second skin to me ... and with abrupt in your face introduction of `kwin` with absolutely no alternatives to the workflow(options/features/shortcuts) that already existed on `deepin-wm` is an absolute deal breaker ... and that's why i continue on the unstable branch with deepin-wm(at least my workflow is 100% intact) !!!

**Comment by aiamuzz** [comment] 2019-06-01 18:33
> Because I am not a boss and doing packaging for Arch is completely voluntary.

honestly ... thank you @felixonmars ... things always tend to turn in the direction this conversation is going ... the only people who are accountable are the people being paid for developing Deepin ... and currently they all seem to be watching from the sidelines and that is a let down !!!

@BLumia ... @hualet ... @wangjia12 ... time for you to collect valuable feedback from this conversation !!!

It would have been far better if you had only migrated from **Debian-Unstable branch to the Debian-Stable branch** and worked towards getting the new branch up to speed and stability that existed on the unstable branch ... after that you could have focused on the applications and their new features and kwin and other implementation !!!

currently its a big mess ... @keybreak ... @antechdesigns ... and myself have been pretty active at testing / reporting issues ... and all of us are really down and low as you can see ... @antechdesigns seems determined to discontinue and with good reason ... @keybreak is trying his best to get the message across ... and I am sitting on the sidelines(on unstable branch and deepin-wm) because the UI/UX has been messed big time !!!

**Comment by BLumia** [comment] 2019-06-01 19:22
I think we need a Code of Conduct now.

First of all please always DO submit any related error info or log or stacktrace or anything may helps to associate bug, and use a title which related to the bug.

Second is, it is not that easy to create/maintain a new distribution(Archdeepin, not Arch). Since you are do packaging job so you need to know what's going on and should know how to deal with basic issue. Once you don't know how to deal with it, post your issue to community so other prople may give you/your work some love. You just cannot blame upstream just because the package you ported to your distro just doesn't work on your distro -- who knows what is going on if you does not even provide any information?

> Do at least some manual testing prior to new packages release, because even ordinary users can see obvious stuff right away, pretty sure devs will too.

I have to make it clearly, again, basicly all DDE application are developed and tested under Deepin distro, we don't have so much time and resources on porting package to other distro (the fact is, DDE application is only officially supported under Deepin distro), although we would like to do that and helping out other people who want to contribute.

> What he's clearly saying: test before release.

Like I have said many times before, we **do** test them before we release them to Deepin. For other distribution, absolutely the package maintainer should do the testing job. @felixonmars did a really good job about packaging, testing and then release the package to Archlinux. I'm not sure who is the package maintainer of the package from your distro, if they did release the package, you should report this issue to them first. If you did the packaging job and you do not know how to deal with the issue, then just post your issue so other people can help.

> But @BLumia for example uses KDE a lot, so it would make sense at least to assume, considering whole situation that it's pretty hard not to notice some stuff.

I use both of them, actually I use Arch and Gentoo with KDE installed and I also use LXQT with i3wm on my another laptop. I use Deepin with DDE most of the time in a day so what's the problem about this? Did you means we should always use DDE on whatever distro I use just because I contribute on DDE?

> I understand that it's annoying to open many issues but get only a few fixed. I am not happy with that either but that's the nature of open source software. In general anyone can help here and I always open PR to fix serious bugs myself. The others, however, are up to whoever cares enough and also has time.

Yeap, I agree with that. It remind me the GitHub motto: "build software better, **together**". A community force will be very helpful to both people to build a better DDE, so why people just know how to complain but don't know to do the thing what really can helps?

> Ok...If it is so then question is - how come you don't have what 2 separate people have on different hardware configuration & even VMs?

Good idea, let me tell you a story. So the first step is let the boss hire two fulltime QA to working on this, whoops, we need money to pay for them, then we need customer pay us money, customer are sending new feature request or they won't pay to our boss so we then need to work on that no-sense feature request now. Then we found that mips and ARM port breaks, and then developers need extra work time to get bug fixed. After get everything works again, two developer leaved the development team due to the high work load, customer feels bad about the release delay and stop planning buying the product. Now what should we do? Oh of course we should get two person get unpaid to do QA for Deepin. Is that right?

Things are not that easy as you imaged, we both would like to do better, but is that really helpful to just complain about bug without information provided and yelling developer about new code brings new bug?

Here 3:00 AM now and it's of course not working time. I am **not** even a manager of Deepin, I just would like to become one of a bridge to help Deepin become more community-friendly and help community people make better use of DDE. I did these extra things completely voluntary without paying any extra cent to me and I think that is already all what I can do now. It is totally fine if you doesn't have time or energy to help Deepin community out, but what's the point yelling to others who would like to help the community out and treat them as a free-of-charge customer support guy? I did also feel very frustrated since it seems all what I've done seems doesn't helps at all. Maybe I should calm down for a few days, stop do volunteering on Deepin community and take a rest. Sorry about that.

**Comment by keybreak** [comment] 2019-06-01 19:23
> It is possible due to different packages/configurations/hardware/drivers/... And no, the world is not perfect and not every bug is always reproducible everywhere.

Like i've said before - personally i talk only about as clean as it can possibly get. I use ant's Arch Deepin which have latest Kernel / untouched configurations / **deepin** and **deepin-extra** groups installed. Arch i usually test on separate VMs on **deepin-wm** and **deepin-kwin**.

And there are also Manjaro Deepin on extremely different hardware of 2 laptops and 1 desktop, Kernels i use there are 4.19 LTS, 5.0 and 5.1 (all bugs repeatable everywhere, except obviously on 5.1 **deeping-anything** can't build).

Usually, with very rare exceptions, bugs that i report are repeatable everywhere and by multiple people and distros, include even Linux Deepin itself and Fedora Deepin.
Also, when i check other's reported bugs - i extremely rarely can't repeat them myself...

So i'd say what you're saying holds true for very marginal portion of those tests, even given variety of my personal testing environments it's hard to believe that you can't repeat **that** much.

There must be some other reason that differentiate our testing environments, maybe yours is not as vanilla and uncofigured as mine, maybe you have some development packages or other stuff installed which tampers results...But that's not highly likely.

> Not always. I agree they should be fixed and they are already present for too long. But that alone doesn't make it a serious bug.

I agree, hopefully you right on isolated issues, but in general more you have - faster it will snowball into unsolvable mess and most likely cause serious bugs, besides there are really serious bugs outside of those new ones already.

I think outside of improving testing of packages prior releasing - devs should focus on getting 0-day bugs fixed as fast as it can be, because later it will be really hard to figure out what exactly caused it, and usually there are not that many actual changes on most of (isolated for particular issue) commits on release day.

> I have tried many times but it still works correctly here. I am using deepin-kwin, in case that's the difference.

Confirmed by me on both **deepin-wm** and **deepin-kwin**.

> I understand that it's annoying to open many issues but get only a few fixed. I am not happy with that either but that's the nature of open source software. In general anyone can help here and I always open PR to fix serious bugs myself. The others, however, are up to whoever cares enough and also has time.

As someone who use Manjaro Deepin for work and daily computing i do whatever i can personally to make it better and help, but sadly at least yet i don't know languages that requires actual changes or introducing PR.

Besides i guess you know why people still count on devs who know OS by heart, it's not like music player or something...It's living breathing complex organism (which actually made by same people who was doing EXTREMELY well, like almost second to none in terms of philosophy and beauty of this DE).

**Comment by keybreak** [comment] 2019-06-01 21:29
@BLumia      
> Good idea, let me tell you a story. So the first step is let the boss hire two fulltime QA to working on this, whoops, we need money to pay for them, then we need customer pay us money, customer are sending new feature request or they won't pay to our boss so we then need to work on that no-sense feature request now. Then we found that mips and ARM port breaks, and then developers need extra work time to get bug fixed. After get everything works again, two developer leaved the development team due to the high work load, customer feels bad about the release delay and stop planning buying the product. Now what should we do? Oh of course we should get two person get unpaid to do QA for Deepin. Is that right?
>
> Things are not that easy as you imaged, we both would like to do better, but is that really helpful to just complain about bug without information provided and yelling developer about new code brings new bug?

Thank you for being honest. But be fair - none of us known any of that prior that day.
That story explains a lot, especially why you prioritized no-sense feature requests, instead of fixing bugs (despite of how bad / blocking they are).

> Did you means we should always use DDE on whatever distro I use just because I contribute on DDE?

Of course not - i haven't said it and sorry if you thought so, i was just referencing why this "rumors" came about.

I think you understand why people from open-source community and usual users perceive it that way, given current situation and fact that almost no one actually **know** that:
- You have corporate clients
- You prioritize corporate clients demands (because you want to pay people for their work)

So of course from outside it looks like devs couldn't care less of community and actual state of stability / testing / bugs. Because we don't know what you know about whole process.
______

> Yeap, I agree with that. It remind me the GitHub motto: "build software better, together". A community force will be very helpful to both people to build a better DDE, so why people just know how to complain but don't know to do the thing what really can helps?

> Here 3:00 AM now and it's of course not working time. I am not even a manager of Deepin, I just would like to become one of a bridge to help Deepin become more community-friendly and help community people make better use of DDE. I did these extra things completely voluntary without paying any extra cent to me and I think that is already all what I can do now. It is totally fine if you doesn't have time or energy to help Deepin community out, but what's the point yelling to others who would like to help the community out and treat them as a free-of-charge customer support guy? 

Well, then we all feel same.
I'm also not part of Deepin at all, as you know, and don't get paid for this, yet spend a lot of my free time for testing / helping community and making actually helpful bug-reports, yet...Well, you told your story, so i had nothing to add there.

And i do this just because i really liked this DE.

You want to do two hardly achievable things at the same time:
1. Serve corporate overlords interest to keep team floating
2. Expect independent open-source community to help without knowing anything about process of making decisions.

I believe dev team can't have serious help from open-source free community right now, because:
1. Ignoring stability / serious bugs
2. Letting down people, who already actively love & help you by:
    - Privacy issues / rumors / not being 100% transparent (yet still keeping up questionable decisions like that https://github.com/linuxdeepin/developer-center/issues/1261)
    - Taking VERY hard decisions very often, which involve whole experience changes (like moving to kwin without proper testing)
3. Not accounting the fact, that all people here actually want Deepin to be best OS / DE for all of us - but without stability you will also loose corporate clients very fast anyway (despite of what they say they want).
4. Keeping all internal internal-discussion / communications / most interesting portions of forum / some of code comments & resources strictly on chinese, which of course cuts down even open-source community developers population, because only english is international language at least for now.

Believe me, even though i work in another field of IT industry - i understand exactly what you struggle with.

But without balancing means of getting to our end goals - we all won't succeed because Deepin is / suppose to be instrument for our daily life / work / it's own development preferably, despite if we are Deepin devs / community users / corporate clients.

I think that Deepin team will have far better chances to survive and not loose your workplaces by placing bets more towards open-source community, improving workflow and stability.

Because eventually everyone will notice stuff like this https://github.com/linuxdeepin/developer-center/issues/1200 and at the very least won't like it, because it completely breaks almost anyone's workflow.

Hence it would make total sense to prioritize it over any feature request or minor bugs that at least not many people will notice right away.

I'm sure there are a lot of people who would like to help for free, because they're actually using this DE for their daily life and work. But you would have to give them at least something to get a grip on, show some respect to any effort to make Deepin even tiny little bit better for everyone.

> I did also feel very frustrated since it seems all what I've done seems doesn't helps at all. Maybe I should calm down for a few days, stop do volunteering on Deepin community and take a rest. Sorry about that.

I don't think that what you're doing daily is for nothing - i respect all your personal efforts and certainly many people see you as face and eyes of Deepin dev team for a reason.

But i really hope that you'll read what i had here someday and consider changing vector, to become more effective in what you want to achieve.

I wish you good luck @BLumia and hope that taking rest will help to see more light in all of this.

____

P.S. Like i've said before - i can help spread a word in open-source community, at least on Manjaro forums portions for sure. Hopefully some developers would come, just let me know how to do it properly and where exactly you would like to apply additional force (it's not easy to know such a huge codebase by heart, outside of actual dev team, so it have to require at least some level of knowledge / communication i assume).

But again, if you want to prioritize corporate interests 100% above users / dev community...
I doubt anyone would like to join for help, because it would be counter-intuitive and in some way waste of time.

**Comment by BLumia** [comment] 2019-06-02 08:10
Once again, we **do** fixing bugs on Deepin and also do feature requests during work (Deepin emploee get paid to get these features implemented, and customer is also the source to keep the company running).

We **both** do extra community support on non-Deepin distro on our free time with love and it's completely voluntary without paying money, personally I still believe we can do better if community people can take part in and give back to the community itself in the right way, so could we just only do things which really useful for solving problem instead of random complain?

> Ignoring stability / serious bugs

As I already said again we **do** fix bugs if that happends on Deepin distro and also would love to help other distro port to fix bugs, but once we cannot response very quickly, could you mark it as help wanted or something else so other people may would like to give some love?

> Letting down people, who already actively love & help you by:
> - Privacy issues / rumors / not being 100% transparent (yet still keeping up questionable decisions like that #1261)
> - Taking VERY hard decisions very often, which involve whole experience changes (like moving to kwin without proper testing)

Deepin is, still, a company driven project,it is completely fine if anyone want to create a fork of DDE if they want. I do my best to make things goes better to community, but I cannot just magicly change the current state to a perfect state.

> Keeping all internal internal-discussion / communications / most interesting portions of forum / some of code comments & resources strictly on chinese

I'm sorry my English is very bad (I'm not a native English speaker) and writing a reply also spend me a lot of time on looking up the dictionary, find typo and grammer issue and etc. About documentation which I was working on, I always also spend time to make a English version at the same time. But I still hope some native English speaker can do help about translating, writing tutorials and etc.

-----------------------

Back on the topic:

> Discountinuing archdeepin

It seems archdeepin user cannot get any support from nether Arch nor Deepin nor the archdeepin maintainer, fire issue without any useful information but just complains doesn't helps at all. So maybe it is the right way to discountinue archdeepin. I'm serious.

**Comment by keybreak** [comment] 2019-06-02 09:03
> personally I still believe we can do better if community people can take part in and give back to the community itself in the right way, so could we just only do things which really useful for solving problem instead of random complain?

- Yes, and we do it a lot.
- At the same time i can not agree that those are just **random** complaints, it's perfectly valid form of saying that we clearly need to change something, because when you do something constantly without positive income, and get mostly negative outcome - you'll certainly get frustration even from serious contributors. Just like you had it that night either, it's pretty much different ends of same problem. We are all humans, not terminators.

> As I already said again we do fix bugs if that happends on Deepin distro and also would love to help other distro port to fix bugs, but once we cannot response very quickly, could you mark it as help wanted or something else so other people may would like to give some love?

- Maybe you should consider to only use final release tags for Arch / Manjaro / Fedora (like we discussed https://github.com/linuxdeepin/developer-center/issues/1093 here) so they would all be at least as stable as Linux Deepin distro, otherwise it will be messy. But i think that you use Arch a lot as testing platform and wouldn't want to loose that (which would make sense, because it's bleeding edge distro by nature).
- Ok then i'd like to tag a lot of my reports. But correct me if i'm wrong, i believe if you're not dev of this github repo - you can't mark it by tags / reopen issues etc.

> I'm sorry my English is very bad (I'm not a native English speaker) and writing a reply also spend me a lot of time on looking up the dictionary, find typo and grammer issue and etc. About documentation which I was working on, I always also spend time to make a English version at the same time. But I still hope some native English speaker can do help about translating, writing tutorials and etc.

That's actually very impressive if it is so, i'm also non-native english speaker but your english seems like actually very good, especially in Linux Deepin OS docs. But anyway, i'm glad that you're aware of it - more english would help a lot to naturally gravitate community devs to this project.

_____

> So maybe it is the right decesion to discountinue archdeepin. I'm serious.

It's the only option left, since @antechdesigns maintains whole Arch Deepin himself, and as non-coder can't really influence Arch or Deepin, outside of bug-reports and heavy testing. But give him a break, guy have bring a lot of new users / testers for Deepin DE, which certainly will improve things in long run.

_____

On a serious note, can you see buggy behavior of terminal for example (after yesterday packages updates) when you minimize / maximize / close it?

I'm pretty sure you can, so not sure what to report here for actually being helpful...
I could do screen record to demonstrate problem but what else is there to actually help quickfix this new bug?

**Comment by antechdesigns** [comment] 2019-06-02 10:29
> > Discountinuing archdeepin
> 
> It seems archdeepin user cannot get any support from nether Arch nor Deepin nor the archdeepin maintainer, fire issue without any useful information but just complains doesn't helps at all. So maybe it is the right decesion to discountinue archdeepin. I'm serious.

You do realise archdeepin is just an installer for arch with the deepin desktop?
So if you install arch 'the arch way' with the deepin desktop or use my installer, your still in the same world of pain.

I have reported bugs and most of them have been ignored:
Example: 13 Feb 2019:
https://github.com/linuxdeepin/developer-center/issues/889
Example: 20 Mar 2019:
https://github.com/linuxdeepin/developer-center/issues/1011

I can post more but you get the idea...

I have even gone as far as not installing `deepin-extra` on the ISO just so people can install their own apps and avoid a lot of bugs.

So if it seems I am complaining, I am, I have good reason too, you will also notice I have not been reporting bugs like I used too for that reason.

The last update was the nail in the coffin for me, I won't be surprised if @oberon-manjaro follows suit.

**Just so you know:**
Me and @keybreak converse with each other over at the Manjaro Forums, after any updates we get together and see whats been fixed, what needs fixing, if we have the same bug/s we report them, because like me @keybreak is passionate about DDE.

All we are trying to do here is make DDE the best UI ...and its so close... well, until the last update)
Just seems we are wasting each others time.

Not trying to disrespect anybody here, just constructive criticism

**Comment by librewish** [comment] 2019-06-02 11:01
well just to comment and curious.
@felixonmars
why the arch  deepin  packages depend on deepin-wm or mutter.
why dont you just build the packages with having deepin-kwin as dependancie rather than let users install it later on.
as its decided it will transit to kwin.
i dont think having two wm is any way beneficial especially an abomination such as mutter.along side kwin.

**Comment by felixonmars** [comment] 2019-06-02 11:05
Because:

1. I don't think the kwin variant is stable enough as of now, so sticking with deepin-wm would be good for newcomers.
2. You can always switch between the two by having the deepin-kwin package installed or not, because the kwin variant always takes precedence. You cannot do it the opposite way: If you have deepin-kwin installed, it will always be used.

Having two variants installed is not good, but not too bad either. We have wayland installed while still using X, too. In the future this will be changed, of course.

**Comment by keybreak** [comment] 2019-06-02 11:33
@BLumia @felixonmars 
I feel you guys would also like to know this and probably influence what's going on:
https://forum.manjaro.org/t/seems-deepin-is-getting-harder-to-keep-supported-by-manjaro/89800

Last thing i personally want is to loose Manjaro Deepin.

**Comment by keybreak** [comment] 2019-06-02 20:23
Here's terminal bug for you we was talking about:
https://bbs.deepin.org/forum.php?mod=viewthread&tid=178715&extra=page%3D1

**Comment by BLumia** [comment] 2019-06-03 03:16
> At the same time i can not agree that those are just random complaints.

The reason I feel like these are **random** complaints because I saw these complaints (not all of them, but some of them actually is) comes with nealy no informations provided but just complaints dev teams "bring new bugs and ignore stability" which really just doesn't help at all which could only let me feel more frustrated.

> Maybe you should consider...

:sweat_smile: We have discussion about that, but just would like to let you know, I'm not a manager or leader and even if I am, I still cannot make the whole workflow change with only myself's opinion.

>  i believe if you're not dev of this github repo - you can't mark it by tags / reopen issues etc.

Maybe I'll write a command bot for adding these tag later, btw maybe you can mark them on manjaro's bug tracker since some of them are Manjaro specific and more Manjaro user can see and help? 

> On a serious note, can you see buggy behavior of terminal for example (after yesterday packages updates) when you minimize / maximize / close it?

I'm verrrry sorry about this issue since I reviewed this submit. Actually I tested it locally and it works fine on my machine. We'll revert the related submit later and you can track this issue in the following issue:

Bug related to the terminal: https://github.com/linuxdeepin/deepin-terminal/issues/168 & https://github.com/linuxdeepin/deepin-terminal/issues/169

> *quote from [Seems Deepin is getting harder to keep supported by Manjaro](https://forum.manjaro.org/t/seems-deepin-is-getting-harder-to-keep-supported-by-manjaro/89800/2):*
> porting to an "unsupported" platform is a lot of work and including development changes

This is the fact, by the way there actually are very less contributers from the user community (it's understandable, though) and current nearly all porting issue are processed by developers from Deepin. So actually I am still looking for a good way to encourage more community contributers to take part in the development -- whatever the Deepin maintained one or a new fork.

**Comment by antechdesigns** [comment] 2019-06-03 09:59
I am going to close this, I feel I have said all I need to say and I doubt anything will change.
We have already been here before and it feels like we are just going round in circles which is futile.

I have spent many man hours creating archdeepin which I feel has all been a waste of time. I have not done all this work just so I can 'complain' they are legitimate concerns, if only to improve the DDE:

https://sourceforge.net/projects/archdeepin/
https://antechdesigns.000webhostapp.com/

Most of mine and @keybreak bugs have been ignored, while other bugs have made their way in making deepin unusable at this point. Also feature requests seem to take priority over bug fixes??

Example:
There was absolutely nothing wrong with deepin-terminal and in the blink of an eye its ruined, it would be interesting to know what you were fixing for this to happen?
https://github.com/linuxdeepin/developer-center/issues/1264 its even on deepinOS not just arch, how this got through is beyond me, this can not of been tested and if it had, maybe you should look into how you do testing, I spotted it in the first 30secs after boot up.

and yet you still can't edit a file as root with deepin-editor https://github.com/linuxdeepin/developer-center/issues/889

Unless something drastic happens in the next week I regret to say I will be saying goodbye to deepin.

Thank you all and I wish you luck ;)

**Closed** 2019-06-03 09:59 UTC

**Comment by BLumia** [comment] 2019-06-03 10:09
> #1264 its even on deepinOS not just arch,

Hey we didn't even release any update for Deepin for around two weeks, why did you even say that?

> Most of mine and @keybreak bugs have been ignored

Did you know why I feel frustrated? While we are not ignore any bug but you said we did. We both do not want that happend but just limited time and resource to work on a non-profit community version, if nether you nor I have time or ability to fix a bug very timely, what's the point to say we "are ignored" them? Did you think we do this on purpose?

Anyway, wish you luck too.

**Comment by antechdesigns** [comment] 2019-06-03 10:42
@BLumia 

My point was, there was nothing wrong with deepin-terminal until the update: 

**Updated 1st June 2019:** `deepin-terminal 3.2.5-1`

You spent 'limited time and resources' on fixing something that wasn't even broken, that limited time could of been spent fixing, lets say this: https://github.com/linuxdeepin/developer-center/issues/889 which is a simple fix, by all accounts.

I can only say what I see and I am not the only one, something really needs to change? 
If you tell me its always going to be that way, say so and I will move on, lets stop wasting everybody's time.

**Comment by BLumia** [comment] 2019-06-03 11:29
> on fixing something that wasn't even broken

No,

1. That commit *is* intended to fix another bug in a internal bug tracker which QA team reported.
2. We get paid to working on bugs which QA term reported.
3. Since you said #889 which is a simple fix, could you please fix it and submit a patch? I do not fimilar with DBus policy so I really couldn't fix it unless read some doc and learn it first.

> something really needs to change?

Yes. could **you** please stop bring negative complain to other contributers who would love to contribute? I am also a volunteer who contribute on Deepin community version on my spare time, other contributer and even other deepin-dev did, why did you so bad and blame them just because they may made some miskate?

**Comment by antechdesigns** [comment] 2019-06-03 11:39
> Yes. could **you** please stop bring negative complain to other contributers who would love to contribute? I am also a volunteer who contribute on Deepin community version on my spare time, other contributer and even other deepin-dev did, why did you so bad and blame them just because they may made some miskate?

Consider it done my friend...

Bye everybody & Good Luck ;)
