### ISSUE TITLE
[deepin 23 Beta] Downloader has an error

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#3985] opened 2023-04-03 00:55 UTC
### SUMMARY | 问题概要

When starting any download, the application displays the message that there is no space available (even having several gigabytes available). When changing the storage location (disk), the message is still displayed.

![Capturar_downloader_20230401152901](https://user-images.githubusercontent.com/45263160/229389243-a5ba77c8-dbdc-4da4-b6f0-dd4cad2ddf27.png)

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin 23 Beta (OsBuild=21238.100)

org.deepin.downloader 5.3.69

### PRE-REQUIREMENT | 预置条件

This information is unnecessary.

### STEPS TO REPRODUCE | 复现步骤

This information is unnecessary.

### OBSERVED RESULT | 观察到的结果

This information is unnecessary.

**Comment by BLumia** [comment] 2023-04-04 01:46
I cannot reproduce this issue. Since no STEPS TO REPRODUCE was given, I'll mark it as need more info.

Please note that the information is to make someone else other than you to be able to reproduce the issue, or we won't be able to fix it...

**Comment by lxwndr** [comment] 2023-04-04 01:54
@BLumia Try any .torrent download or magnet link.

**Comment by babyfengfjx** [comment] 2023-04-12 06:10
We apologize that the downloader project has been transferred to maintenance, and there may not be anyone available to optimize related issues at the moment. However, we will log this issue, and there may be updates when someone is available to address it in the future.

**Comment by babyfengfjx** [comment] 2023-04-12 06:11
@SuperEffie  可以提单跟踪。

**Comment by SuperEffie** [comment] 2023-05-04 08:44
Thank you for your feedback.
 We have not reproduced your question in the latest the version 5.3.70 downloader. We can download the. torrent download or magic link file normally.
![下载器](https://user-images.githubusercontent.com/58986464/236154688-3e778b84-f185-421c-a10e-c51ba342dc1b.jpg)

**Comment by BLumia** [comment] 2023-05-04 09:13
So it's still in "cannot reproduce" status then :p

If you have any additional information that can help others reproduce the issue, please feel free to let us know. Thanks!

**Closed by BLumia** 2023-05-04 09:13 UTC
Labels: triage | need more information
