### ISSUE TITLE
Deepin File Manager missing "Open As Admin" Option on right click

### ISSUE THREAD

**Issue by Y0ngg4n** [linuxdeepin/developer-center#1770] opened 2020-06-18 15:55 UTC
With Deepin 20 i am missing the option to open the File Manager as Admin/root

![image](https://user-images.githubusercontent.com/30302975/85043493-b77a3a00-b18c-11ea-8980-eed114ac1d7b.png)

**Comment by xmuli** [comment] 2020-06-19 01:23
Linux is strictly privileged (unlike win); Menu is not designed that way (not a bug), and of course, you can try sudo to open a file.

**Comment by Y0ngg4n** [comment] 2020-06-19 15:20
Shure i know this. But i can remember there was this Button in Deepin 15 and it was very useful. You just entered your sudo Password and got an elevated File Manager.

**Comment by alexwender1** [comment] 2020-06-25 23:09
> Linux is strictly privileged (unlike win); Menu is not designed that way (not a bug), and of course, you can try sudo to open a file.

This feature is very useful and the File Manager has been praised for bringing this feature in a practical way (it is activated with a click).

Having to resort to the Terminal (sudo dde-file-manager) to do the same thing, it's not practical.

If possible, talk to the team and review this position. When in doubt, consult the community opinion.

**Comment by xmuli** [comment] 2020-06-28 02:40
Okay, I'll talk to the designer and see if we can consider adding admin rights to the deepin community edition, in the context menu.

**Comment by vesterlay** [comment] 2020-08-18 18:24
I'm really missing this feature and It's essential to have an ability to freely view files as root, **especially** on Linux. Revoking the easy way of having full control over your device kind of breaks Linux philosophy.

Apart from file manager topic, I'm really interested about deepin editions. Can you tell more about it? I'm very curious why wouldn't you implement this functionality on all versions. How many of them are anyway?

**Comment by xmuli** [comment] 2020-08-19 02:28
In the new version plan, I see that the "Add Administrator Privilege Open" function has been added;

This function was not added later, probably because the uos version has stricter management of sudo permissions (for users who don’t understand computers), which later led to the disappearance of this function

**Comment by xmuli** [comment] 2020-12-07 08:46
This feature has been integrated into dde-file-manage and is already enabled on UOS and Deepin. (But no one has come to close this issue )

![image](https://user-images.githubusercontent.com/33887845/101328979-b9a39280-38ab-11eb-8a0f-f10934793dac.png)


![image](https://user-images.githubusercontent.com/33887845/101328742-629dbd80-38ab-11eb-8e2c-408e308d75c9.png)

**Closed by xmuli** 2020-12-07 08:46 UTC
Labels: place | CD, suggest | functional behavior
