### ISSUE TITLE
a lot of issues with new update ( 20.02)

### ISSUE THREAD

**Issue by imHamo** [linuxdeepin/developer-center#2746] opened 2021-04-02 11:46 UTC
A popping audio while using My bluetooth headphone
keep list to it every 3 - 2 seconds
when i connect my bluetooth headset i keep listen to Popping Sound every 3-4 second

i tried powersave tricks . all that but didn't work :/

i'm able to mute it by go to sound settings >> sound effect >> voulme +/- and remove it

so i hope this get fixed in next update. thanks for hard work

**Comment by BLumia** [comment] 2022-03-28 05:52
Sorry for the super late response since we were not looking into issues that were reported outside the developer-center repo.

Now we are on deepin v20.4 and v20.5 will be released in the upcoming days. Since I cannot reproduce this issue and we are processing a huge amount of issues that were transferred from other repos. If you still have this issue, please consider creating a new issue with the necessary detailed information provided, so we could look into it. Thanks.

**Closed by BLumia** 2022-03-28 05:52 UTC
