### ISSUE TITLE
Manjaro - Unable to set sound output after the last update.

### ISSUE THREAD

**Issue by orarugogerincufelpattano** [linuxdeepin/developer-center#1881] opened 2020-08-27 14:55 UTC
## Describe the bug
Since the last Manjaro update (around a week ago) which included Deepin UI components,  I'm no longer able to set which device should output sound.

## To Reproduce
1. Go to Settings -> SOUND -> SPEAKER 
2. In the **Output Devic**e drop down menu try to set a different output device

## Expected behavior
In the previous Version there was an advanced menu entry in the sound menu. There was a list of available devices, where one could pick the preferred output device.
Now it is replaced with a drop down menu directly in the Speaker sub menu but this menu is completely empty. So it is not possible to set a different device.

## Screenshots

![Deepin_Sound_Problem](https://user-images.githubusercontent.com/66918646/91456666-d4fe0b00-e883-11ea-9e4d-04ce9ecfd43f.png)

### Distro & Version
Manjaro Linux 20.1

### Related package version
deepin-control-center 5.3.0.9-1

### Additional context
I made no changes on the hardware. I have 2 Bluetooth headphones, a Monitor with sound output and an SPDIF Sound output. All of them worked fine before the UI Change.

**Comment by juteman** [comment] 2020-08-28 01:08
Duplicate of #1862

**Comment by vesterlay** [comment] 2020-08-29 23:17
How did you install Manjaro deepin? @orarugogerincufelpattano

**Comment by orarugogerincufelpattano** [comment] 2020-08-30 08:39
I have 2 PCs with Manjaro Deepin. One I installed years ago when there was an installer for it. The other (newer one) I installed with Manjaro architect with XFCE and added the Deepin DE afterwards.

**Comment by xmuli** [comment] 2020-08-31 02:09
#293 duplicate

**Comment by orarugogerincufelpattano** [comment] 2020-09-08 21:23
SOLVED. The lastest Manjaro Deepin update solved this problem. The **Output Device** selector is now working as intended. Many thanks! :-)

**Comment by xmuli** [comment] 2020-09-09 02:26
nice

**Closed by xmuli** 2020-09-09 02:26 UTC
Labels: Solved | resolved, bug | Ports, duplicate | repeat or similar
