### ISSUE TITLE
Bug report - Unable to launch applications

### ISSUE THREAD

**Issue by mitchellkrogza** [linuxdeepin/developer-center#1928] opened 2020-09-29 07:50 UTC
Latest version leaves us unable to launch ANY applications from Launcher NOT even control center.

You also introduced a screenlock over-riding my previous settings which I can now NOT disable because I cannot launch system settings.

You also messed up ALL existing bookmarks forcing me to recreate them all.

So many bugs and seems nothing was tested before pushing a new release out.

**Comment by xmuli** [comment] 2020-09-30 09:38
Please bring a detailed description, including version information, re-steps, etc., so that it is easy to close the issues (causing confusion).

**Comment by orarugogerincufelpattano** [comment] 2020-10-02 15:17
I have the same Problem. Since the last update two days ago, I am also unable to start apps from the launcher when the launcher is in full screen mode. When it is in small mode (lower left corner), it works correctly.

**To Reproduce:** start any app from the launcher if the launcher is in full screen mode.
It should open the app you click on but on my machine nothing happens. Starting apps from the small launcher works.

**Enviroments:**
**Distro & Version:** Manjaro, 20.1.1 - Mikah
deepin-desktop-base 3:2019.07.10-1 
deepin-desktop-schemas 5.8.0.20-1
deepin-desktop-schemas 5.8.0.20-1
deepin-kwin 5.2.0.2-2
**deepin-launcher 5.3.0.13-1**
deepin-qt5integration 5.1.0.7-2 
deepin-session-ui 5.3.0.10-2
deepin-turbo 0.0.3-2
deepin-wm 1.9.38-4
plymouth-theme-manjaro-deepin-circle 1.0-4
startdde 5.6.0.1-1

**_deepin-mutter 3.20.38-4_** Why is this installed, when Deepin uses KWIN? 

If you need any more information, please ask specifically.

**Comment by mitchellkrogza** [comment] 2020-10-03 08:58
Thank you @orarugogerincufelpattano I didn't even know the small launcher existed until now. I prefer it so much over the full screen environment. Thank you !!! I can now launch everything again without command line.

**Comment by KimHono** [comment] 2020-10-17 18:29
It's  the same problem as issue #1919

**Comment by peeweep** [comment] 2021-12-29 08:47
This problem has been fixed in the latest version of Deepin, if you still have problems, you can reopen this issue.

**Closed by peeweep** 2021-12-29 08:47 UTC
