### ISSUE TITLE
chrome window and multitasking view (animation bug)

### ISSUE THREAD

**Issue by wep777** [linuxdeepin/developer-center#1759] opened 2020-06-05 16:50 UTC
## Describe the bug
Chrome Window twitches after switching to it

## To Reproduce

0. Open 5-6 windows and open google-chrome
1. Go to multitasking view mode
2. Click on some window (not chrome)
3. Go to multitasking view mode
4. Click on chrome window
5. See animation bug
(doesn't always work from 1 time, try different windows and a chrome window)
(in my case bug present when i switch from deepin file manager and chrome)

### Distro & Version
Linux Deepin 20 beta

**Comment by wep777** [comment] 2020-06-05 17:26
![Screen Capture_dde-desktop_20200605212437](https://user-images.githubusercontent.com/16454901/83905755-43469c00-a773-11ea-9cc7-77a1cdfa4a8c.gif)

**Comment by Zeno-sole** [comment] 2022-01-10 07:26
20.3 did not reproduce your problem, please upgrade to 20.3 to try

**Comment by Zeno-sole** [comment] 2022-02-11 08:19
Due to no reply for a long time and lack of necessary information, close the issue, If the problem still exists, you can apply to reopen the issue

**Closed by Zeno-sole** 2022-02-11 08:19 UTC
Labels: other | need confirmation, bug | functional behavior
