### ISSUE TITLE
Deepin Sound System is full of bugs 

### ISSUE THREAD

**Issue by imHamo** [linuxdeepin/developer-center#2754] opened 2021-06-03 12:45 UTC
Hello until now i found about 3 Annoying bugs. so i will leave this report here i know it will take a time to get fixed but i hope it get fixed at the end

Deepin 20.2 : 
 

**FIRST BUG :** 

There A popping sound When Bluetooth Headset Turned on when i try use my bluetooth headphone

There a sound of ( Volume up sound key ) keep popping every 3 seconds

To fix this i had to make this OFF 
![image](https://user-images.githubusercontent.com/79617976/120646689-10b0ab80-c47a-11eb-8ffb-62c1503eefdc.png)

**Second BUG**  : 

Bluetooth Auto Connect Not Work
When i turn my Headphone ON , Deepin automatic connect to my headphone but it's not really connected
it show as " Connected" but it's not connected / and there no headset in audio output

which i need to Disconnect And Re connect Manually 

**Third BUG :** 

Sometimes Sounds comes from 2 input at same time ( i have face this a lot and a alot)

while i watch netflix and browse a video on facebook

i found a sound come from my Headphone and other video sound comes from my Sub 
and this weird. and happen a lot but random

i hope this bugs move to right section and dev know about it . so they can fix it , Thanks for great work

**Comment by BLumia** [comment] 2022-05-11 07:06
Does this still happens on deepin v20.5?

**Comment by NjlsShade** [comment] 2022-05-30 05:47
I am often having issues where sound will be playing from the wrong output device for some apps. System sounds and my web browser will be outputting to my USB headphones, while opening Deepin Movie will output through my AUX speakers.

I also have experienced sound not working at all after using Deepin for many hours nonstop, restarting PulseAudio does not seem to fix it, I have to physically unplug my USB headphones and plug them back in to get it working again.

Sadly I don't have any information outside of my statement, but I'll update this issue if I find any way of reliably replicating the issue. Just wanted to confirm I'm also seeing issues regarding audio.

**Comment by babyfengfjx** [comment] 2022-06-02 08:09
We are very sorry that we did not pay attention to the issue before, on the currently used devices, no similar issue has been found for the time being, we will expand the scope of testing, and hope to find a way to reproduce the problem, thank you very much for your feedback.

**Comment by SuperEffie** [comment] 2023-02-13 07:50
Sorry  for that we cannot reproduce it under version deepin 20.8. Due to no reply for a long time ,closing this issue for now. If the problem still exists, please consider prvoide the necessary information to reopen the issue, or creating another issue.Thank you~
Best wishes!

**Closed by SuperEffie** 2023-02-13 07:50 UTC
