### ISSUE TITLE
Log Viewer does not export logs

### ISSUE THREAD

**Issue by lxwndr** [linuxdeepin/developer-center#1983] opened 2020-11-24 00:32 UTC
Since the launch of the application, the option to export the logs has never been available; making it difficult to send feedback to developers.

When clicking on export logs, only one "Exporting..." screen is displayed and the file is not generated / exported:

![Captura de Tela_deepin-log-viewer_20201123211704](https://user-images.githubusercontent.com/45263160/100030432-43def780-2dd2-11eb-84ec-783315b042a9.png)

deepin-log-viewer 5.8.0.24-1
deepin 20 (1003 Update 1) / OsBuild=11031.106

**Comment by alexwender1** [comment] 2020-12-30 18:28
The problem persists in the new version: deepin 20.1 (1010) / OsBuild=11031.108

**Comment by z966768** [comment] 2021-03-01 02:44
Please check the export location, whether you have permission ，maybe you can try the newest version

**Comment by lxwndr** [comment] 2021-03-01 12:26
> Verifique o local de exportação, se você tem permissão, talvez você possa tentar a versão mais recente

I use the latest version (below) available in the repository. This function has NEVER worked for users.
_Note: By default, I save to the desktop. I have already tried to save to the Downloads folder and the partition of my personal files and was unsuccessful._

deepin-log-viewer 5.8.0.28-1
deepin 20.1 (1030) / OsBuild=11038.003

**Comment by babyfengfjx** [comment] 2022-02-15 06:20
Hi, this problem will you still appear in the latest version?Currently testing everything in new devices is ok, I don't know if your problem is fine.

**Comment by lxwndr** [comment] 2022-02-16 00:30
I'm using the latest version (deepin-log-viewer 5.8.31) and the problem persists!

It is important to state that this problem has always existed since the app was launched.

**Comment by babyfengfjx** [comment] 2022-02-16 02:56
- Are you using the Deepin V20.4 version?
- Currently, cannot revert, using everything is normal,i don't know if any other necessary conditions?
- try to uninstall  and reinstall ?

**Comment by lxwndr** [comment] 2022-02-16 22:50
Yes, I am using the latest version of the application and the system (as attached). It is important to point out that I reinstalled the system a short time ago and this problem has always occurred (old installation and new/current installation).

I believe this is because of the language or time zone.

![Capturar_deepin-terminal_20220216191431](https://user-images.githubusercontent.com/45263160/154370484-2aecded4-f0f5-4a34-87e5-f4c75a7d531e.png)

I run the application through the Terminal, maybe there is information about the problem:

![Capturar_deepin-terminal_20220216194854](https://user-images.githubusercontent.com/45263160/154370776-b8f977b1-ebe6-4495-bdfa-842b67246fc0.png)

**Comment by babyfengfjx** [comment] 2022-02-17 01:04
OK , can you tell me the system language and time zone information you use, I see if I can reproduce this problem?

**Comment by lxwndr** [comment] 2022-02-17 01:58
Language: Brazilian Portuguese [pt-BR]
Time Zone: GMT-3 (Sao Paulo)

**Comment by z966768** [comment] 2022-02-17 05:21
please run the application through the Terminal,then export log,and show the screenshots of Terminal @lxwndr

**Comment by z966768** [comment] 2022-02-17 06:12
This problem arose after we switched the language to "Brazilian Portuguese [pt-BR]",there is a solution now, please be patient for the next version.
Thanks for your feedback @lxwndr

**Comment by babyfengfjx** [comment] 2022-02-22 09:43
> Language: Brazilian Portuguese [pt-BR] Time Zone: GMT-3 (Sao Paulo)

- This issue is resolved in the 5.8.32 version;
- If you confirm the problem solving, you can  close the issue.

**Comment by babyfengfjx** [comment] 2022-03-04 02:47
Since we have not been in touch for a long time, we will close the issue first. If there is any problem later, you can submit the issue in time. Thank you for your feedback.

**Closed by babyfengfjx** 2022-03-04 02:47 UTC
Labels: bug | functional behavior
