### ISSUE TITLE
[BUG] deepin-editor History keeps messing

### ISSUE THREAD

**Issue by N1coc4colA** [linuxdeepin/developer-center#3096] opened 2022-04-16 07:55 UTC
### Text history mixes every parts while moving in file's edition history
If you use Ctrl+Z (cancel edits) and Ctrl+Shift+Z (cancel the cancelled edition) some parts goes where it was not.

### STEPS TO REPRODUCE | 复现步骤
Just play with file's edition history.

### OBSERVED RESULT | 观察到的结果
When I work on my python files, and not only that, it is really annoying to have to build and check all the file again, as I mostly have files with thousands lines.

### EXPECTED RESULT | 期望的结果
Have the right parts where it should be.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息
Deepin 20.1

Moreover, I don't know if it has been fixed in newer versions.

**Comment by BLumia** [comment] 2022-04-16 08:13
> Deepin 20.1

Hi, please consider upgrade the system since a lot of fixes were landed and we are now on deepin v20.5 now :)

**Comment by BLumia** [comment] 2022-04-18 01:21
Does it still exist if you upgrade to deepin v20.5? I cannot reproduce this issue on my v20.5 installation with `deepin-editor 5.10.14-1`. By the way, the default re-do shortcut is <kbd>Ctrl+Y</kbd> instead of <kbd>Ctrl+Shift+Z</kbd>.

**Comment by BLumia** [comment] 2022-05-11 02:14
Closing since no future response and not reproduceable. If you believe this can be reproduced, please consider creating a new issue with more detailed information so we can look into it. Thanks!

**Closed by BLumia** 2022-05-11 02:14 UTC
Labels: other | need confirmation
