### ISSUE TITLE
Blur effect doesn't work properly in some conditions on Arch Linux

### ISSUE THREAD

**Issue by gustavodlima** [linuxdeepin/developer-center#195] opened 2017-03-13 16:23 UTC
Blur effects doesn't work properly when using background with higher resolution and keep not working properly if using some of the defaults backgrounds or other background with "lower resolution" just on menus like right click on desktop or right click on something else. Blur effect just starts cluttering.

I've tried to modify `/home/$USER/.xinitirc` from `exec startdde` to `exec optirun startdde` to guarantee that is nothing with bad compatibility with Intel HD Graphics, but nothing really happens, still got the blur effect messy.

Video: Nvidia 930m + Intel HD 5500.
Nvidia driver version: 378.13.
Wallpaper resolution: 5120x3684.

Prints:

Generic blur effect when anything else is behind the launcher if not the desktop background:
![deepinscreenshot20170313113933](https://cloud.githubusercontent.com/assets/14314943/23862940/4ad7e98e-0806-11e7-9a6f-f9ef10d3d8b5.png)

Just started a random application and launcher got like this:
![deepinscreenshot20170313123451](https://cloud.githubusercontent.com/assets/14314943/23862943/4aefba50-0806-11e7-8aee-33539fbb7fe2.png)

I open Control Center and because of Deepin Dock, this area became like this:
![deepinscreenshot20170313123728](https://cloud.githubusercontent.com/assets/14314943/23862941/4adb9e4e-0806-11e7-9284-d5f050f07f4a.png)

Notification is affected too just when the window is focused:
![deepinscreenshot20170313130017](https://cloud.githubusercontent.com/assets/14314943/23862942/4addcee4-0806-11e7-91bc-508f89467ecd.png)

EDIT: Seems related to #158, idk.

**Comment by pablomancera** [comment] 2017-03-14 01:07
Same here, but mine looks worse
![deepinscreenshot20170314010220](https://cloud.githubusercontent.com/assets/26395881/23881464/7f5f3526-0852-11e7-959c-56abc441ea42.png)

**Comment by sonald** [comment] 2017-03-14 09:48
@gustavodlima  @pablomancera it is known problem on Arch, will be fixed later. This is related to deepin version of clutter.

**Comment by gustavodlima** [comment] 2017-03-16 03:00
@sonald Oh, ok. There's a patch for it available on Deepin repos? If so, maybe I can port it to Arch.

**Comment by felixonmars** [comment] 2017-03-16 06:47
@gustavodlima Fixed in the deepin-clutter package, please replace clutter with the new package during a normal upgrade.

**Comment by beauraF** [comment] 2017-03-16 17:42
Hi,

@felixonmars the problem seems to persist : 

`deepin-clutter-1.26.2-1 est à jour`

![captureecrandeepin20170316133619](https://cloud.githubusercontent.com/assets/12185788/24010404/22a75c52-0a4e-11e7-9d34-1502d08a59ac.png)

**Comment by gustavodlima** [comment] 2017-03-16 21:21
@felixonmars Thks, it worked for me. :+1:

**Comment by felixonmars** [comment] 2017-03-17 06:08
Oops, sorry for the inadvertent reopen...

**Closed by felixonmars** 2017-03-17 06:08 UTC

**Comment by quadpixels** [comment] 2017-09-22 17:03
This issue happens when installing DDE over Xubuntu 17.04 as well, and can be reproduced on 3 different configurations:

For me this can be fixed by compiling "Deepin Clutter 1.26" ( [source repository here](https://github.com/sonald/clutter) ) and replace the one in the system (`/usr/lib/x86_64-linux-gnu/libclutter-1.0.so.0` is the location Ubuntu decides to keep it.)

![shadowartefactfix](https://user-images.githubusercontent.com/1406681/30755896-ede26d88-9f8d-11e7-9324-f59c4315493d.png)

Yummy !  :+1:

p.s. I had observed the same issue when playing with Compton's shadow & blur effects as well (looks like the dirty rectangles behind a blurred region affects the pixels on the blurred bitmaps) but I'm not sure of whether it was due to Clutter as well.

**Comment by sonald** [comment] 2017-09-30 08:22
my clutter fork is specialized for the blurring effect of deepin-wm (backed by deepin-mutter). I dont think compton need this.

**Comment by quadpixels** [comment] 2017-09-30 20:28
Thanks for the explanation! It seems there is a lot for me to learn about desktop environments and compositors ...

**Comment by dreszczyk** [comment] 2018-04-04 09:28
This problem still occurs on new Deepin installation. Is there any fix for this?
