### ISSUE TITLE
Use this kwinrc

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/developer-center#1777] opened 2020-06-24 17:03 UTC
Current kwin effects are inconsistent.

Instead use this [kwinrc](https://github.com/linuxdeepin/developer-center/files/4826895/kwinrc.txt) or similar.

**Comment by gardotd426** [comment] 2020-06-26 10:42
What effects are you talking about? Do you have a screenshot of an example?

Plus, this kwinrc seems to disable many of them, at least for KDE (which can just be disabled in the settings GUI). 

There's also no `[deepin-chameleon]` section. But I imagine that would get set the first time you change something in Personalization anyway.

**Comment by es20490446e** [comment] 2020-06-26 15:16
I think it would be better if you simply try.

**Comment by gardotd426** [comment] 2020-06-27 02:07
What are you talking about? I'm using Deepin DE right now, and I don't see any issues with effects.

**Comment by gokhanyildirimlar** [comment] 2020-06-27 09:41
If the default configuration doesn't work well for you, you are free to do customize it. But this doesn't mean that everybody else is having problems. I don't have an issue with KWin but even if I had, this is not a solution. You can't impose a customized KWin configuration file. So this is not an option. Defaults are being set for the majority, not for individuals.

**Comment by es20490446e** [comment] 2020-06-27 12:20
I mean with the default config animations are overly slow, and common actions like opening a window don't animate at all.

**Comment by gardotd426** [comment] 2020-06-27 12:23
Then file a bug report, because that's not intended behavior. 

@gokhanyildirimlar is right, this isn't really how things are supposed to work. 

What would help is if you would point out what you changed that made the animations work/improve, because I guarantee that all of the changes to the kwinrc aren't necessary, if anything that would only be affected by one or two of the lines.

**Comment by es20490446e** [comment] 2020-06-27 12:41
I changed almost everything, and the kwinrc you see is as I would leave it.

Perhaps the hashes of the desktop I would remove, but even the opengl version I would keep.

**Comment by gardotd426** [comment] 2020-06-27 12:44
That's not what I'm asking. 

My kwinrc literally only has like 12 lines, and my animations work fine. 


```
cat ~/.config/kwinrc
[Compositing]
Enabled=true
OpenGLIsUnsafe=false

[Desktops]
Id_1=1fd6feed-6a26-42a9-9974-1bce9a330bff
Id_2=c6d66ffd-929d-4cb1-94ea-fda3b8c89a59

[Script-closewindowaction]
BorderActivate=

[Script-runcommandaction]
Border7Program=dbus-send --session --dest=com.deepin.wm --print-reply /com/deepin/wm com.deepin.wm.PerformAction int32:6
BorderActivate=,7

[deepin-chameleon]
theme=dark/deepin
```

Obviously you can't use those device ids for the monitors, but that's all that should be needed.

**Comment by es20490446e** [comment] 2020-06-27 12:49
I think that if you don't try the animations of both configurations yourselves you won't understand.

**Comment by gardotd426** [comment] 2020-06-27 15:30
@es20490446e what are you talking about? Both configurations? What other configuration? Mine works out of the box, that config up there is the one deepin's given me (after tweaking the settings in the Control Center). 


I don't know if you're not quite grasping this or what, but almost none of those options are going to be used by `deepin-kwin`, you don't need hardly any of them.

**Comment by justforlxz** [comment] 2022-02-03 09:38
I looked at the configuration file you provided, we usually don't preset too many values because we want to use the default configuration provided by kwin. This is a minimization principle.

So I'll review this config file with others and pick whichever ones we think are helpful, and then I'll close this issue, thanks a lot.

**Comment by justforlxz** [comment] 2022-03-31 08:27
Sorry, in the end we decided not to use your profile.

**Closed by justforlxz** 2022-03-31 08:27 UTC
Labels: other | need confirmation
