### ISSUE TITLE
Wallpaper shortcut duplicated every time it is applied

### ISSUE THREAD

**Issue by NjlsShade** [linuxdeepin/developer-center#3168] opened 2022-05-21 02:38 UTC
### SUMMARY | 问题概要

When applying a specific image as the wallpaper, then reapplying it using the shortcut created in the wallpaper selector, it causes the shortcut to be duplicated, over and over.

### STEPS TO REPRODUCE | 复现步骤

1. Set this image as your wallapaper
![Screenshot_20220520221411](https://user-images.githubusercontent.com/15788214/169630772-76a81616-3d3a-465a-8684-c1baf5cb1566.png)

2. Open the wallpaer settings
![Screenshot_20220520221445](https://user-images.githubusercontent.com/15788214/169630797-5934461e-d482-4808-816b-a8ebc4aa5aa9.png)

3. Apply the same wallpaper again using the shortcut for it
![Screenshot_20220520221452](https://user-images.githubusercontent.com/15788214/169630855-9b3d6800-e5b0-4224-a63d-5ffc1f1ebb3f.png)

4. There is now a duplicate shortcut for the wallpaper
![Screenshot_20220520221501](https://user-images.githubusercontent.com/15788214/169630887-c3f09cb6-5cf4-4827-99d7-b4efda57bbb1.png)

5. You can see it will just keep incramenting
![Screenshot_20220520221516](https://user-images.githubusercontent.com/15788214/169630906-46f741d5-6742-4f2b-812a-f4316ef919da.png)

### OBSERVED RESULT | 观察到的结果

It does not happen with every Image, however, the one I have attached works every time.

### EXPECTED RESULT | 期望的结果

Shortcut for the image I set should not be duplicated.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Using the latest deepin 20.5 freshly installed and updated.

This is the image I used to reproduce this:
![test](https://user-images.githubusercontent.com/15788214/169631061-3268b30b-c60a-44f5-8db3-4a10b5b4ceb3.png)

**Comment by BLumia** [comment] 2022-05-23 03:08
Can be reproduced under deepin v20.5 with `dde-file-manager 5.5.10-1`, but cannot reproduce with v20.6 `dde-file-manager 5.6.3-1` (tag not released yet).

deepin v20.6 is in closed beta stage and should be released in the end of this month, so it will hopefully be resolved after release. If you are interested in join the beta testing, you can also check out https://bbs.deepin.org/post/236479 :)

**Comment by NjlsShade** [comment] 2022-05-31 01:14
Just an update, using dde-file-manager 5.6.3 on the live deepin 20.6 and am still able to replicate the issue on my end.

**Comment by BLumia** [comment] 2022-05-31 03:20
Yeah you're right it's still reproduceable with the final released `dde-file-manager 5.6.1-1`. @babyfengfjx could you take a look?

**Comment by luodeepin** [comment] 2023-02-01 05:38
在 20.8发布环境中，没有复现到这个问题

**Closed by luodeepin** 2023-02-01 05:38 UTC
Labels: bug | functional behavior, project: dde-file-manager

**Comment by NjlsShade** [comment] 2023-02-03 07:22
I am still able to reproduce this using a fresh install of Deepin 20.8. Video example bellow:

[test.webm](https://user-images.githubusercontent.com/15788214/216537437-7c04cdc6-e8a5-4c87-b041-c6f5eadf7486.webm)
