### ISSUE TITLE
File Manager Doesn't Access Samsung Devices.

### ISSUE THREAD

**Issue by sarojpoudel33** [linuxdeepin/developer-center#758] opened 2018-12-28 00:29 UTC
## Describe the bug

Trying to access my Samsung Devices so that I can transfer a movie to my laptop. Reading around, it seems I need to change something to give it access? And no, not talking about granting and allow access from the phone itself. Any help is appreciated! -by robertsala 

## To Reproduce
You can Try Own so You better to know Bugs.

## Expected behavior

*A clear and concise description of what you expected to happen.*

## Screenshots

*If applicable, add screenshots to help explain your problem.*

### Distro & Version

Linux Deepin 15.8+4 latest]

### Related package version

dde-file-manager latest version 4.7.1.10 
![photo_2018-11-16_12-16-23](https://user-images.githubusercontent.com/45546591/50498318-c4224400-0a67-11e9-8e48-df679d5823ed.jpg)

*If you are not sure about which package went wrong, you can provide a list of package and it's version which you thinks is probably related with your issue*

### Additional context

*Add any other context about the problem here. It will be very helpful for us to isolate the problem. We will ask for more details when needed so feel free to remove this section if you really don't know what to provide.*

**Comment by BLumia** [comment] 2018-12-30 13:59
https://github.com/linuxdeepin/dde-file-manager/issues/4

Probably the same reason. the `URI` which gvfs returned (`[usb:001,016]`) is not a valid `QUrl`.

Could you provide a log for this issue? thx.

**Comment by SiamSami** [comment] 2019-02-26 17:12
That's a Samsung device. That problem has been fixed. Just wait for the next update.
@sarojpoudel33 Can you close it?

**Comment by BLumia** [comment] 2019-02-27 01:09
> That's a Samsung device. That problem has been fixed [linuxdeepin/dde-file-manager@ef95c92](https://github.com/linuxdeepin/dde-file-manager/commit/ef95c920cc7b83f35cf7fddb5a1d51a204a465a4).
> Just wait for the next update.
> @sarojpoudel33 Can you close it?

I'm not sure about if it's the same issue, could be better if @sarojpoudel33 can test it out after next release.

**Comment by sarojpoudel33** [comment] 2019-02-28 02:03
> That's a Samsung device. That problem has been fixed [linuxdeepin/dde-file-manager@ef95c92](https://github.com/linuxdeepin/dde-file-manager/commit/ef95c920cc7b83f35cf7fddb5a1d51a204a465a4).
> Just wait for the next update.
> @sarojpoudel33 Can you close it?
I am sure i can access device but cant transfer file.

**Comment by sarojpoudel33** [comment] 2019-03-11 09:51
[samsung Bug.mp4.zip](https://github.com/linuxdeepin/developer-center/files/2951583/samsung.Bug.mp4.zip)

**Comment by sarojpoudel33** [comment] 2019-03-11 09:53
Unable to transfer files between deepin and  Samsung Devices. @BLumia

**Comment by BLumia** [comment] 2019-03-13 06:37
Need some help since I really didn't have any Samsung device to reproduce this issue :(

**Comment by SiamSami** [comment] 2019-03-13 15:33
> Unable to transfer files between deepin and Samsung Devices. @BLumia

That's a different issue. It has already been opened here, #975

**Comment by BLumia** [comment] 2019-03-14 02:06
> That's a different issue. It has already been opened here, #975

Seems fair enough. Closing.

**Closed by BLumia** 2019-03-14 02:06 UTC
Labels: help wanted, info needed
