### ISSUE TITLE
Deepin-draw asociates itself with all types of files

### ISSUE THREAD

**Issue by User-green** [linuxdeepin/developer-center#3912] opened 2023-03-20 20:37 UTC
### SUMMARY | 问题概要

Under KDE setup Deppin-draw associates itself with ALL types of files, not only with image ones. 
![1](https://user-images.githubusercontent.com/52010870/226459125-ee1168e5-4d98-4edd-bce0-13b323339619.png)

Please, note, that I no no Chinese and so unable to fully search the issue board, and so this issue may be a dupe.

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

Software: seem to be any deepin-draw, but tested on deepin-draw 5.10, (manjaro official repository)
KDE plasma 5.26.5

### PRE-REQUIREMENT | 预置条件

None

### STEPS TO REPRODUCE | 复现步骤

1. Install deepin-draw from official manjaro repo

### OBSERVED RESULT | 观察到的结果

Deppin-draw asoccaits itself with ALL types of files, not only with image ones. 

### EXPECTED RESULT | 期望的结果

Deepin-draw associates itself only with files, it can acctuly process (images and deepin-draw files)

### ADDITIONAL INFORMATION | 额外补充

None

**Comment by BLumia** [comment] 2023-03-21 02:18
I cannot reproduce this issue. `deepin-draw` itself didn't do the association, you can check if the installed `deepin-draw.desktop` have related field that associate them. Currently it declared the support of:

```
MimeType=image/bmp;image/bmp24;image/jpg;image/jpe;image/jpeg;image/jpeg24;image/jng;image/png;image/tif;image/tiff;image/tiff24;image/xpm;image/xbm;image/pbm;image/pgm;image/ppm;image/xpm;image/x-portable-graymap;image/x-xpixmap;image/x-xbitmap;image/x-portable-pixmap;application/x-ddf
```

and `text/css` is not one of them.

Version info for reference: `deepin-draw 6.0.1-1` on Archlinux. You might check the content of that file by yourself since it might be an issue in previous version of the application.

**Comment by User-green** [comment] 2023-03-21 05:33
I have unistalled the software since. 
In order to do testing, I will clear assocoations and re-install draw.

**Comment by User-green** [comment] 2023-03-29 11:36
I have installed deepin-draw 5.11.7-2 and checked `deepin-draw.desktop`, and indeed there is no unexpected associations. 
![изображение](https://user-images.githubusercontent.com/52010870/228523087-5b8aed2c-a2a4-45fa-8972-d171742a1cec.png)

However, issue with draw somehow asociationg itself with files it should not persists.

**Comment by BLumia** [comment] 2023-03-30 03:16
> I have installed `deepin-draw 5.11.7-2` and checked `deepin-draw.desktop`, and indeed there is no unexpected associations.

I guess we can confirm the issue does not exist then.

> However, issue with draw somehow asociationg itself with files it should not persists.

Did you mean the issue still exists? It won't do the association if `text/css` is not in the `MimeType` list. If it no longer exists on your PC, you can close the issue then :)

**Comment by User-green** [comment] 2023-04-03 06:53
> > However, issue with draw somehow asociationg itself with files it should not persists.
> 
> Did you mean the issue still exists? It won't do the association if `text/css` is not in the `MimeType` list. If it no longer exists on your PC, you can close the issue then :)
The thing is — I have removed unwanted associations via `plasma-settings`, rebooted and than reinstalled draw. But after reinstallation of the draw and one more reboot association `text/css` (and some others, not mentioned here) appeared again.

**Comment by User-green** [comment] 2023-10-01 17:01
So, _a bit later,_ I tyed this again. Deepin 6.0.6-1 and Plasma Workspace 5.27.8-1. For now seems that bug dispirited. Will comment again after reboot.

**Comment by BLumia** [comment] 2023-10-02 06:19
Thanks for the update, I think we can close this issue now :)

**Closed by BLumia** 2023-10-02 06:19 UTC
Labels: triage | need more information
